### ISSUE TITLE
Updated bmv2 to the latest version, set output log directory.

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#100]
Updated bmv2 to the latest version, and thread through flag to change output log directory for simple_switch (currently, it defaults to /tmp).

**Comment by jafingerhut** [comment]
Would be good if someone can verify whether this issue has been fixed long ago.  I believe the latest tutorials repo as of 2024-Mar-07 always puts BMv2 log files in a sub-directory of where one is running the exercise.

**Comment by jafingerhut** [comment]
Based on investigation done on another issue https://github.com/p4lang/tutorials/issues/94 I believe this one can be closed as completed, probably at least a couple of years ago.
