### ISSUE TITLE
Add exercise with state (counters, meters, registers).

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#101]

**Comment by jafingerhut** [comment]
As of 2024-Jul-07 (and I believe for several years now):

+ exercises/p4runtime demonstrates a P4 program with counters, including controller code in Python that uses P4Runtime API to read the values of those counters and display them
+ exercises/link_monitor and exercises/firewall both have P4 programs that use register arrays.

There are none that demonstrate the use of meters, but that seems like a minor omission, and reasonable to close this issue given the example programs that exist for the other features, so I am closing this issue.
