### ISSUE TITLE
Consider removing calculator example. 

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#102]

**Comment by keesjank** [comment]
I would keep it in. I think it perfectly shows the level of freedom you have to creatively solve your networking problems. It's huge!
People need to understand that they can approach their networking problem from the opposite direction: not "what features does this box have and how do I use them", but "what is the bare minimum I want this box to do." 
Somebody  should set up a contest for the most creative use of P4.

**Comment by jnfoster** [comment]
Closing this issue as we have removed then restored the exercise!
