### ISSUE TITLE
Make Error: P4 switch s1 did not start correctly.

### ISSUE THREAD

**Issue by qq995002966** [p4lang/tutorials#107]
hi guy,I followed the README under `/tutorials/P4D2_2017_Fall/exercises/p4runtime` to test `PI` function while `make` command got the follow error
```
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/advanced_tunnel.p4info --p4runtime-format text -o build/advanced_tunnel.json advanced_tunnel.p4
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
Switch port mapping:
s1:  1:h1       2:s2    3:s3
s2:  1:h2       2:s1    3:s3
s3:  1:h3       2:s1    3:s2
P4 switch s1 did not start correctly.
make: *** [run] Error 1
```

I also tryed `sudo make` but got the same error. I cannot get any useful info from the output above. Counld anybody give me some guide, thanks.
  John

---

I tried to run `sudo simple_switch_grpc topology.json` but got 
```
Thrift port was not specified, will use 9090 
Calling target program-options parser 
Field standard_metadata.clone_spec is required by switch target but is not defined
```

**Comment by bocon13** [comment]
There are two reasons that you might see "switch X did not start correctly"

1. BMv2 dies before Mininet checks (which basically means immediately)
2. The switch is not binding the gRPC port (or the [code that we use to detect the binding](https://github.com/p4lang/tutorials/blob/master/P4D2_2017_Fall/utils/netstat.py#L17:5) is broken)

To see if BMv2 is printing an error, you can check its logs:
`tail -50f /tmp/p4s.s1.log`

Also, when you run simple_switch_grpc, you should append the gRPC server address:
` -- --grpc-server-addr 0.0.0.0:50051`

**Comment by qq995002966** [comment]
Tried `tail -50f /tmp/p4s.s1.log` which show nothing.
As to `-- --grpc-server-addr 0.0.0.0:50051` , do you mean I shold first modify `utils/run_exercise.py` or some other relevant file slightly to add the params then run `make` to start the tutorial tests?

**Comment by qq995002966** [comment]
Can anybody help? I'm still struggling with this problem.
(╥╯^╰╥)

**Comment by tomyhu1995** [comment]
I have same problem. Wish that somebody can help~~~

**Comment by keesjank** [comment]
How long does it take before you get the error? There is time-out of 10 seconds for checking if the port is listening.

**Comment by tomyhu1995** [comment]
The error `P4 switch s1 did not start correctly.` occur after I enter `make`. I checked listening port before I `make` this tutorial and there were no listening ports on the list.

**Comment by tomyhu1995** [comment]
Hi all, 
I have solved this problem in this afternoon.
The following are what did I do:
1. `cd /usr/loca/lib`
2. check `/usr/local/lib` has `libbmp` 
3. `sudo ldconfig`

And then, problem solved !

Wish that my method helps you. 

Thanks

**Comment by bocon13** [comment]
@qq995002966 I meant adding `grpc-server-addr` as an argument to the `simple_switch_grpc` target:
`sudo simple_switch_grpc topology.json -- --grpc-server-addr 0.0.0.0:50051`

Can I ask how you installed the tutorial and its dependencies?

@tomyhu1995 I'm not sure why `libbmp` would be required. Do you mean something else? I could see how `sudo ldconfig` could help if that wasn't run after installing some of the dependencies.

**Comment by tomyhu1995** [comment]
@bocon13 Thanks for your advisement. I saw `fail to link libbmp shared library` when I just ran `simple_switch_grpc` before doing `sudo ldconfig` at `/usr/local/lib`.  

Thanks a lot

**Comment by qq995002966** [comment]
_Sorry about the overdue reply, I got anoying work to do._

@tomyhu1995 It seemed that my situation is different with yours  while I could run `simple_switch_grpc` without any error.
@bocon13 I'm going to use the VM to set up P4 environment.
Close this issue.
