### ISSUE TITLE
Use tutorials/SIGCOMM_2017/exercises/basic and encounter a problem.

### ISSUE THREAD

**Issue by Jacksonsq** [p4lang/tutorials#110]
I run the run.sh and encounted the problem when it shows Adding switches:

*** Adding switches:
Cannot find required executable simple_switch.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/bin:/sbin:/bin:/snap/bin)

What can I do? it's an emergency. Please give me a hand, and thank you a lot!

**Comment by qq995002966** [comment]
Maybe you should compile and install bmv2(simple_switch) first.
Follow the `README` of https://github.com/p4lang/behavioral-model.

**Comment by Jacksonsq** [comment]
@qq995002966 Thank you so much, I have solved the problem this morning.
