### ISSUE TITLE
Why there is not key in the table swtrace?

### ISSUE THREAD

**Issue by drobinkent** [p4lang/tutorials#111]
This is the swtrace for solution of exercise "mri". 

**table swtrace {
        actions = { 
	    add_swtrace; 
	    NoAction; 
        }
        default_action = NoAction();      
    }**

But if look at the P4_16  (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.pdf) section 12.2.1.1,  Then we can see 

_**If a table has no key property, then it contains no look-up table, just a default action—i.e., the associated lookup table is always the empty map**_.
 
Now, I am confused about the solution. according to P4-16 documentation only "NoAction" should be executed. But we actually need to execute the action "add_swtrace". 

Am I missing something here? Can someone please explain what is happening in the code?

**Comment by mbudiu-vmw** [comment]
The value of the default action can be changed by the control plane at runtime.

**Comment by drobinkent** [comment]
But according to P4 specification only default action will be used for this table. 

**But if look at the P4_16 (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.pdf) section 12.2.1.1, Then we can see**

_**If a table has no key property, then it contains no look-up table, just a default action—i.e., the associated lookup table is always the empty map.**_

I am confused with this part of the specification. swtrace table has no key. Then how add_swtrace action can be called?

**Comment by jnfoster** [comment]
The default action is configurable. The declaration in the table specifies
its initial value, but as @mbudiu-vmw wrote, it can be changed later by the
control plane -- e.g., to add_swtrace.

-N

**Comment by drobinkent** [comment]
@mbudiu-vmw @jnfoster  thanks.
