### ISSUE TITLE
SIGCOMM_2017 - scrambler doesn't compile

### ISSUE THREAD

**Issue by maborghe** [p4lang/tutorials#112]
exercises/scrambler/run.sh fails because scrambler.p4 doesn't compile, using the proposed solution (exercises/scrambler/solution/scrambler.p4) doesn't work either

**Comment by kevinbird61** [comment]
Scrambler in my workspace work fine. 
Can you show some error message for compile error?

**Comment by maborghe** [comment]
Well actually I noticed it's an issue I have with all the files but basic.p4.
 I'm working with the virtual machine, so I don't think it's a configuration problem, here is the error:

![screenshot from 2018-01-26 12-33-48](https://user-images.githubusercontent.com/26746380/35438073-7464f3c0-0295-11e8-8709-410053937321.png)

**Comment by jnfoster** [comment]
Some parts of the architecture (v1model.p4) changed right around the SIGCOMM tutorial. On GitHub, we've updated the starter code to be in sync with the current version of the compiler, which has v1model.p4 "baked in". But if you have an older version you might see this error. 

A simple work-around is to update the parameter from `in headers hdr` to `inout headers hdr`. You could also try doing `git pull` to grab the latest version of the tutorial starter code.
