### ISSUE TITLE
A bug in example RESUBMIT

### ISSUE THREAD

**Issue by ponderhow** [p4lang/tutorials#12]
The script         "sudo $SWITCH_PATH resubmit.json \
    -i 0@veth0 -i 1@veth2 -i 2@veth4 -i 3@veth6 -i 4@veth8 \
    --nanolog ipc:///tmp/bm-0-log.ipc --log-console \
    --pcap &"                         in run_switch.sh add 5 interfaces into the P4 switch.
But the test script in send_and_receive.py uses the veth1 and veth7 to send and receive packets respectively...It does work, and the P4 consle echos right information.  But, in fact veth1 and veth7 are not added to the p4 switch...

I have try to use other virtual ethernet interfaces to send packets which is not added to the P4 switch...It still works.

Is there some problem?

![aaa](https://cloud.githubusercontent.com/assets/5836465/20517113/9e28652a-b0d4-11e6-89ae-e1cc423660a5.PNG)

**Comment by antoninbas** [comment]
We use veth pairs here. As I found on a blog online: "they [veth pairs] are connected like a tube—whatever comes in one veth interface will come out the other peer veth interface". The pairs here are veth0-veth1, 2-3, 4-5, 6-7, 8-9. For example, when the script sends a packet on veth1, the switch receives it on port 0 (veth0).
