### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by khursheedali38** [p4lang/tutorials#120]
I followed the SIGCOMM_2017 tutorial for p4 environment setup and installation. 

I am unable to login the VM provided using the username as `p4`and password as `p4`.

Anyone else faced this issue?

**Comment by jnfoster** [comment]
That's strange. This line sets the password.
https://github.com/p4lang/tutorials/blob/master/SIGCOMM_2017/vm/root-bootstrap.sh#L44

Try "vagrant" and "vagrant" as a backup?

Otherwise my advice would be to try one of the newer developer day
directories -- e.g., the one for 2018 East Coast which was just finalized
and carefully tested this week!

**Comment by khursheedali38** [comment]
username: vagrant
password: vagrant

Thanks that helped.

**Comment by khursheedali38** [comment]
Perhaps, the username and password are for ubuntu server 16.04. 

Following the instructions when I do `vagrant up` , I should get Ubuntu Guest OS. That doesn't seem to happen. I get ubuntu server.

Any thoughts on this?

**Comment by jnfoster** [comment]
Which instructions are you referring to?

-N

**Comment by khursheedali38** [comment]
Instructions I am referring to can be found [here](https://github.com/p4lang/tutorials/tree/master/P4D2_2018_East/exercises).

**Comment by jnfoster** [comment]
I'm a little confused. Usually the distinction is between a "desktop" and "server" version of Ubuntu, not "guest," which typically refers to the OS being virtualized.

In any case, I don't see any mention of "guest" or "server" in the instructions, and when I run `vagrant up` from this directory (`P4D2_2018_East/vm`), the virtual machine builds flawlessly—i.e., a graphical desktop, with the correct passwords.

It's possible that some part of the build scripts are failing for you and it is not getting far enough to create the "p4" user and set the password, or to finish installing the packages for a graphical desktop. If that hypothesis is correct, I would need to see the complete log of the `vagrant up` command. And I'd like to know what versions of Vagrant and VirtualBox you are using, as well as details about the host OS. From these vague descriptions it's rather hard to debug your problem.

Hosting all OVA images might be nice, but saving a ~5GB file for each version of the P4 tutorial quickly eats through cloud-hosted storage.

**Comment by khursheedali38** [comment]
Ok, you got me right. By guest OS, I was referring to Ubuntu Desktop. 

Took less than 2 hours for my virtual machine to build(with the graphical desktop, with correct passwords), when i ran `vagrant up`. In fact, during the build process, the Virtual box starts up with Ubuntu Server. Although the script for building virtual machine was still running, the initial boot up of ubuntu server confused me.

Eventually, I was able to get here, thanks a lot for your assistance!!!


![github issue](https://user-images.githubusercontent.com/13725433/37234146-256a9d4e-241c-11e8-8e0f-5963d4b42004.png)
