### ISSUE TITLE
Problems getting started on Windows

### ISSUE THREAD

**Issue by red-reaper** [p4lang/tutorials#121]
I have been going through a lot of issues getting everything set up over the past few days.

I originally attempted to set up the virtual machine as instructed, but the "p4" username and "p4" password combination never worked. I then tried to install all the dependencies on a virtual machine running Ubuntu 16.04.4 LTS, but I kept running into issues at each step. Basically, dependencies kept requiring more dependencies, and I sometimes wouldn't catch errors in the outputs of the terminal, because so much was being run by the scripts each time.

I read on here that the "vagrant" username and "vagrant" password combination works so I went with that, and now I have that virtual machine running. However, I don't seem to have all the required software installed. I tried to clone the tutorials repository in my virtual machine (since it wasn't in there), and ran "make run" in "tutorials/P4D2_2018_East/exercises/basic/" but I get the same error as when I tried to install the dependencies manually, which is the following:

p4@p4:~/tutorials/P4D2_2018_East/exercises/basic$ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 -o build/basic.json basic.p4
make: p4c-bm2-ss: Command not found
../../utils/Makefile:35: recipe for target 'build/basic.json' failed
make: *** [build/basic.json] Error 127

What can be going wrong? What state is the virtual machine created supposed to be at? Am I supposed to be able to start the tutorials after having the given virtual machine set up, or do I still need to do more?

I am assuming something went wrong with the creation of the virtual machine, because it doesn't make sense to start off at the same non-functional state as when I installed dependencies manually.

PS: I have Vagrant 2.0.2 installed and Virtual Box Version 5.2.8 r121009 (Qt5.6.2).

**Comment by jnfoster** [comment]
Indeed, it looks like the P4 compiler, `p4c`, was not installed correctly. 

> Basically, dependencies kept requiring more dependencies, and I sometimes wouldn't catch errors in the outputs of the terminal, because so much was being run by the scripts each time.

There are indeed some non-trivial dependencies and it's important to have everything installed. 

Two options:
* Could you post the full log containing the output of the original `vagrant up` command and/or of your attempt to manually install the software?
* Assuming you are attending the East Coast Developer Day, have you considered downloading the VM image instead?

**Comment by khursheedali38** [comment]
It takes some time for the virtual machine to build, trying to install all the dependencies.

The reason why you aren't able to log in is that it is not the final build of your VM, it is the Ubuntu server which is being set up(username: vagrant, password: vagrant). 

So wait for the virtual machine to build completely. I encountered the same issue, you can follow the issue #120.

**Comment by red-reaper** [comment]
Thank you.. I just ran "vagrant destroy" and "vagrant up" again (as I had been doing), and this time it worked!
