### ISSUE TITLE
append data to frame

### ISSUE THREAD

**Issue by lomosewen** [p4lang/tutorials#124]
Is it possible to append more data to a frame by using P4_16? 
For example, a 100-byte frame is received, then I would like to add 8 more bytes to it to make the total outgoing frame 108-byte.

Any help would be appreciated!

**Comment by jafingerhut** [comment]
P4 as defined in the language specs deals primarily with packet headers.  Any part of a packet that is not parsed by the parser code that you wrote is considered "payload", and by default is appended to outgoing packets after the headers your program leaves valid at the end of your program execution.  So it is easily possible to add new headers at the end of, middle of, or beginning of the headers that  you parsed, but typically not possible to append after the payload (or anywhere in the middle of the payload, either).

P4 implementations are free to extend the language to do more things, but I would be surprised if the highest-performance P4 implementations have implemented the capability to append data with programmable contents after the payload.

A special case is certainly possible -- if a received packet consists completely of headers as parsed by the P4 program, up to the last byte of the packet, then adding additional headers that appear at the end of the packet is already possible today with P4.

**Comment by lomosewen** [comment]
About the special case you wrote, a packet is parsed up to the last byte, then how to add addtional headers to it? What I did is defining one more header in the struct, assigning value to it during Ingress, then using packet.emit during Deparser to append it. But the packet comes out was still the same length as before. Do you have any idea where the problem is?

**Comment by lomosewen** [comment]
I forgot to make the header valid...
Thanks for your help!
