### ISSUE TITLE
How can I start tutorials??

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#127]
I am studying p4 tutorial version 2018_east. and I read the tutorial pdf file on this directory.
but It is hard to upderstand What do I do for studying p4. 
Which file do I open or run to study lab1. basics exercise??

**Comment by jnfoster** [comment]
Detailed instructions are in the [README](https://github.com/p4lang/tutorials/blob/master/P4D2_2018_East/exercises/basic/README.md) file.
