### ISSUE TITLE
Which File Do I open when I want to run tutorial??

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#129]
I have a  question. 
I want to run tutorial 2018 in p4 github.
But I don't know Which file do I open..
Is this in the p4lane/tutorials/SiGCOMM2018/vm folder or order??
Please Let me know it.

**Comment by cool-leng** [comment]
tutorials/P4D2_2018_East/exercises/

Before you run this repo please install dependencies such as p4c.

**Comment by jnfoster** [comment]
Indeed you need to either create (e.g., using Vagrant) and boot a virtual machine or install the necessary dependencies (p4c, bmv2, mininet, etc.) from source.

**Comment by jafingerhut** [comment]
@jw1park Not sure how clear it might be from cloning the tutorials repository, but starting with one of the 2017 tutorial directories, and continuing with the 2018_East tutorial, probably the way to install the required software that takes the fewest number of steps on your part is the one described starting at "To build the virtual machine" in this README: https://github.com/p4lang/tutorials/blob/master/P4D2_2018_East/exercises/README.md

For example, on my Mac laptop, I installed Vagrant and VirtualBox as described there.  After doing that, then when I open a terminal window on my Mac, there is now a "vagrant" command installed, which I can confirm by typing "vagrant version" (mine is 2.0.1, the latest is 2.0.3 -- see https://github.com/p4lang/tutorials/issues/131#issuecomment-381725522 for a small edit you will need to make to the Vagrantfile contents below if you install vagrant version 2.0.3)

If you then do: "cd tutorials/P4D2_2018_East/vm" followed by "vagrant up", that "vagrant up" command reads the contents of Vagrantfile to create a new Ubuntu 16.04 Linux virtual machine in VirtualBox, and runs many commands inside of that virtual machine for you, _including_ running root-bootstrap.sh and user-bootstrap.sh scripts -- the last few lines of Vagrantfile mentions these files.

Even with a good Internet connection and a recent computer, "vagrant up" can easily take an hour to finish installing Ubuntu, upgrading it to the latest version, installing the GCC compiler and many other build tools, and then downloading and building the P4 development tools needed by the tutorial.

However, by the time "vagrant up" finishes, you won't need to run either of the bootstrap.sh scripts.

**Comment by jnfoster** [comment]
PR #135 is now merged, so the editing the Vagrant file is no longer needed.

I'm going to close this issue. General questions about P4 development are probably best asked on the P4 mailing lists or Slack channel.
