### ISSUE TITLE
basic of tutorials compile failed.

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#130]
I got this message after run of tutorial SIG2017/basic

[sudo] password for sds: 
Entering build directory.
Extracting package.
Reading package manifest.
> p4c-bm2-ss --p4v 16 "basic.p4" -o "basic.p4.json"
sh: 1: p4c-bm2-ss: not found
Compile failed.

What is the reason??

**Comment by kevinbird61** [comment]
Look like your p4c environment is not completed ?
Here[1] I have modified the installation script from p4lang/tutorials
It has been tested on my x86 machine.

[1]: https://github.com/toolbuddy/ssfw#p4-environment-setup

**Comment by jw1park** [comment]
Thank you for help.
I did it. but there is another issue.
When I was running user.bootstap.sh,
below message happens.

collect2: error: ld returned 1 exit status
Makefile:14672: recipe for target '/home/sds/share/ssfw/grpc/bins/opt/grpc_cpp_plugin' failed
make: *** [/home/sds/share/ssfw/grpc/bins/opt/grpc_cpp_plugin] Error 1

What should I do?

**Comment by kevinbird61** [comment]
hmm, seems that encounter grpc dependencies problems.
Or you can just using docker to pull the P4env image I've built before.

\[1\] p4 docker image (Has some information before run it) : https://hub.docker.com/r/kevinbird61/basic-p4env/
\[2\] docker installation : https://github.com/toolbuddy/ssfw#docker-installation

**Comment by SkatingLiu** [comment]
> Look like your p4c environment is not completed ?
> Here [1] I have modified the installation script from p4lang/tutorials
> It has been tested on my x86 machine.
> 
> [1]: https://github.com/toolbuddy/ssfw#p4-environment-setup

I have met the similar error, and I did as your advice, but it does not work.

mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
make: p4c-bm2-ss: Command not found
../../utils/Makefile:43: recipe for target 'basic.json' failed
make: *** [basic.json] Error 127

What should I do?

**Comment by jnfoster** [comment]
This error means the P4 compiler for Bmv2 Simple Switch (i.e., `p4c-bm2-ss`) cannot be found in your path. So you need to (re)install the compiler.
