### ISSUE TITLE
Switch port number in mininet

### ISSUE THREAD

**Issue by VerricDr** [p4lang/tutorials#137]
Hi, all,
     I am learning SIGCOMM_2017, I have a little question. When I want to set table entry manually,  for example, exercise/basic.p4, I don't know which port is connected to h1 for s1 switch, and similar question to s2 and s3.

**Comment by kevinbird61** [comment]
You can directly using `simple_switch` program, 
and run the command:
```bash
simple_switch -i 1@s1-eth1 -i 2@s1-eth2 ...
```
Which mean port 1 is connected to s1 (interface : eth1) and port 2 is connected to s1 (interface: eth2)

And in tutorial, mostly this part has been wrapped into python scripts under `utils/`.

**Comment by Polly2014** [comment]
I was puzzled by the same problem( how does switch port mapping in the bmv2 in mininet) recently.
I read and analysis the tutorials code and find it, here is the findings when exec ```make run```
```js
// Makefile
../../utils/Makefile

// Makefile
python ../../utils/run_exercise.py -t $(TOPO) $(RUN_ARGS)

// run_exercise.py
args = get_args()
exercise = ExerciseRunner(args)
  -> ExerciseRunner.__init__()
    -> self.hosts, self.switches
    -> self.links = self.parse_links(topo['links'])
exercise.run_exercise()
  -> self.create_network()
    -> self.topo = ExerciseTopo(self.hosts, self.switches.keys(), self.links, self.log_dir)
      -> ExerciseTopo.__init__()
        -> host_links, switch_links, self.sw_port_mapping = {}
          -> host_links.sort(), switch_links.sort()
          -> for link in host_links
            -> self.addHost(), self.addLink(), self.addSwitchPort()
          -> for link in switch_links
            -> self.addLink(), self.addSwitchPort(), self.addSwitchPort()
    -> self.net = Mininet()
  -> self.program_hosts()
  -> self.program_switches()
  -> self.do_net_cli()
  -> self.net.stop()
```
just focus on the ```self.port_mapping```, the links was sorted for order to make sure the ports are also predictable, then ```addSwitchPort()``` was called 
yeah, the port mapping rules just fit for mininet, not actual work. In real network, may be one should configure ```simple_switch -i 1@s1-eth1 .....```
