### ISSUE TITLE
basic make run error

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#139]
I want to exercise p4. so I run the make run from "2018/exercise/basic"
but there is a problem.
I see the message like below.
p4c-bm2-ss --p4v 16 0o build/basic.json basic.p4
../../utils/makefile:35: recipe for target 'build/basic.json' failed
make: *** [build/basic.json]error 127

What is the problem??

**Comment by maiorescuioandan** [comment]
Have you tried using elevated permissions when doing "make run"?

Try "sudo make run" instead.

**Comment by washburn125** [comment]
Hello!
Have you found  a solution for your  probleme?

**Comment by pszabop** [comment]
same problem, sudo didn't fix it.

**Comment by pszabop** [comment]
I note I had to rerun the installation scripts as they don't appear to finish from Vagrant:

Inside the VM

    cd tutorial/vm
    sudo ./root-bootstrap.sh
    sudo ./user-bootstrap.sh

After that all runs (takes a long time on a 2018 Mac, should try parallel Make), the tutorials seem to run.

**Comment by andre91998** [comment]
Is "make run" available for windows? Doesn't seem to work..

**Comment by jnfoster** [comment]
I don't believe the tutorials run on Windows.

**Comment by andre91998** [comment]
https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows 

I think this might make it work.. Unless there is another reason for which the tutorial would not work? 
I can't use linux because of a problem with my wifi card, which linux doesn't recognize.

**Comment by jafingerhut** [comment]
Most Intel/AMD-based computers can run VirtualBox, which lets you install a guest virtual machine that runs Linux.  As long as the host machine recognizes your wifi card and other hardware, the guest Linux virtual machine will only see a virtual Ethernet card, and has always worked for me.

Getting these open source tools to work on Windows, or even WSL, is probably an exercise in frustration, even for an expert in getting software working across operating systems.

**Comment by andre91998** [comment]
But then I'd basically have to use a VM within a VM right? Because the initial tutorial consists of building a VM with vagrant, then running the makefile. So if I use a VM to be able to use make, I'd have to build the "vagrant" VM within a VM

**Comment by jafingerhut** [comment]
I am not sure what you are trying to do that suggests you should run a VM within a VM.

What host OS do you have on your machine?  I've successfully used macOS as a host for running VirtualBox, do `git clone https://github.com/p4lang/tutorials`, then `cd tutorials/vm`, then `vagrant up`.  It takes about a couple of hours, and you need a good stable Internet connection, and in recent experiments I have also had to delete one line `sudo pip install grip` that fails on the Ubuntu 16.04 VM, but except for that it is possible for everything to go smoothly. (I will create a PR for removing that line soon).

**Comment by jafingerhut** [comment]
Here is the one-line change I would recommend before running `vagrant up`: https://github.com/p4lang/tutorials/pull/354

**Comment by andre91998** [comment]
I've successfully built the VM with `vagrant up` on Windows 10 (with Virtual Box). Have the GUI running, P4 user, no problem. Am I supposed to `make run` within the VM? That doesn't make much sense to me, because my cloned repo. is not in the VM

**Comment by jafingerhut** [comment]
If you successfully ran `vagrant up`, and then started up the Linux guest VM, can you run `which p4c` and see the `p4c` command in some directory, probably `/usr/local/bin` ?

If so, then all of the P4 open source development tools should also be installed and ready to go.  They will be built from source code that was latest as of some time around August or September 2019, because that is what the `vagrant up` scripts do right now.

Will that meet your needs?  Or do you want p4c and/or simple_switch built from later versions of the source code instead?

**Comment by andre91998** [comment]
I think I might try re-installing the VM because although I have the GUI working fine, the p4c command isn't present (`which p4c` returns nothing). Weird though, since `vagrant up` seemed to have executed fine.

**Comment by jafingerhut** [comment]
Make sure your host OS has enough free disk space available.  I think 15 Gbytes may be sufficient.  10 Gbytes probably isn't.  Also you may want to record the full output of `vagrant up` in a fail so you can search for failures in it, in case something went wrong somewhere in the middle, but it kept going anyway.  On macOS host, you can do `vagrant up |& tee vagrant-up-log.txt`, but I do not know what the equivalent would be on Windows.  Somehow saving the full contents of the output sent to the terminal window should do it.

**Comment by andre91998** [comment]
Apparently, this time the `vagrant up` worked as it was supposed to. Everything seems to be installed correctly and `make run` works as well. I always had more than enough disk space free though, so I'm not sure what was causing the faulty build. Thank-you for the help @jafingerhut .

**Comment by mhmdahmed97** [comment]
Hi guys, I know this is a really old thread. But I am trying to learn p4 and this installation has been a nightmare. my vagrant up command seemed to work fine as it launched a vm as p4 user. But there is absolutely nothing in that vm. Is there a possibility that vagrant up was not executed successfully?

**Comment by jfingerh** [comment]
From the evidence you describe, it sounds not only possible but likely.

If you want to download a pre-built VM, there are a few older versions linked from old tutorials listed here: https://github.com/p4lang/tutorials#older-tutorials  (follow one of those links and look for instructions to download a pre-built VM)

If you are interested in trying out a pre-built VM with Ubuntu 20.04 and only Python3, no Python2, and very limited testing but it is known for sure that the tutorial in exercises/basic works, you can try downloading this one: https://drive.google.com/file/d/13SwWBEnApknu84fG9otwbL5NC78tut-d/view?usp=sharing

You could also trying running `vagrant up` on your system again and record the output that appears in a file, publish that file somewhere, link to it in a comment here, and someone might be able to recognize what has gone wrong.  e.g. do you have at least 25 GBytes of free disk space as recommended in the README of this project?  Do you have a stable Internet connection for the entire duration of running it, as the script will cause about 2 GBytes of data to be downloaded from different web sites?

**Comment by mhmdahmed97** [comment]
Yes sir all the requirements in the README were fulfilled. However I
downloaded the prebuilt VM and that seemed to work fine. I have started my
tutorials.
Thank you very much!
