### ISSUE TITLE
Examples cannot be run due to incorrect path in env.sh

### ISSUE THREAD

**Issue by Starl1ght** [p4lang/tutorials#14]
'tutorials/env.sh' file is incorrect:
P4C_BM_PATH=$THIS_DIR/../p4c-bmv2

This string points to non-existent directory.
Looks like p4c-bmv2 was merged with p4c-bm, however, examples were not updated

**Comment by antoninbas** [comment]
This is not really an issue. The instructions here (https://github.com/p4lang/tutorials/tree/readme-env/SIGCOMM_2015) ask to clone p4c-bm as p4c-bmv2, which is causing the confusion. The `env.sh` file is supposed to be edited to match your environment. I added some information to the repo's README file to try to avoid the confusion in the future.
