### ISSUE TITLE
tutorial make run issue

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#142]
Hi I am running the tutorial basic. 
there is a problem. but I don't know why.
I just guess the script issue in netstat.py file.
How do I fix it??
here is error message.

sudo python ../../utils/run_exercise.py -t topology.json -j build/basic_tunnel.json
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 25, in <module>
    from p4_mininet import P4Switch, P4Host
  File "/home/sds/tutorials/P4D2_2017_Fall/utils/p4_mininet.py", line 26, in <module>
    from netstat import check_listening_on_port
  File "/home/sds/tutorials/P4D2_2017_Fall/utils/netstat.py", line 16, in <module>
    import psutil
ImportError: No module named psutil
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jnfoster** [comment]
It appears that your Python installation does not have `psutil`. So I'd suggest installing that package using whatever technique you prefer (pip, easy_install, etc.) or switching to a VM?
