### ISSUE TITLE
Why do we need clone_ingress_pkt_to_egress in copy_to_cpu example

### ISSUE THREAD

**Issue by extend1994** [p4lang/tutorials#144]
Hi all!
In the copy_to_cpu example,
we used `clone_ingress_pkt_to_egress` to clone and sent the packet to CPU.
But we found that we can just modify `standard_metadata.egress_spec` to 3 (CPU port) and get the same result as before.

So we are wondering what is the purpose of `clone_ingress_pkt_to_egress `?
Does anyone know this?

```p4
action do_copy_to_cpu() {
    clone_ingress_pkt_to_egress(CPU_MIRROR_SESSION_ID, copy_to_cpu_fields);
}
```

-> 
```p4
action do_copy_to_cpu() {
    modify_field(standard_metadata.egress_spce, 3);
}
```

By the way, we already knew `instance_type` would be changed to distinguish between the original and cloned packet instances. If we manually used `modify_field` to update `instance_type`, it would also be the same result.

**Comment by antoninbas** [comment]
In this example, we do not do anything with the original packet (we drop it in egress), so making a clone of the packet is not really necessary. However, if I quote the README:

> This is a very simple example obviously. Feel free to build upon it. For example, instead of dropping the original packet, you could try to broadcast it out of every non-ingress port to have a working L2 switch.

Cloning is used to send a copy of the original packet to a remote listener for various purposes: packet sampling, telemetry, flow learning... Very often, you want to "keep" the original packet and forward it normally, not drop it like in this basic example.

**Comment by extend1994** [comment]
@antoninbas Thank you for the quick response! We get a better understanding of the question we asked now :+1:
