### ISSUE TITLE
SIG2017 hula tutorial error

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#145]
I run the hula tutorial of SIG2017.
when I ping from h1 to h3 or h2, it doesn't.
I guess there is some issue in mininet script.
Is this ok in case of you??is it work well??
if anyone know why, Please tell me how to fix it.

**Comment by jw1park** [comment]
ah. iperf also does not work well.

**Comment by arijeetsat** [comment]
Try the updated tutorials.
