### ISSUE TITLE
/P4D2_2017_Fall/exercises/basic/basic.p4 not compiling with p4c-bm2-ss

### ISSUE THREAD

**Issue by MadhavChoudhary** [p4lang/tutorials#148]
This is the output shown when the command "p4c-bm2-ss basic.p4" is run.
```
basic.p4(38):syntax error, unexpected }
}
^
error: 1 errors encountered, aborting compilation
```
On trying to compile the solution basic.p4 file, the same error message came.

When I removed the comments inside empty blocks, this was the error message:
```
basic.p4(152): error: Could not find declaration for MyParser
MyParser(),
^^^^^^^^
basic.p4(153): error: Could not find declaration for MyVerifyChecksum
MyVerifyChecksum(),
^^^^^^^^^^^^^^^^
basic.p4(154): error: Could not find declaration for MyIngress
MyIngress(),
^^^^^^^^^
basic.p4(155): error: Could not find declaration for MyEgress
MyEgress(),
^^^^^^^^
basic.p4(156): error: Could not find declaration for MyComputeChecksum
MyComputeChecksum(),
^^^^^^^^^^^^^^^^^
basic.p4(157): error: Could not find declaration for MyDeparser
MyDeparser()
^^^^^^^^^^
```
The compiler was running fine on the test data. One interesting point to note is that when p4c is used instead of p4c-bm2-ss, it compiles fine and the output .json file is created.

**Comment by jafingerhut** [comment]
Thanks for the report.  I suspect this is due to a recent change made in p4c where the goal is to extract data from comments in P4 programs, e.g. for doxygen like comments.  I have filed an issue with the P4 compiler that contains a different program exhibiting the problem: https://github.com/p4lang/p4c/issues/1301

**Comment by jafingerhut** [comment]
Mihai Budiu already has a fix for the issue.  Try updating your p4c to the latest version as of today and hopefully the problem you saw will no longer occur.

**Comment by MadhavChoudhary** [comment]
Yeah, its working now. Thanks for the help and information.
