### ISSUE TITLE
MAC_LEARN SAVING ADDRESSES IN THE SWITCH INSTEAD OF RECEIVER

### ISSUE THREAD

**Issue by Chriss4P** [p4lang/tutorials#151]
Hi everyone,
I have an issue to code a mac_learn action in the P4 switch saving new source addresses IN the switch (so, without using the generate_digest action because it saves in the receiver). 
Where can I save the addresses? With which action or function? Can I use a C code in .p4 file?
please, can your help me? 
Greatings,

Chriss

**Comment by jnfoster** [comment]
This seems like a general question about P4 rather than a specific question about the tutorial. Please ask on the p4-dev list or the P4 Slack channel?
