### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by djshah19** [p4lang/tutorials#175]
Hello, 

I am getting below error. Please help me on this.

![image](https://user-images.githubusercontent.com/38405786/41254083-45c71050-6d90-11e8-84b9-faabaf201e35.png)

Thanks

**Comment by arijeetsat** [comment]
type the command  `make stop` .
Then re-run it using the command `make run`

**Comment by djshah19** [comment]
did it work for you?

**Comment by arijeetsat** [comment]
When target 'run'  fails , `make stop` clears the existing process. Is your problem solved?

**Comment by djshah19** [comment]
This does not looks like stale state. This seems to be some issue in python script. It didn't work for me. Let me know if it works for you. Thanks.

**Comment by arijeetsat** [comment]
Can we move to some other platform for discussion : https://www.linkedin.com/in/arijeetsat/

**Comment by arijeetsat** [comment]
https://www.linkedin.com/in/arijeetsat/ or arijeetsat@gmail.com
