### ISSUE TITLE
Match key in ipv6 format

### ISSUE THREAD

**Issue by djshah19** [p4lang/tutorials#176]
Hello,

How can I populate match key in ipv6 format?
![image](https://user-images.githubusercontent.com/38405786/41423855-71324ba6-6fca-11e8-912e-58db749e3810.png)

Thanks

**Comment by antoninbas** [comment]
The bmv2 runtime CLI (https://github.com/p4lang/behavioral-model/blob/master/tools/runtime_CLI.py) does not support IPv6 addresses "natively" (so you have to provide them as a 16-byte string). Feel free to submit a patch if you are a p4.org member.

**Comment by antoninbas** [comment]
Actually this is not correct. The CLI does support IPv6 addresses: https://github.com/p4lang/behavioral-model/blob/master/tools/runtime_CLI.py#L449
The screenshot that you provided also looks correct so I'm not sure what your question is.

**Comment by djshah19** [comment]
When program matches ip address with key it fails and drops packet. The format of ip address does match with key.

image
![image](https://user-images.githubusercontent.com/38405786/41489356-c23184ec-70bd-11e8-8072-01f43c7c998b.png)


I believe below piece of code populates the table

![image](https://user-images.githubusercontent.com/38405786/41489305-84fb6106-70bd-11e8-9880-912abdd6ff18.png)

How to ensure that format of key does not change?

**Comment by antoninbas** [comment]
AFAIK the 2 addresses you highlighted are exactly the same, the second one is just the full 16-byte string. It is impossible for me to explain the packet drops with that kind of information, I need the simple_switch packet processing logs. I recommend opening an issue in the behavioral-model repository and including the packet logs.
