### ISSUE TITLE
ipv6 address for addHost( )

### ISSUE THREAD

**Issue by djshah19** [p4lang/tutorials#177]
Hello,

I currently want to use mininet API to create a custom network topology. And I want every host to be configured as ipv6 address after I start the
network topology.

My question is: in mininet addHost( ) API, can I pass in ipv6 address instead of ipv4 address? If I can, could you please give me some hint about how I can do it? I tried couple times but looks like addHost( ) can not do so.

Many thanks,
Dhwani

**Comment by kevinbird61** [comment]
Look like using the command below can solve it? 
```
# create host 1
h1 = net.addHost( 'h1', mac='00:00:00:00:00:01', ip='10.0.0.1/24' )
# run ifconfig to set ipv6 addr to h1 interface
h1.cmd("ifconfig h1-eth0 inet6 add fc00::1/64")
```

**Comment by jnfoster** [comment]
Closing this now (and may I kindly suggest asking Mininet questions [here](https://github.com/mininet/mininet)?)
