### ISSUE TITLE
Basic Forwarding tutorials make run error

### ISSUE THREAD

**Issue by BEsdn** [p4lang/tutorials#178]
Hello,
I have installed bmv2 and p4c successfully. However , I run `make run` in `tutorials/exercises/basic`
it shows

```
root@lbee:~/p4lang/tutorials/exercises/basic# make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
error: Arch '' not supported by P4Runtime serializer
../../utils/Makefile:35: recipe for target 'build/basic.json' failed
make: *** [build/basic.json] Error 1
```

Do I need to install other dependencies?  
In addition, it can be successful in `SIGCOMM2017/exercises/basic` when I run `./run.sh`
Thanks

**Comment by hanw** [comment]
The correct command is `p4c-bm2-ss --std p4-16 --target bmv2 --arch v1model --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4`

**Comment by cc10512** [comment]
This error is usually seen when P4Runtime is not properly installed. Please use the instructions in https://github.com/p4lang/PI to install P4Runtime.

**Comment by BEsdn** [comment]
Hi, I have installed PI and it can find the module named p4. But when I want to try basic forwarding tutorials ,

```
root@lbee:~/p4lang/tutorials/exercises/basic# make run
mkdir -p build pcaps logs
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/root/p4lang/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/root/p4lang/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/root/p4lang/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4 import p4runtime_pb2
ImportError: cannot import name p4runtime_pb2
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1
root@lbee:~/p4lang/tutorials/exercises/basic# 
```

Then I want to find p4runtime_pb2

```
root@lbee:~# locate p4runtime_pb2
/root/p4lang/p4c/build/control-plane/p4/v1/p4runtime_pb2.py

```
it can't be found in PI respository. How can I import p4runtime_pb2? Thanks

**Comment by antoninbas** [comment]
The tutorial exercises don't work with the latest version of PI. I recommend installing a slightly older version of PI (https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L9) or better still you could use the Vagrant VM image to make sure that you have the right version for all the software dependencies.

**Comment by BEsdn** [comment]
thanks it worked for me
