### ISSUE TITLE
New to p4 and trying out new simple designs on p4c-sdnet

### ISSUE THREAD

**Issue by tijothazhone** [p4lang/tutorials#179]
Hi

I am currently working on implementing a simple switch using P4. As a start, I have designed a HW pipeline on Xilinx Vivado that will be built later on 'xcku060-ffva1156-2-e'. Initially to ensure there are packets flowing I had self-looped a 10G MAC IP. This seems to work perfectly but once I insert my P4 block (basic source and destination address swap), the whole output gets blocked. Please note I am using the p4c-sdnet compiler. Since I am fairly new to this language, could somebody help me with understanding the mistakes I am doing or at least guide me to right people who could help? 

Please help me with-
-finding what's wrong with the below code and understanding where the rest of the packet(payload) gets merged with the headers or in other words are the non-programmable blocks(For eg: demux) included automatically?(Refer P4 code below)
-All design blocks generated have inputs known as tuple_in_data &valid. What are these for? Can I get rid of them? (Refer the image of the block below)

Thanking you in advance for the help.

------------------------------------------------------------------------------------------------------------------
P4 code

#include <xilinx.p4>

header ethernet_h {
    bit<48>             dst;
    bit<48>             src;
    bit<16>             type;
}

struct headers_t {
    ethernet_h          ethernet;
}

@Xilinx_MaxPacketRegion(1518*8)  // in bits
parser Parser(packet_in pkt, out headers_t hdr) {
    state start {
        pkt.extract(hdr.ethernet);
        transition accept;
    }
}

control Pipeline(inout headers_t hdr, inout switch_metadata_t ctrl) {
  
headers_t temp;

    apply {
    
        temp.ethernet.src=hdr.ethernet.src;
        temp.ethernet.dst=hdr.ethernet.dst;
        
        if (hdr.ethernet.isValid()){
        
            hdr.ethernet.dst = temp.ethernet.src;
            hdr.ethernet.src = temp.ethernet.dst;
        }
       else
           return;
  
    }
}

@Xilinx_MaxPacketRegion(1518*8)  // in bits
control Deparser(in headers_t hdr, packet_out pkt) {
      apply {
        pkt.emit(hdr.ethernet);
    }
}

XilinxSwitch(Parser(), Pipeline(), Deparser()) main;
-------------------------------------------------------------------------------------------------------------------

PS: If somebody has worked on p4 using xilinx tools and has a working example design, please do share.

**Comment by jafingerhut** [comment]
I have not used the p4c-sdnet compiler, so I could easily be missing things
you are doing wrong that are specific to that compiler.

I can answer your question about "understanding where the rest of the
packet(payload) gets merged with the headers".  In the P4_16 language
variant that you are using, any part of the packet that is not 'extract'ed
during your parsing code is considered "the payload" for that particular
packet.  If you do not drop a packet or do anything else special to it
(e.g. truncating the payload), then after any headers that you explicitly
do "emit" calls for in your deparser code, the payload is appended after
the last header you emit, to the outgoing packet.

The only thing I wonder about in terms of swapping the destination and
source Ethernet addresses in a frame is: if the destination Ethernet
address of a frame is multicast, or broadcast (all 48 bits are 1), and you
put that into the source Ethernet address, are there pieces of hardware or
software that will treat that as a bad Ethernet packet?  Ethernet source
addresses are typically required to be unicast addresses, I believe.

Andy

**Comment by gbrebner** [comment]
Tijo,
Re. Andy’s remarks below, your P4 program looks correct, and would have the effect you expect.

It looks like your issue is more to do with the integration of the block generated by the p4c-sdnet compiler into the rest of your hardware pipeline.  I suggest that you look first at Chapter 6 of the SDNet user guide (https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_1/UG1012-sdnet-packet-processor.pdf) for help with this integration.  In general, the generated interfaces with “tuple” in their names correspond to metadata inputs or outputs.  Note that the XilinxSwitch architecture you are using has a metadata inout called “control” – see p.10 of the P4-SDNet user guide (https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_1/ug1252-p4-sdnet.pdf).

Hope this helps.

Best wishes,
Gordon.

**Comment by tijothazhone** [comment]
Thank you @jafingerhut and @gbrebner for the immediate response.

@gbrebner, I had followed every step while integrating the P4 custom block. The sdnet example titled OF_classifier seems to work perfectly fine by following the above-mentioned procedure. But when I compile from p4 nothing seems to go through.
I believe there is something wrong with the pipeline block even though there is no lookup happening. Theoretically shouldn't the pipeline block be optional? How can I make it optional? I suppose in that case I won't be able to xilinx.p4 anymore.

@jafingerhut, is .emit helps demux the entire packet. How do I utilize the aribiter block incase I need to pass packets coming out of say 5 MAC IPs?

Regards,

**Comment by gbrebner** [comment]
The block named pipeline, which is a P4 control, is part of the XilinxSwitch architecture and so must be there.  However, you are actually using it in the P4 program you sent:
control Pipeline(inout headers_t hdr, inout switch_metadata_t ctrl) { … }
where you are swopping the Ethernet MAC addresses.

Re. your original question, note that this control has the metadata inout argument, which corresponds to a tuple input/output interface that you must connect up when putting the generated P4 block into your design.  Referring to the xilinx.p4 include file, you will see the definition of the type switch_metadata_t:
typedef bit<4> switch_port_t;
struct switch_metadata_t {
    switch_port_t ingress_port;
    switch_port_t egress_port;
}
This means that ctrl will be an 8-bit (4+4) input and output tuple.  If you do not care about passing input and output port information through your design, you could just tie the input to all zeroes and send the output to a sink.

Gordon.

**Comment by tijothazhone** [comment]
@gbrebner, I have connected both the tuples to zero and the enable to '1'. The output tuples are simply unconnected.(Refer attachment)
Since I am trying to find out reasons as to why p4 isn't working for me? Could you tell me what is the difference between using sume_switch.p4 and xilinx.p4(currently used)? Does this only have an effect only on the switch interface we define? For example, in the case of parser- 
_in sume_switch.p4_

**parser Parser<H, M, D>(packet_in b,
                       out H parsedHeaders,
                       out M user_metadata,
                       out D digest_data,
                       inout sume_metadata_t sume_metadata);**
-----------------------------------------------------------------------------------------
_in xilinx.p4 it is_ 

**parser XilinxParser<L>(
    packet_in packet, out L local);**
-----------------------------------------------------------------------------------------

Or does this change based on the board one is using? I am currently working on Kintex ultrascale (xcku060-ffva1156-2-e). Nowhere in the Chapter 6 (https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_1/UG1012-sdnet-packet-processor.pdf) there is any mention of how a user could mention the board he/she is using. **Can this be something that I am doing wrong?**

Secondly, can the OS(gentoo linux) be an issue?

Regards,
Tijo

**Comment by gbrebner** [comment]
Closing issue here since not relevant to P4 tutorials.  Will follow up in direct email with @tijothazhone.

**Comment by tijothazhone** [comment]
@gbrebner ,please could we communicate via email. My email id is tijothazhone@gmail.com
