### ISSUE TITLE
Solution of flowlet switching tutorial

### ISSUE THREAD

**Issue by AmedeoSapio** [p4lang/tutorials#18]
In the proposed solution for the flowlet switching tutorial 
(simple_router.p4 in  https://github.com/p4lang/tutorials/blob/master/SIGCOMM_2015/flowlet_switching/solution.tar.gz)

- The timestamp is defined as 32 bits in the metadata _ingress_metadata_t_ (fields _flowlet_lasttime_ and _flow_ipg_) and in the register _flowlet_lasttime_, but I think should be 48 bits. In fact in the intrinsic.p4 file the timestamp is defined as 48 bits (correct according to https://github.com/p4lang/tutorials/blob/master/SIGCOMM_2016/p4-tutorial-slides.pdf).

- In the action _lookup_flowlet_map()_ the call to 
_modify_field_with_hash_based_offset()_ 
has _FLOWLET_MAP_SIZE_ (=13) as size value, but I think it should be 2^13=8192.

The P4_14 document says:

> _modify_field_with_hash_based_offset(dest, base, field_list_calc, size)_
> ...
> _size_ (VAL) The size of the hash value range. Must be larger than 0.
> ...
> The hash value is used to generate a value between base and (_base_ + _size_ - 1) by calculating (_base_ + (_hash_value_ % _size_)).

so _size_ should be the max value that the result can have +1, not the number of bits.

**Comment by antoninbas** [comment]
Thanks @AmedeoSapio I opened a pull request to fix this
