### ISSUE TITLE
Errors when compiling P4_14 code

### ISSUE THREAD

**Issue by djshah19** [p4lang/tutorials#180]
Hello,

I am getting below errors when compiling P4_14 code. Please help me fix these errors.
![image](https://user-images.githubusercontent.com/38405786/42061374-e82d5894-7af7-11e8-92d3-7e52750bf3c1.png)

here is the code

#include <tofino/intrinsic_metadata.p4>
#include <tofino/constants.p4>
#include <tofino/stateful_alu_blackbox.p4>

/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/
// Standard L2 Ethernet header

header_type ethernet_t {
    fields {
        
                            dstAddr : 48;
        
                            srcAddr : 48;
        
                            etherType : 16;
    }
}

// Standard IPv4 header

header_type ipv4_t {
    fields {
        
                            version : 4;
        
                            ihl : 4;
        
                            diffserv : 8;
        
                            totalLen : 16;
        
                            identification : 16;
        
                            flags : 3;
        
                            fragOffset : 13;
        
                            ttl : 8;
        
                            protocol : 8;
        
                            hdrChecksum : 16;
        
                            srcAddr : 32;
        
                            dstAddr: 32;
    }
}

header ethernet_t ethernet;
header ipv4_t ipv4;

/************************************************************************* 
*********************** P A R S E R  *********************************** 
*************************************************************************/ 
// Start with ethernet always.
     parser start { 
         return parse_ethernet; 
     } 
 
#define ETHERTYPE_IPV4 0x0800
 
     parser parse_ethernet { 
         extract(ethernet); 
         return select(latest.etherType) { 
             ETHERTYPE_IPV4: parse_ipv4; 
             default: ingress; 
         } 
     } 
 
 
     parser parse_ipv4 { 
         extract(ipv4); 
         return ingress;  // All done with parsing; start matching
     } 
 
 
/*************************************************************************
**************  I N G R E S S   P R O C E S S I N G   *******************
*************************************************************************/
// Drop the packet;
action drop_pkt(){
drop();
}

action ipv4_forward(dst_mac){
modify_field(ethernet.src_addr, ethernet.dst_addr);
modify_field(ethernet.dst_addr, dst_mac);
add_to_field(ipv4.ttl, -1);
}

table ipv4_lpm{
reads{
ipv4.dstAddr: lpm;
}
actions{
ipv4_forward;
drop_pkt;
no_op; // Take no action 
}
max_size: 20000;
default_action: drop_pkt;
}

apply{
if(valid(ipv4)){
apply(ipv4_lpm);}
}

 

Many thanks,
Dhwani

**Comment by cc10512** [comment]
Hi Dhwani,

Please stop posting questions about the Barefoot SDE and Tofino on public forums. The correct channel for these questions is the Barefoot support portal. If there are issues that prevent you from using that channel, please let me know by writing directly to my email address: cascaval@barefootnetworks.com <mailto:cascaval@barefootnetworks.com>.

I hope you understand that you have signed a legal agreement when Barefoot gave you access to the SDE. Please read carefully the terms, and if you have questions about the usage, let me know. I will get someone in Barefoot explain them to you.

Thanks, Calin

—
Calin Cascaval, PhD
Director, Compilers and Tools
Barefoot Networks
cascaval@barefootnetworks.com
