### ISSUE TITLE
Error: gRPC UNIMPLEMENTED

### ISSUE THREAD

**Issue by vvkgopalan** [p4lang/tutorials#181]
Hi All,
I'm a student aiming to make use of the p4runtime API this summer and am in the process of going through the tutorials. I've run into this error when running mycontroller.py and have not found a similar error log online. 
Traceback (most recent call last):
  File "./mycontroller.py", line 222, in <module>
    main(args.p4info, args.bmv2_json)
  File "./mycontroller.py", line 167, in main
    s1.MasterArbitrationUpdate()
  File "/home/vagrant/tutorials/exercises/p4runtime/../../utils/p4runtime_lib/switch.py", line 68, in MasterArbitrationUpdate
    for item in self.stream_msg_resp:
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 344, in next
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 324, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, )>
Am running this on the vagrant vm - did not run into problems on the installation though "unimplemented" makes me believe something is missing from my install of p4runtime. Please let me know if any of y'all have run into this problem & have a potential solution!

**Comment by endrigoshi** [comment]
Hi @vvkgopalan !
Did you solve this problem? I have having the same error with the latest code of P4Runtime.

**Comment by NE4Y** [comment]
Hi @endrigoshi  and @vvkgopalan,

die you manage to find a solution or a previous version of the p4runtime which is compatible to the current bmv2?

**Comment by endrigoshi** [comment]
hi @NE4Y ,
if you mean that the tutorials to be compatible with the latest version of P4Runtime then take a look at this issue here https://github.com/p4lang/PI/issues/417 .
With the changes that I have explained there, the lastest code of PI, p4c and bmv2 work together with no problem.
