### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by jw1park** [p4lang/tutorials#182]
during run exercises, I see this message.
What is the problem??

../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by arijeetsat** [comment]
Refer #175

**Comment by pszabop** [comment]
I note I had to rerun the installation scripts as they don't appear to finish from Vagrant:

Inside the VM

    cd tutorial/vm
    sudo ./root-bootstrap.sh
    sudo ./user-bootstrap.sh

After that all runs (takes a long time on a 2018 Mac, should try parallel Make), the tutorials seem to run.

**Comment by jnfoster** [comment]
Closing this issue as it seems to have been solved.
