### ISSUE TITLE
p4runtime exercise: ./mycontroller.py: 'module' object has no attribute 'P4RuntimeStub'

### ISSUE THREAD

**Issue by qiaokang92** [p4lang/tutorials#184]
Hi,

I'm seeing this issue when running ./mycontroller.py in p4runtime exercise.

```
$./mycontroller.py
Traceback (most recent call last):
  File "./mycontroller.py", line 183, in <module>
    main(args.p4info, args.bmv2_json)
  File "./mycontroller.py", line 126, in main
    device_id=0)
  File "/home/qiaokang/p4-workspace/p4-tutorials-learn/P4D2_2018_East/exercises/p4runtime/p4runtime_lib/switch.py", line 28, in __init__
    self.client_stub = p4runtime_pb2.P4RuntimeStub(self.channel)
AttributeError: 'module' object has no attribute 'P4RuntimeStub'
```

I have read https://github.com/p4lang/tutorials/issues/114, what I have done includes

1) rolled back PI to git commit 219b3d67299ec09b4 (suggested by the user-bootstrap.sh file)
2) reinstalled PI.

But the problem still exists. Any idea?

Thanks,
Qiao

**Comment by ccascone** [comment]
Looking at #114, it seems the error is due to a more recent version of grpc rather than PI. Make sure you are running the same version of grpc as the one in `user-bootstrap.sh`.

Otherwise, @antoninbas suggests:

> I have done some research and I've been able to confirm that this is because you are using a more recent version of grpc than we support. grpc stubs are no longer included in p4runtime_pb2.py and you have to use p4runtime_pb2_grpc.py with recent versions of grpc.
> 
> If you want to keep using your version of grpc you will need to:
> 
> * Modify this p4lang/PI makefile to install *_grpc.py files: https://github.com/p4lang/PI/blob/master/proto/Makefile.am#L98
> * Modify the relevant Python files in this repo - tutorials - to use p4runtime_pb2_grpc.py instead of p4runtime_pb2.py when appropriate (i.e. for grpc stubs).

**Comment by qiaokang92** [comment]
Thanks, I have rolled back grpc to an older version (v1.6.0) and this issue disappeared.

**Comment by cslev** [comment]
I had the same issues with wrong versions, but a lower level and even the connection to the switch was not working due to "not master" error.
I have compiled everything and the above-mentioned failure could have been resolved by importing p4runtime_pb2_grpc as well in switch.py, and modify the __init__ function accordingly:
```
**from p4.v1 import p4runtime_pb2_grpc as p4runtime_pb2_grpc**
from p4.v1 import p4runtime_pb2

from p4.tmp import p4config_pb2

class SwitchConnection(object):
    def __init__(self, name, address='127.0.0.1:50051', device_id=0):
        self.name = name
        self.address = address
        self.device_id = device_id
        self.p4info = None
        self.channel = grpc.insecure_channel(self.address)
        **self.client_stub = p4runtime_pb2_grpc.P4RuntimeStub(self.channel)**
```
Everything else can be the same, and the controller will work.
