### ISSUE TITLE
Does p4_16 support copy_to_cpu?

### ISSUE THREAD

**Issue by antonywei** [p4lang/tutorials#185]
In p4_14, the tutorials gives us an example to show how to copy a package and send to special port. However, it seem been delete in p4_16, so what should I do to copy a package and send to multiple ports in p4_16?
Thank you very much 

```
action do_copy_to_cpu() {
clone_ingress_pkt_to_egress(CPU_MIRROR_SESSION_ID, copy_to_cpu_fields);
}
```

**Comment by jnfoster** [comment]
This is the repository for tracking technical issues in the P4 tutorial source code, not general questions about the language.

I suspect you'll get a faster response if you ask your question on the [p4-dev](http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) list or the [P4 Slack](https://p4-lang.slack.com/join/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
