### ISSUE TITLE
Is there any way to log what's happening in DP?

### ISSUE THREAD

**Issue by qiaokang92** [p4lang/tutorials#187]
Just want to know if there is something like `printf` in p4 which could help debug. I searched the spec but didn't find any clue.

Any ideas would be appreciated.

**Comment by antoninbas** [comment]
There isn't a `printf` P4 built-in (or v1model extern), even though that could be an interesting open-source contribution. (Of course that would mostly be useful for debugging P4 programs on a software switch, it is unlikely that P4-programmable HW would implement that functionality).

What you can do is use the bmv2 debugger to set breakpoints and print field values: https://github.com/p4lang/behavioral-model/blob/master/docs/p4dbg_user_guide.md

**Comment by jafingerhut** [comment]
When simple_switch is run with the `--log-console` command line option, or `--log-file`, then every time a table is searched, the names and values of all fields in the search key are printed as debug output.  Thus creating a table with a 'no op' default action, and whatever header or metadata fields you want to know the current value of as search key fields, is one way to effectively get a 'debug print' statement in a P4 program, when run on simple_switch.

**Comment by qiaokang92** [comment]
Thanks @antoninbas and @jafingerhut , very helpful answers!
