### ISSUE TITLE
hash in p4

### ISSUE THREAD

**Issue by zenhox** [p4lang/tutorials#188]
I use  a crc16 hash algorithm in p4 code, like below:
              hash(
                   flow_hash,
                   HashAlgorithm.crc16,
                   16w0,
                   { hdr.ipv4.srcAddr, hdr.ipv4.dstAddr, hdr.udp.srcPort},
                   32w65536);
I store something in  a register, and the index is determined  by the value flow_hash.
But now I want to read the register value by  thrift CLI.
So I need to replay the hash algorithm using the same  tuple.
I can query the register by python, but how can I get the same digest that p4 program get.
I don't know how p4 do the hash on this kind of tuple.

**Comment by antoninbas** [comment]
For bmv2, the hash functions are implemented there: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/calculations.cpp
bmv2 uses standard crc polynomials, so you should be able to use a Python package such as crcmod to compute the hash in a way which is consistent with the bmv2 implementation. The easiest way is probably to use the `crc16_custom` hash in P4 instead of `crc16` and configure the polynomial with the `set_crc16_parameters` runtime_CLI command. This way you can choose the exact polynomial you want and make sure you use the same in bmv2 and in your "control plane" Python script.

**Comment by zenhox** [comment]
Yeah, That is what i needed. Thank you.

**Comment by Benature** [comment]
Hi, @antoninbas 

I use `crc16_custom` to do the hash with `set_crc16_parameters`

```python
self.controllers[sw_name].set_crc16_parameters("calc_0", 0x18005, 0x0000, 0b1111111111111111, True, False)
```

but the python raise UIn_Error: `Error: Integer cannot fit within 16 bits`, see `hex_to_i16()` function in `runtime_API.py`
```python
def hex_to_i16(h):
    if type(h) != int:
        h = int(h, 0)
    if (h > 0xFFFF):
        raise UIn_Error("Integer cannot fit within 16 bits")
    if (h > 0x7FFF):
        h -= 0x10000
    return h
```
So the poly should not be larger than `0xFFFF`.

However, in `crcmod`, there is a verify function requires the poly's width should be 16
```python
def _verifyPoly(poly):
    msg = 'The degree of the polynomial must be 8, 16, 24, 32 or 64'
    for n in (8,16,24,32,64):
        low = 1<<n
        high = low*2
        if low <= poly < high:
            return n
    raise ValueError(msg)
```
when I generate a crc16 function, using a smaller poly
```python
crc16 = crcmod.mkCrcFun(0x8d95, initCrc=0, xorOut=0b1111111111111111, rev=True)
```
---
Those two requirements in crcmod and runtime_API are incompatible, so how can I re-calculate the hash value in my "control plane" Python script? Or is there something I mis-understand?

**Comment by antoninbas** [comment]
It's been a while since I last looked at it. But I would guess that bmv2 doesn't want you to explicitly provide the leading "1" for the polynomial, while crcmod requires you to. So a `0x1021` polynomial for bmv2 would be equivalent to a `0x11021` polynomial for crcmod.

**Comment by Benature** [comment]
Thank you, @antoninbas 

There is one more question, when the number of input data is more one, say I hash ingress port and egress port
```p4
        hash(
            result,
            HashAlgorithm.crc16,
            (bit<1>)0,
            {   
                standard_metadata.ingress_port
                standard_metadata.egress_port
            },
            (bit<16>)0xffff);
```

Then how can I compute the same hash in python? Assume that I get the correct hash function `crc16`
```python
ingress_port = 2
egress_port = 1
hash_result = crc16(struct.pack('B', ingress_port + egress_port)) # I try naive add but it seems not right
```

**Comment by antoninbas** [comment]
The bmv2 implementation (for building the buffer before computing the hash) is there: https://github.com/p4lang/behavioral-model/blob/f16d0de3486aa7fb2e1fe554aac7d237cc1adc33/src/bm_sim/calculations.cpp#L64

IIRC, `standard_metadata.ingress_port` and `standard_metadata.egress_port` are 9-bit fields. So I would expect a 2-byte buffer, which would look like this: `<9bits = ingress port><9bits = egress port><6bits = zero padding>`.
I don't think you can use the `struct` Python package to build this, as it assumes byte-aligned types. You need to do some bit-level manipulation.

**Comment by Benature** [comment]
Thank you! That helps a lot!
