### ISSUE TITLE
p4runtime: gRPC Error: Connect Failed (UNAVAILABLE) [./mycontroller.py:156]

### ISSUE THREAD

**Issue by qiaokang92** [p4lang/tutorials#190]
Hi,

I'm learning the p4runtime exercise.

`make` works for me, but when I type `./mycontroller.py`, there was an error message:
```
gRPC Error: Connect Failed (UNAVAILABLE) [./mycontroller.py:156]
```

Then I checked `sudo netstat -lpnt`, I found 50051 and 50052 disappeared (they appeared after `make`).

```
(disappeared) tcp6       0      0 :::50051                :::*                    LISTEN      45456/simple_switch
(disappeared) tcp6       0      0 :::50052                :::*                    LISTEN      45461/simple_switch
tcp6       0      0 :::50053                :::*                    LISTEN      45466/simple_switch
```
I'm using grpc version 1.6.0. Any ideas?

Thanks,
Qiao

**Comment by zengman** [comment]
I met same problem with you and I solved it by unsetting my http_proxy

**Comment by Just-yyc** [comment]
You can use the command in your shell (the ./mycontroller.py ) ：unset http_proxy （or unset https_proxy）

**Comment by jnfoster** [comment]
I have not experienced this error, but it sounds like there is consensus on the solution. Marking this as closed.
