### ISSUE TITLE
 basic tutorial:P4 switch s1 did not start correctly.

### ISSUE THREAD

**Issue by rdhillbb** [p4lang/tutorials#193]
I get the following error

mkdir -p build pcaps logs
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
Switch port mapping:
s1:  1:h1	2:s2	3:s3	
s2:  1:h2	2:s1	3:s3	
s3:  1:h3	2:s1	3:s2	
P4 switch s1 did not start correctly.
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by rdhillbb** [comment]
I found my issue. wrong version of libprotobuf linked.

**Comment by jnfoster** [comment]
👍
