### ISSUE TITLE
 Tutorial Basic Exercise Error 127 Make Run

### ISSUE THREAD

**Issue by washburn125** [p4lang/tutorials#203]
I have successfully installed P4 VM, but I have a probleme when I run 'Make run' command.  

vagrant@p4:~/tutorials/exercises/basic$ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
make: p4c-bm2-ss: Command not found
../../utils/Makefile:35: recipe for target 'build/basic.json' failed
make: *** [build/basic.json] Error 127

I don't undertand what my next step should be.  What is a solution for the problem?

Thank you

**Comment by SuperKittyFan** [comment]
The p4c is not installed in your vagrant vm. Try to install the vm in the tutorial instead, because other vm may skip this step.
