### ISSUE TITLE
Vagrant URL 404

### ISSUE THREAD

**Issue by jwbensley** [p4lang/tutorials#204]
`vagrant up` fails as the vagrant image has/is moving location.

I think the Vagrant file should be updated from `config.vm.box = "fso/xenial64-desktop"` to `config.vm.box = "lasp/ubuntu16.04-desktop"`

The original setting throws the error:
```
==> p4-tutorial: Adding box 'fso/xenial64-desktop' (v2018.10.08.0) for provider: virtualbox
    p4-tutorial: Downloading: https://vagrantcloud.com/fso/boxes/xenial64-desktop/versions/2018.10.08.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

**Comment by riftadi** [comment]
Yes, I can confirm this issue also happened in my setup. Proposing to fix it in PR #206.

**Comment by random1001guy** [comment]
When I run "vagrant up", it fails with the following error(displayed in red) - 
URL: ["https://vagrantcloud.com/lasp/ubuntu16.04-desktop"]
Error: The requested URL returned error: 404 Not Found

**Comment by jafingerhut** [comment]
I see the same error when attempting "vagrant up" on a machine that does not already have the 1.5 GByte base image file cached already.  When I use a browser to try to go that URL, it gives the message below.  This URL used to link to an image that seemed to be accessible by everyone, which leads me to wonder whether the possibility mentioned below might be true now?  "The resource exists, but its owner organization is delinquent"



404 Not Found
Sorry, the page /lasp/boxes/ubuntu16.04-desktop could not be found.

This error could mean one of three things:

The resource doesn't exist
The resource exists, but requires proper authorization to access
The resource exists, but its owner organization is delinquent
If someone has linked you to this resource, ensure that they have given you proper permissions to access it.

**Comment by jafingerhut** [comment]
Addendum to my previous comment: I believe I last tested this working some time in December 2019, so it seems that the URL for the base Ubuntu Linux VM image became stale/inaccessible/broken somehow since then.

**Comment by twitu** [comment]
Hi I am facing the same issue. Is there any other URL where the VM image can be downloaded from?

**Comment by jafingerhut** [comment]
@twitu If you do not mind downloading a prebuilt VM, there are some linked from the August 2019 SIGCOMM tutorials section near the end of the readme here: https://github.com/p4lang/tutorials

**Comment by twitu** [comment]
I decided against a prebuilt VM and installed from source. I installed from source using the [user bootstrap script](https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh). Thanks for maintaining such a helpful script that just works.
