### ISSUE TITLE
simple_switch_grpc not found.

### ISSUE THREAD

**Issue by gharshr** [p4lang/tutorials#212]
While Running the tutorial, it shows the below error.
```
ubuntu@param-HP-280-G2-MT-Legacy:~/p4c/tutorials/exercises/basic$ make run
mkdir -p build pcaps logs
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
[sudo] password for ubuntu: 
Reading topology file.
Building mininet topology.
Switch port mapping:
s1:  1:h1	2:s2	3:s3	
s2:  1:h2	2:s1	3:s3	
s3:  1:h3	2:s1	3:s2	
Cannot find required executable simple_switch_grpc.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1
```

Checked the above directories, the bin file with above name is not there.
Have installed bmv2 and PI.
What can be the steps to install the simple_switch_grpc?

**Comment by antoninbas** [comment]
If you plan on running the tutorial exercises, you should use the provided VM (https://github.com/p4lang/tutorials/tree/master/vm). If you try to install the latest version of the software (PI, bmv2, compiler), you may run into compatibility issues.

That being said, you can look at the VM scripts for the installation steps (https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh) and reproduce them. Instructions to install simple_switch_grpc are also included in this README: https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc

**Comment by gharshr** [comment]
Yes, I checked it. Directly used the vagrant file to setup.

Did it manually first, issue was about the google protocol buffer version. So hence the compatibility issues. Thanks.
