### ISSUE TITLE
I need help with P4

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#213]
I know this might sound silly to some of you but I sincerely need help understanding the P4 tutorials. I am stuck at the basic which is supposed to be the easiest but it seems to me that you need prior knowledge in something. I just don't know what that is. If you do, I will be grateful if you can make a tutorial walkthrough or anything that will help me. This is my email:bbaby6205@gmail.com. Thank you.

**Comment by jafingerhut** [comment]
I don't know if it explains what you need to know, but give this P4 program a read, with its heavy comments:
+ https://github.com/jafingerhut/p4-guide/blob/master/demo1/demo1-heavily-commented.p4_16.p4

Also this explanation of some of the open source P4 tools, and what role they play in simulating a single switch running a P4 program:
+ https://github.com/jafingerhut/p4-guide/blob/master/README-using-bmv2.md

Also there is interactive chat with other P4 developers available here that you may be able to get some questions answered: https://p4-lang.slackc.om

**Comment by Juniortheone** [comment]
> 
> 
> I don't know if it explains what you need to know, but give this P4 program a read, with its heavy comments:
> 
>     * https://github.com/jafingerhut/p4-guide/blob/master/demo1/demo1-heavily-commented.p4_16.p4
> 
> 
> Also this explanation of some of the open source P4 tools, and what role they play in simulating a single switch running a P4 program:
> 
>     * https://github.com/jafingerhut/p4-guide/blob/master/README-using-bmv2.md
> 
> 
> Also there is interactive chat with other P4 developers available here that you may be able to get some questions answered: https://p4-lang.slack.om

Thank you very much.I'm truly grateful.
