### ISSUE TITLE
How much disk space  is required to run the VM and to install the Software within the VM ? 

### ISSUE THREAD

**Issue by shankru5** [p4lang/tutorials#214]
Looks like huge amount of memory is required. Can someone please clarify the approximate disk space required ?

**Comment by jnfoster** [comment]
The VM is indeed currently large, mostly because it's based on a
not-very-minimal Ubuntu graphical desktop image. The OVA file is ~2.5GB,
which VirtualBox expands to 7.25GB on my machine.

If someone feels inspired to build a new VM starting from a smaller base
image, that would be fantastic.

-N
