### ISSUE TITLE
Error occur when I try to import IPv6 address in mycontroller.py of p4runtime exercise

### ISSUE THREAD

**Issue by shijinyu-bjtu** [p4lang/tutorials#216]
I want to insert some tables that include IPv6 address by mycontroller.py in p4runtime exercise, but Error occur when I run the `./mycontroller.py`. the error are described as follows:
`
-  Installed P4 Program using SetForwardingPipelineConfig on s1
-  Installed P4 Program using SetForwardingPipelineConfig on s2
-  Installed ingress ipv4_lpm on s1
-  Installed ingress mytunnel_lpm on s1
- Traceback (most recent call last):
-   File "./mycontroller.py", line 201, in <module>
-     main(args.p4info, args.bmv2_json)
-   File "./mycontroller.py", line 159, in main
-     dst_eth_addr3="00:00:00:02:04:00", dst_port3=4)
-   File "./mycontroller.py", line 58, in writeTunnelRules
-     "port": dst_port2
-   File "/home/myp4/P4/tutorials/exercises/contro_multipro/../../utils/p4runtime_lib/helper.py", line 191, in buildTableEntry
-     for field_name, value in action_params.iteritems()
-   File "/home/myp4/P4/tutorials/exercises/contro_multipro/../../utils/p4runtime_lib/helper.py", line 160, in get_action_param_pb
-     p4runtime_param.value = encode(value, p4info_param.bitwidth)
-   File "/home/myp4/P4/tutorials/exercises/contro_multipro/../../utils/p4runtime_lib/convert.py", line 81, in encode
-     assert(len(encoded_bytes) == byte_len)
- AssertionError

`
the parameters of ipv4_lpm and myTunnel_lpm are IPv4 address，so these two tables insert successfully.but the next table's parameters ars IPv6 addresss.

**Comment by kevinbird61** [comment]
I supposed that reason is the P4Host has disabled IPv6?

https://github.com/p4lang/tutorials/blob/master/utils/p4_mininet.py#L40

**Comment by shijinyu-bjtu** [comment]
@kevinbird61 
thanks for your help , I've tried the solution you provide, but the Errors still exist.

**Comment by jnfoster** [comment]
The Python code provided in the tutorials does not support IPv6. You'd have to extend it with additional functionality -- e.g.,here https://github.com/p4lang/tutorials/blob/master/utils/p4runtime_lib/convert.py#L60

**Comment by shijinyu-bjtu** [comment]
@jnfoster 
thanks for you help，the fact has proved that you are right and the problem has been solved.
I rewrite the python code 
`
ipv6_pattern = re.compile('^([\da-fA-F]{1,4}:){7}([\da-fA-F]{1,4})$')
def matchesIPv6(ipv6_addr_string):
    return ipv6_pattern.match(ipv6_addr_string) is not None
def encodeIPv6(ipv6_addr_string):
    return ipv6_addr_string.replace(':', '').decode('hex')
def decodeIPv6(encoded_ipv6_addr):
    return ':'.join(s.encode('hex') for s in encoded_ipv6_addr)
......
def encode(x, bitwidth):
    'Tries to infer the type of `x` and encode it'
    byte_len = bitwidthToBytes(bitwidth)
    if (type(x) == list or type(x) == tuple) and len(x) == 1:
        x = x[0]
    encoded_bytes = None
    if type(x) == str:
        if matchesMac(x):
            encoded_bytes = encodeMac(x)
        elif matchesIPv4(x):
            encoded_bytes = encodeIPv4(x)
        elif matchesIPv6(x):
            encoded_bytes = encodeIPv6(x)
        else:
            # Assume that the string is already encoded
            encoded_bytes = x
    elif type(x) == int:
        encoded_bytes = encodeNum(x, bitwidth)
    else:
        raise Exception("Encoding objects of %r is not supported" % type(x))
    assert(len(encoded_bytes) == byte_len)
    return encoded_bytes
`
but there are still some problem:
1、It can't support the form  ' :: ' 
2、I'm not sure  if I can use the python package that named socket  to achieve it.(like the method used in decodeIPv4 and encodeIPv4)?
