### ISSUE TITLE
when I want to run P4 on ubuntu 16.04 , an error happened

### ISSUE THREAD

**Issue by MoonTseng** [p4lang/tutorials#218]
I have already installed bmv2 p4c Protocol Buffers .
But I run make -j4 check  %82 tests passed
Then i run "sudo make run " like below in 
### **~/P4/tutorials/exercises/basic$ sudo make run
[sudo] raytseng 的密码： 
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
make: p4c-bm2-ss：命令未找到
../../utils/Makefile:35: recipe for target 'build/basic.json' failed
make: *** [build/basic.json] Error 127**

**Comment by MoonTseng** [comment]
How can i fix it?

**Comment by kevinbird61** [comment]
Seems that you don't have *correctly* installed p4 compiler yet (p4c-bm2-ss is the  compiler for BMv2).

**Comment by jafingerhut** [comment]
If you start with a fresh installation of Ubuntu 16.04 Linux and run the bash shell script below with an Internet connection, it should correctly download, build, and install the p4lang/behavioral-model simple_switch software switch, and p4lang/p4c compiler:

https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh

It will probably work on at least some other Ubuntu 16.04 Linux systems that are not fresh installs, too, but there are some packages that can conflict with each other, so I can't promise it will work on others.

**Comment by anonymity12** [comment]
如果你是按照tutorial里的vagrant 方式，很有可能一些环境，依赖没有安装完成，GFW导致我也没有办法按照tutorial里的user-bootstrap.sh 完成下载，编译，安装。

**Comment by daniel0720** [comment]
为什么我安装后没有p4这个用户啊？只有vagrant这个用户，需要我自己新建一个p4用户吗

**Comment by jnfoster** [comment]
Closing as it seems this issue has been diagnosed and perhaps solved.
