### ISSUE TITLE
Basic tutorial fails to run in 2018-06-01 VM

### ISSUE THREAD

**Issue by stevenkaras** [p4lang/tutorials#219]
When using the [VM][p4-vm] linked from the [2018-06-01 Developer Day][p4-dev-day], I get a hard failure when running the basic exercise without any modification:

```
p4@p4 [tutorials]/exercises/basic (master) $ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
basic.p4(81): warning: Unused action parameter dstAddr
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): warning: Unused action parameter port
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
Switch port mapping:
s1:  1:h1	2:s2	3:s3	
s2:  1:h2	2:s1	3:s3	
s3:  1:h3	2:s1	3:s2	
P4 switch s1 did not start correctly.
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1
```

It turns out I had set up a shared folder and blindly cloned this repository onto my host, meaning that I was not running the same code that is included in the VM (commit 37021092 included in the VM, whereas I had cloned 41873db5).

[p4-dev-day]: https://p4.org/events/2018-06-06-p4-developer-day/
[p4-vm]: https://drive.google.com/uc?id=1f22-DYlUV33DsR88_MeMb4s7-1NX_ams&export=download

**Comment by jafingerhut** [comment]
I am confused -- you have diagnosed the problem to using two different versions of the tutorials repository on the same machine, true?

If so, is there something you are hoping that will change in this repository's contents as a result of the problem you experienced?

**Comment by jafingerhut** [comment]
So are you hoping someone will add documentation to this repository that recommends _not_ doing that, because of the problems it can cause?

In other words: If you have a solution for your problem, what is the purpose of creating this issue?

**Comment by stevenkaras** [comment]
It may be worth adding a note such as this to the README: "NOTE: This repository is only compatible with VMs generated from the same revision. Backwards or forwards compatibility is not guaranteed."

To be honest, my hope here is more that by opening the issue with the exact error message inside, it will get indexed by google and anyone else who steps on that particular landmine can quickly and easily understand that they should use the exact same revision as included in the VM. Consider the issue closed.
