### ISSUE TITLE
protobuf issues with v3.2.0

### ISSUE THREAD

**Issue by kabaka0** [p4lang/tutorials#221]
Had issues manually running the bootstrap scripts, related to the installation of protoc v3.2.0. I was not able to complete the PI make, getting errors related to importing protobuf types, such as ...
Import "google/protobuf/any.proto". It appears that the 3.2.0 branch does not copy all the type header files during installation, causing the error. v3.6.0 works just fine, see https://github.com/tensorflow/tensorflow/issues/13765#issuecomment-451371685 for similar issue and solution.

**Comment by antoninbas** [comment]
I believe @jafingerhut has a script which can install all the dependencies for multiple Linux (or at least multiple Ubuntu) versions: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh
Maybe you can look in there for the appropriate steps to install Protobuf & gRPC. I believe that any.proto was always correctly installed in my case.

**Comment by kabaka0** [comment]
Thanks, I'll test this on a clean Ubuntu 16 install.
