### ISSUE TITLE
user in bootstrap scripts

### ISSUE THREAD

**Issue by jnfoster** [p4lang/tutorials#224]
Currently the `*-bootstrap.sh` scripts assume that `/home/vagrant/` exists. This creates problems for people trying to install the software directly on an Ubuntu VM. We should generalize the scripts so they are more broadly applicable.

**Comment by davidcawork** [comment]
I have had to modify them slightly(It would be a good idea to do a pullrequest of it 😄), I use the connection directory **~** instead of **/home/vagrant/**

**Comment by jafingerhut** [comment]
Please see the comment of 2024-Jul-07 on PR #261 for why I am closing this issue.
