### ISSUE TITLE
Tutorial vagrant up issue

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#225]
On my PC, I have two user accounts one as an admin and one a normal account. I initially tried to "vagrant up" on the main account with all the admin privileges but it didn't work. I tried on the normal account and everything worked fine but I had an issue with Wireshark since it did not have admin privileges. Can anyone please help me with this issue? Details of the 
![screenshot 809](https://user-images.githubusercontent.com/44960997/52543194-f48d2a00-2dea-11e9-8d8b-1d79bcaae1ea.png)
system: Windows 8.1, Vagrant 2.2.3, Virtual box 6.0.4. Thank you.

**Comment by jnfoster** [comment]
This looks like a VirtualBox issue...

**Comment by jnfoster** [comment]
From the error message, it looks like something went wrong during the VirtualBox import process. Maybe try to delete the virtual machine and try again from a fresh start.

**Comment by Juniortheone** [comment]
Thank you @jnfoster
