### ISSUE TITLE
Question about bytes representation of packet at xterm

### ISSUE THREAD

**Issue by stdoo** [p4lang/tutorials#23]
Hi, I want to know how to print the byte representation of the packet at xterm. I can read that through the _pcap_ file, just like this:  00 00 00 00 **00 00 00 00** 68 65 6c 6c 6f     ........hello. I try to read middle bytes(bold) by doing this in the receive.py:
pkt = str(pkt)       // _pkt is the packet from network_   
number = struct.unpack("<L", pkt[4:8])[0]     //  _get the middle bytes_ 
print('number: %s' %number)

I can get a really large integer, like **10063296**, but when I check the _pcap_ file, I see this:
00 00 00 00 **00 00 00 06** 68 65 6c 6c 6f     ........hello. 
So I don't get the same number as in _pcap_ file, can't figure out why.

**Comment by antoninbas** [comment]
This is hardly a P4 question...
The result is expected as 10063296 is nothing more than 00000006 in host-byte order instead of network-byte order.
To print the string as a sequence of bytes, you can use:
`":".join("{:02x}".format(ord(c)) for c in pkt[4:8])`
