### ISSUE TITLE
Unable to run the P4 basic program on VM

### ISSUE THREAD

**Issue by nniranjhana** [p4lang/tutorials#232]
I tried following the tutorial's README by first `sudo apt-get install vagrant virtualbox`
and then when I clone tutorials repo, `cd vm` and `vagrant up`, I get this error at the end (nevertheless it still runs):

**Error log on console:**
 ```
       p4-tutorial: Guest Additions Version: 6.0.4 r128413
       p4-tutorial: VirtualBox Version: 5.1
==> p4-tutorial: Setting hostname...
==> p4-tutorial: Running provisioner: file...
==> p4-tutorial: Running provisioner: file...
==> p4-tutorial: Running provisioner: file...
==> p4-tutorial: Running provisioner: shell...
       p4-tutorial: Running: /tmp/vagrant-shell20190215-2852-ytb3db.sh
==> p4-tutorial: mesg: ttyname failed: Inappropriate ioctl for device
==> p4-tutorial: + DEBIAN_FRONTEND=noninteractive
==> p4-tutorial: + sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
==> p4-tutorial: Cannot add PPA: 'ppa:~webupd8team/ubuntu/sublime-text-3'.
==> p4-tutorial: ERROR: '~webupd8team' user or team does not exist.

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Now, when the Ubuntu system is up on the VM, it does not have the "p4" login. Instead, it has a login for "vagrant" and by random chance, I found the password is also set to "vagrant" and was able to login.

I did `sudo shutdown -r now` and when it was up again, I cloned repo and tried to `make run` from inside tutorials/exercises/basic but found out some of the dependencies have been installed and I am unable to run it. For example, _the error said I don't have the behavioral model installed._

What's going on here? I think I can find the required software pre-installed only via the "p4" login, since the script has to run completely probably to get to install everything, which I cannot see. What do I do?

**System configuration:**
Ubuntu 16.04.5 LTS
Vagrant 2.2.3
VirtualBox 5.1.38

**Comment by jnfoster** [comment]
I think the `apt-add-repository` command failed, which caused the rest of the bootstrap script to fail. Hence, most software was not installed.

I just tried running the same command `apt-add-repository` command on a Ubuntu 16.04 VM, and it worked fine. So I think it's something local about your local setup... 

[This](https://askubuntu.com/questions/971877/cannot-add-ppa-user-or-team-does-not-exist?rq=1) page suggests there might be an issue with your network connection -- e.g., do you know if you are behind a web proxy?

**Comment by jnfoster** [comment]
I'm going to close this for now. It seems like a Vagrant / local environment issue and not actually a problem with the tutorial VM build scripts.

**Comment by nniranjhana** [comment]
@jnfoster I'm not behind a proxy.. but thanks for getting back on this! I was able to resolve it.

So for future users facing this issue, you can try this:

Run the last command where it previously failed, once again:

`sudo add-apt-repository -y ppa:webupd8team/sublime-text-3`

And this time, it did it. I did not do change anything else in between, so I have no idea why it worked now but not when the script tried to do it. And then, I ran

`vagrant provision`

and the script continued where it left off, this time installing everything to completion and giving me the P4 login as well! Yippie!

**Comment by jnfoster** [comment]
Glad to hear it!
