### ISSUE TITLE
Invalid topo name

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#235]
I'm trying something out so I created a network with only switches but I'm getting the error message "Invalid topo name". Can anyone help?

**Comment by jafingerhut** [comment]
I do not know for certain whether anyone will be able to help, but if you publish the changes you made and/or any files you added, and the command you ran and the results you got, it is more likely someone could attempt to reproduce the circumstances, or recognize what is going wrong.

**Comment by Juniortheone** [comment]
Thanks, @jafingerhut but I figured out why.
