### ISSUE TITLE
Make run issue

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#237]
I have been using the P4 tutorial just fine but now I run the file and this is the error I'm getting.Any help?
![screenshot from 2019-02-25 13-18-31](https://user-images.githubusercontent.com/44960997/53385203-8a8d8c80-3975-11e9-807c-519cb22806d2.png)

**Comment by jnfoster** [comment]
The error message explains it: you need to install the `psutil` Python library.

**Comment by antoninbas** [comment]
The scripts used to set up the Vagrant image should probably take care of installing this package though.
So I submitted https://github.com/p4lang/tutorials/pull/240
