### ISSUE TITLE
Calculator tutorial missing

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/tutorials#245]
The link to the Calculator tutorial on https://github.com/p4lang/tutorials results in a 404 Not Found error. Was it silently removed per #102? I'd restore it, it's intriguing.

**Comment by jnfoster** [comment]
We're not currently using the calculator so it's not in the current master branch. It can be found in the pre-2018 D2 release, available [here](https://github.com/p4lang/tutorials/releases).

I'll fix the README.md
