### ISSUE TITLE
ecn redirecting output with ./receive.py > h2.log doesn't work

### ISSUE THREAD

**Issue by adamM11** [p4lang/tutorials#247]
Hi everyone, 
My english will maybe be bad and I'm a beginner in P4, I'm also sorry if there is some stupid saying or bad english :/ 
So my problem is the following : 
When I use my make run command in the ecn folder and write "./receive.py > h2.log" there is no "sniffing on h2-etho" in my xterm h2, I only get the WARNING message ("no route found for ipv6 destination..."). I also can't print my tos values in the separate log and when I do all steps in my xterms, there is no tos values printed. 
In plus, I get a warning message in my h11 node "did not receive ack of last datagram after 10 tries" and another bad feedback from my h22 node : "read failed: Connection refused".
How can I fix those problems ? 

Thank you for your attention,
Cordially

**Comment by jnfoster** [comment]
Closing as this issue is quite old and the current solution is functional.
