### ISSUE TITLE
Setting register in control plane (json files)

### ISSUE THREAD

**Issue by henriklb** [p4lang/tutorials#256]
I'm currently using the P4 tutorial environment for my P4 code. Is it possible to set a register value (the way it is for tables) in the control plane json-files?

If that's the case, what's the proper json formatting/syntax?

**Comment by antoninbas** [comment]
P4Runtime register support is currently not implemented on bmv2: https://github.com/p4lang/PI/issues/376

**Comment by henriklb** [comment]
Ok. Since it is currently not possible to do this via the json files/P4Runtime on bmv2. 
Any suggestion on alternatives ways I could set the register value from the control plane within the P4 tutorial VM?

**Comment by antoninbas** [comment]
Yes you can use the simple_switch_CLI if your bmv2 target was built with Thrift support.

**Comment by antoninbas** [comment]
Asked and answered on slack as well

**Comment by Akshataavk** [comment]
Hi @antoninbas I'm new to P4 and using the P4 tutorial environment for my P4 code. How exactly can I use simple_switch CLI to set register values? 
I'm using a register to decide where the packet is forwarded based on register values (load balancing with weighted round robin, and have weights stored in registers) for some context. I'm very overwhelmed by the P4 specification document and haven't found any answers on how register values can be initialized.

**Comment by jafingerhut** [comment]
The example program and README.md file in this directory show examples of using simple_switch_CLI to read/write registers in a P4 program: https://github.com/jafingerhut/p4-guide/tree/master/demo6

**Comment by Akshataavk** [comment]
Thank you @jafingerhut !
