### ISSUE TITLE
'ecn' No connectivity between hosts connected to the same switch

### ISSUE THREAD

**Issue by harshgondaliya** [p4lang/tutorials#257]
It has been my observation that whenever we are connecting two hosts to the same switch then the ping is not working among them. For example for the topology used in the ecn exercise these are the results of using pingall in Mininet CLI:
```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 h3 X h22 
h2 -> h1 h3 h11 X 
h3 -> h1 h2 h11 h22 
h11 -> X h2 h3 h22 
h22 -> h1 X h3 h11 
*** Results: 20% dropped (16/20 received)
```
The table entries in all the switches as per `s1-runtime.json` and `s2-runtime.json` are perfect. If match by /32 is done then ping should work between h1 & h11 and for h2 &h22. But still, this issue is arising. Any idea why this is occurring?

**Comment by jnfoster** [comment]
The `ecn.p4` program only forwards IPv4 packets. In particular, it doesn't handle ARP. If you manually populate the ARP tables on those hosts, pings will work.

For example, in Mininet:
`
> h1 arp -s h11 00:00:00:00:01:0b
> h11 arp -s h1 00:00:00:00:01:01
`

**Comment by harshgondaliya** [comment]
Yes this works. Thanks.
