### ISSUE TITLE
Seeing Help for Parse TCP Option 

### ISSUE THREAD

**Issue by qq995002966** [p4lang/tutorials#26]
For some reason I want to parse TCP Options using p4 , but it seems that there is no such a helpful code to reference in this repository and P4 spc.
Could you please give me some advise how to parse TCP Options using p4?

Thanks. John.

**Comment by antoninbas** [comment]
TCP options are very similar to IPv4 options AFAIK. So I invite you to take a look at the TLV parsing example in this repo: https://github.com/p4lang/tutorials/tree/master/examples/TLV_parsing
Please be sure to read the README for that example, as there is one important caveat.

**Comment by qq995002966** [comment]
Really sorry about the other tow duplicate posts,I thought there were different people maintain different repositories . 

There are a some details about the P4 source code confusing me 

1.  `(line 96) header ipv4_option_NOP_t ipv4_option_NOP[3];` 
why the array count is `3` ? can other number work ?

2. ` (line 137、144)   extract(ipv4_option_EOL[next]);`
what does `next` mean?

Appreciate your help , thank you .
John.

**Comment by antoninbas** [comment]
1. You have to pick a size for the array / stack, which will be the maximum number of NOP options in any given packet. You can choose any number that works for you, keeping in mind that in real hardware a higher number would mean more resources utilized.

2. The answer should be in the P4_14 spec.
