### ISSUE TITLE
SSH bootstrap error

### ISSUE THREAD

**Issue by prince901** [p4lang/tutorials#260]
I tried running the P4 tutorial but there is a SSH error. I checked online and the apparent solution was to make changes in the `sudoers` file but the installation was never complete so it's impossible. I've tried uninstalling Vagrant and re-installing. I made a new Windows install but it's still the same. Here is the error:
`  p4-tutorial: + echo p4:p4
    p4-tutorial: + echo 'p4 ALL=(ALL) NOPASSWD:ALL'
    p4-tutorial: + chmod 440 /etc/sudoers.d/99_p4
    p4-tutorial: + usermod -aG vboxsf p4
    p4-tutorial: + cd /usr/share/lubuntu/wallpapers/
    p4-tutorial: + cp /root/p4-logo.png .
    p4-tutorial: cp:
    p4-tutorial: cannot stat '/root/p4-logo.png'
    p4-tutorial: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by prince901** [comment]
Any help please? I've read the log but I have no idea as to what's wrong.

**Comment by jnfoster** [comment]
This sounds like an error with vagrant or your local environment but it's hard to tell without more information.

Perhaps you share some details like:
* The operating system you are running and its version
* The version of Vagrant you have installed
* The precise sequence of commands you ran
* The complete log produced

Alternatively, if you are not familiar with building VM images using vagrant, it might be easier to use the pre-packaged OVA image from the latest P4 tutorial, which can be imported into VirtualBox or VMware...

**Comment by prince901** [comment]
Thank you Sir @jnfoster. I downloaded and installed the OVA Image.
