### ISSUE TITLE
Question: Is it correct to talk about switch?

### ISSUE THREAD

**Issue by davidcawork** [p4lang/tutorials#264]
Hi all,

I wonder, after doing several exercises, the terminology of calling switch to nodes in the network that handle and operate with layer 3. I think it would be more correct to talk about a router.

Best,

**Comment by antoninbas** [comment]
"Programmable switch" is the widely accepted terminology in the p4.org, when referring to a multi-port packet processing device whose data plane behavior can be defined by a P4 program.

If your P4 program implements traditional routing functions, then it is probably accurate to refer to the programmable switch running your P4 program as "router". It is likely that several of the tutorial exercises use such P4 programs. But is also very easy to write a pure L2 switch in P4. You will also find numerous examples online of P4 programs implementing in-network compute functions (with or without routing functions), in which case it would be vastly inaccurate to just refer to them as routers. The tutorial exercises will usually use "switch" when referring to bmv2 instances, as we want to emphasize that these can run *any* P4 program (as long as it is written for a supported P4 architecture). If we use the switch as a plain router, it is just to illustrate a specific use case (not a very interesting one when you have access to a fully programmable device...).

**Comment by davidcawork** [comment]
Thank you very much for your clarification, I understand what you want to say! :smile: 


Have a good day! Closing Issue
