### ISSUE TITLE
Run basic: No module named protobuf.internal

### ISSUE THREAD

**Issue by ILoveStudying** [p4lang/tutorials#265]
I make all components right. 
But when I get into the tutorials/exercise/basic folder, I met error: No module named protobuf.internal.
 I tried many ways but no use. I really need some help!!!

![image](https://user-images.githubusercontent.com/32291191/60320515-87022480-99ac-11e9-82ab-1feca5025d0a.png)

**Comment by jnfoster** [comment]
I believe you likely have the wrong version of protobuf. Consider using the pre-packaged [virtual machine](https://drive.google.com/uc?id=1lYF4NgFkYoRqtskdGTMxy3sXUV0jkMxo&export=download)?

**Comment by Polly2014** [comment]
I think you can try in two ways:
- Check the protobuf version whether it is match with the sh script in tutorial
- Check the tutorial's branch, I met the start problem at first, then change to use the p4d-2018-spring, it runs success
Hope it could help you

**Comment by ILoveStudying** [comment]
Thanks a lot. That's it!

**Comment by poohdang** [comment]
This issue is indeed caused by **tutorials** folder.
Beside checkout  to older branch, the following command can help if your're desperate to taste the latest experiments:
```
$ cd  /usr/local/lib/python2.7/dist-packages/
$ cp -rf protobf-xxx-py2.7.egg/google/*   google/
```
