### ISSUE TITLE
How to configure switches(bmv2) when build custom network topology?

### ISSUE THREAD

**Issue by Polly2014** [p4lang/tutorials#266]
I'm a starter for P4 from China (with little paper or document about P4), here is what I want to do:
- build a custom network topology with bmv2 ( eg: 8 bmv2 switch, linked each other, also each switch with a host connect)
- each host can ping to another host via switch(es)
Then the problems as bellow:
- I know how to write a topo file (custom_topo.json), but how to configure each switch? using the CLI or static json file ( like s-xx.json)?
- If using the json file, need I write 8 file one by one?
- If using CLI to automic configure, what should I do?
Thanks for guide me some Idea

**Comment by antoninbas** [comment]
For basic usage (simple table entries only), you can use JSON files (one per switch instance) just like in the "basic" tutorial exercise: https://github.com/p4lang/tutorials/tree/master/exercises/basic
For more advanced things, you can look into using p4runtime-shell (https://github.com/p4lang/p4runtime-shell), which lets you connect to each switch and generate arbitrary P4Runtime messages.

**Comment by Polly2014** [comment]
> For basic usage (simple table entries only), you can use JSON files (one per switch instance) just like in the "basic" tutorial exercise: https://github.com/p4lang/tutorials/tree/master/exercises/basic
> For more advanced things, you can look into using p4runtime-shell (https://github.com/p4lang/p4runtime-shell), which lets you connect to each switch and generate arbitrary P4Runtime messages.

Thanks for your advice, I've continue learned several days.  Now I know the two ways you mentioned:
- one is using thrift-based bvm2 CLI (one per switch instance)
- another is using gRPC-based P4 Runtime CLI( as you say p4runtime-shell)

Now, the question becomes as bellow:
- Either using thrift-based or gRPC-based method, when the bmv2 switch's number is large, how could I populate the flow entry to each switch, Only one-by-one ? Hope you have some brighting idea, thanks again^_^

**Comment by antoninbas** [comment]
When you start building more ambitious topologies, it is not a bad idea to start writing your own P4Runtime "controllers" (can be just a simple script) in the language of your choice, instead of relying on the P4Runtime libraries / wrappers included in the tutorials repository.

I just updated p4runtime-shell with instructions on how it can be used to write custom scripts which instantiate a P4Runtime client and push forwarding rules to the switch: https://github.com/p4lang/p4runtime-shell#using-p4runtime-shell-in-scripts. If all your switches need to be configured with the exact same rules, you can write a single Python script and run it multiple times with the appropriate gRPC socket address and the appropriate device id. If your switches need to be configured differently, you can write / generate one Python script for each.

**Comment by Polly2014** [comment]
> When you start building more ambitious topologies, it is not a bad idea to start writing your own P4Runtime "controllers" (can be just a simple script) in the language of your choice, instead of relying on the P4Runtime libraries / wrappers included in the tutorials repository.
> 
> I just updated p4runtime-shell with instructions on how it can be used to write custom scripts which instantiate a P4Runtime client and push forwarding rules to the switch: https://github.com/p4lang/p4runtime-shell#using-p4runtime-shell-in-scripts. If all your switches need to be configured with the exact same rules, you can write a single Python script and run it multiple times with the appropriate gRPC socket address and the appropriate device id. If your switches need to be configured differently, you can write / generate one Python script for each.

Wow, it's very **Cool** for hearing that, I will try ```p4runtime-shell```, hope one day I can join you to make some contributions in P4. Thanks a lot

**Comment by Polly2014** [comment]
> When you start building more ambitious topologies, it is not a bad idea to start writing your own P4Runtime "controllers" (can be just a simple script) in the language of your choice, instead of relying on the P4Runtime libraries / wrappers included in the tutorials repository.
> 
> I just updated p4runtime-shell with instructions on how it can be used to write custom scripts which instantiate a P4Runtime client and push forwarding rules to the switch: https://github.com/p4lang/p4runtime-shell#using-p4runtime-shell-in-scripts. If all your switches need to be configured with the exact same rules, you can write a single Python script and run it multiple times with the appropriate gRPC socket address and the appropriate device id. If your switches need to be configured differently, you can write / generate one Python script for each.

One More Question in using-p4runtime-shell-in-scripts:
- If I want to use this script, should I fist installed bmv2、p4c、PI in the system before run the script
- If bmv2、p4c、PI installed also by docker, how to set params when run the p4runtime-shell
- If bmv2、p4c、PI installed directly in system( like tutorials ), how to set params when run the p4runtime-shell
- Can I run p4runtime-shell directly without docker?

**Comment by antoninbas** [comment]
The compiler (p4c) is required to generate the bmv2 JSON (input to bmv2 switch) and the P4Info message (for P4Runtime) from the P4 program.
The bmv2 switch binary is called simple_switch_grpc. Instructions on how to build it can be found here: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/README.md. You can run simple_switch_grpc natively or in a docker (example Dockerfile: https://github.com/p4lang/behavioral-model/blob/master/Dockerfile.grpc), it's up to you.

simple_switch_grpc can be run like this:
```
simple_switch_grpc [--log-console] --no-p4 --grpc-server-addr <server IP>:<server port> --device-id <id> --cpu-port <port> -i <port>@<interface> -i <port>@<interface> ...
```
It's probably easier to use p4app to generate a Mininet topology of hosts / simple_switch_grpc switches. You can look for inspiration in the p4app & tutorials repo. I don't have exact instructions, I haven't used it in a while.

For p4runtime-shell, you can run it natively if you want but it's massively easier to just run the Docker image directly:
```
[sudo] ./p4runtime-sh-docker --grpc-addr <server IP>:<server port> \
  --device-id <id> --election-id 0,1 \
  --config <path to p4info text file>,<path to bmv2 json>
```

The `--grpc-addr` and `--device-id` command line arguments to `p4runtime-sh-docker` must match the `--grpc-server-addr` and `--device-id` command line arguments to the corresponding `simple_switch_grpc` instance.

The P4Info text file and bmv2 JSON are obtained by running the p4c compiler. Something like this:
```
p4c -b bmv2 -a v1model --p4runtime-files p4info.pb.txt <path to P4 program>
```

I personally recommend that you do the following first:
 * compile P4 program with p4c directly
 * start `simple_switch_grpc`
 * connect to `simple_switch_grpc` with p4runtime-shell and try adding some flows

After that, you should have a better understanding of what's going on and you can start creating some network topology using Mininet / p4app. Don't hesitate to ask for help on the p4.org slack channel.

**Comment by Polly2014** [comment]
> The compiler (p4c) is required to generate the bmv2 JSON (input to bmv2 switch) and the P4Info message (for P4Runtime) from the P4 program.
> The bmv2 switch binary is called simple_switch_grpc. Instructions on how to build it can be found here: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/README.md. You can run simple_switch_grpc natively or in a docker (example Dockerfile: https://github.com/p4lang/behavioral-model/blob/master/Dockerfile.grpc), it's up to you.
> 
> simple_switch_grpc can be run like this:
> 
> ```
> simple_switch_grpc [--log-console] --no-p4 --grpc-server-addr <server IP>:<server port> --device-id <id> --cpu-port <port> -i <port>@<interface> -i <port>@<interface> ...
> ```
> 
> It's probably easier to use p4app to generate a Mininet topology of hosts / simple_switch_grpc switches. You can look for inspiration in the p4app & tutorials repo. I don't have exact instructions, I haven't used it in a while.
> 
> For p4runtime-shell, you can run it natively if you want but it's massively easier to just run the Docker image directly:
> 
> ```
> [sudo] ./p4runtime-sh-docker --grpc-addr <server IP>:<server port> \
>   --device-id <id> --election-id 0,1 \
>   --config <path to p4info text file>,<path to bmv2 json>
> ```
> 
> The `--grpc-addr` and `--device-id` command line arguments to `p4runtime-sh-docker` must match the `--grpc-server-addr` and `--device-id` command line arguments to the corresponding `simple_switch_grpc` instance.
> 
> The P4Info text file and bmv2 JSON are obtained by running the p4c compiler. Something like this:
> 
> ```
> p4c -b bmv2 -a v1model --p4runtime-files p4info.pb.txt <path to P4 program>
> ```
> 
> I personally recommend that you do the following first:
> 
> * compile P4 program with p4c directly
> * start `simple_switch_grpc`
> * connect to `simple_switch_grpc` with p4runtime-shell and try adding some flows
> 
> After that, you should have a better understanding of what's going on and you can start creating some network topology using Mininet / p4app. Don't hesitate to ask for help on the p4.org slack channel.

Very thanks for you , I will try it ^_^
