### ISSUE TITLE
Basic make run error: 'build/basic.json' failed

### ISSUE THREAD

**Issue by ILoveStudying** [p4lang/tutorials#267]
My Verision:
BMV2_COMMIT="7e25eeb19d01eee1a8e982dc7ee90ee438c10a05"
PI_COMMIT="219b3d67299ec09b49f433d7341049256ab5f512"
P4C_COMMIT="48a57a6ae4f96961b74bd13f6bdeac5add7bb815"
PROTOBUF_COMMIT="v3.2.0"
GRPC_COMMIT="v1.3.2"

But when I make run ./tutorials/exercises/basic:
![image](https://user-images.githubusercontent.com/32291191/60502645-cc965880-9cf0-11e9-94d4-b2d23294a1a8.png)

Where is wrong??I can't find the reason

**Comment by antoninbas** [comment]
Recent p4c compiler versions use `--p4runtime-files`, but older versions, like the one you are using, do not accept this flag. If you want to keep using the same p4c version, you can edit the Makefile and replace:
```
P4C_ARGS = --p4runtime-files $(basename $@).p4.p4info.txt
```
with
```
P4C_ARGS = --p4runtime-file $(basename $@).p4info --p4runtime-format text
```
BTW, you can see that `--p4runtime-files` doesn't show up in the compiler help message.
