### ISSUE TITLE
I install the tutorials,but I can find the Terminal

### ISSUE THREAD

**Issue by mocaibupt** [p4lang/tutorials#268]
As the title, I install the virtual machine as cd to vm folder,and run 'vagrant up',Then there are a machine,but there are"
 fatal: destination path 'mininet' already exists and is not an empty directory.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong." in the MINGW64 screen.
When I use p4 as password login in the virtual machine,I can entry the desktop.But there are nothing in my screen,no Menu Bar on Left of the desktop as normal Ubuntu system.That's OK , 
the most issue is I can't open the desktop by input command Ctrl+Alt+T.And it is no reaction when I click right of mouse in the desktop of virtual machine.but I can input p4 as password in the page of login.
My vagrant version is 2.2.4,my virtual box version is 6.0.8,My computer system is Win7

**Comment by pszabop** [comment]
Experiencing the same

There's probably some bitrot.  

Waiting for the vagrant install to finish takes 5-10 minutes.  It finished on the same error

I had to reboot several times just to get P4 login screen.

If you right-click you can bring up a terminal and from there should be able to do work.

I note I had to rerun the installation scripts as they don't appear to finish from Vagrant:

    cd tutorial/vm
    sudo ./root-bootstrap.sh
    sudo ./user-bootstrap.sh

After that all runs (takes a long time on a 2018 Mac, should try parallel Make), the tutorials seem to run.

**Comment by mocaibupt** [comment]
> Experiencing the same
> 
> There's probably some bitrot.
> 
> Waiting for the vagrant install to finish takes 5-10 minutes. It finished on the same error
> 
> I had to reboot several times just to get P4 login screen.
> 
> If you right-click you can bring up a terminal and from there should be able to do work.
> 
> I note I had to rerun the installation scripts as they don't appear to finish from Vagrant:
> 
> ```
> cd tutorial/vm
> sudo ./root-bootstrap.sh
> sudo ./user-bootstrap.sh
> ```
> 
> After that all runs (takes a long time on a 2018 Mac, should try parallel Make), the tutorials seem to run.

Thank you. I restart the machine and I can use the Terminal.But Now I find other issue.It is：
《fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Connection timed out》when I command sudo ./user-bootstrap.sh
I think it's Chinese wall caused.but when I through the wall to want  do the same operate, The issue appear again.Even I can not bing the address, I don't know why.Can you link to the page: https://boringssl.googlesource.com/boringssl/?
Thank you very much

**Comment by jnfoster** [comment]
Please try the pre-built VM image at: http://stanford.edu/~sibanez/docs/
