### ISSUE TITLE
Updating existing rules using P4Runtime results in GRPC error

### ISSUE THREAD

**Issue by burakatalay** [p4lang/tutorials#269]
Hello everyone,

I am trying to update existing rules using P4Runtime, I am using the WriteTableEntry() function in utils/p4runtime_lib/switch.py as my basis. I added the following to the class definiton in switch.py:
`self.requests = []`
and I updated the WriteTableEntry() function to the following:
```python
def WriteTableEntry(self, table_entry, dry_run=False):
        request = p4runtime_pb2.WriteRequest()
        request.device_id = self.device_id
        request.election_id.low = 1
        update = request.updates.add()
        if table_entry.is_default_action:
            update.type = p4runtime_pb2.Update.MODIFY
        else:
            update.type = p4runtime_pb2.Update.INSERT
        update.entity.table_entry.CopyFrom(table_entry)
        if dry_run:
            print "P4Runtime Write:", request
        else:
            self.client_stub.Write(request)
	    self.requests.append(request)  #Added by me
```
This way I am able to keep track of the table entries. Now I added the following function to delete all existing table entries in the file  utils/p4runtime_lib/switch.py:
```python
def DeleteTableEntry(self, dry_run=False):
        print "DeleteTableEntry() is called, device_id=", self.device_id
        updates = []
        for req in reversed(self.requests):
          for update in reversed(req.updates):
            if update.type == p4runtime_pb2.Update.INSERT:
              updates.append(update)
        new_req = p4runtime_pb2.WriteRequest()
        new_req.device_id = self.device_id
	new_req.election_id.low = 1
        for update in updates:
          update.type = p4runtime_pb2.Update.DELETE
          new_req.updates.add().CopyFrom(update)
        if dry_run:
            print "P4 Runtime Write:", new_req
        else:
            self.client_stub.Write(new_req)
```
And in my controller, I have the following function:
```python
def clearTunnelRules(p4info_helper, sw):
    print "Clear rules on %s" % sw.name
    sw.DeleteTableEntry()
```
With these additions, I can delete all existing rules on a switch. What I am trying to achieve is to update an existing rule, I added the following function under utils/p4runtime_lib/switch.py:
```python
def UpdateTableEntry(self, table_entry, old_table_entry, dry_run=False):
        print "UpdateTableEntry() is called, device_id=", self.device_id
	print "UpdateTableEntry() is called, table id=", table_entry.table_id
	print "UpdateTableEntry() is called, old_table id=", old_table_entry.table_id
        updates = []
        for req in reversed(self.requests):
          for update in reversed(req.updates):
            if update.type == p4runtime_pb2.Update.INSERT:
              updates.append(update)
        new_req = p4runtime_pb2.WriteRequest()
        new_req.device_id = self.device_id
	new_req.election_id.low = 1
        for update in updates:
	  if update.entity.table_entry == old_table_entry:
            update.type = p4runtime_pb2.Update.MODIFY
	    update.entity.table_entry.CopyFrom(table_entry)
            new_req.updates.add().CopyFrom(update)

        if dry_run:
            print "P4 Runtime Write:", new_req
        else:
            self.client_stub.Write(new_req)
	    self.requests.append(new_req)
```
And in my controller I have the following function:
```python
def updateTunnelRules(p4info_helper, ingress_sw, egress_sw,
                     dst_eth_addr, dst_ip_addr, port, new_egress_sw, new_dst_eth_addr, new_dst_ip_addr, new_port):
    
    old_table_entry = p4info_helper.buildTableEntry(
        table_name="MyIngress.ipv4_lpm",
        match_fields={
            "hdr.ipv4.dstAddr": (dst_ip_addr, 32)
        },
        action_name="MyIngress.ipv4_forward",
        action_params={
            "dstAddr": dst_eth_addr,
            "port": port
        })

    table_entry = p4info_helper.buildTableEntry(
        table_name="MyIngress.ipv4_lpm",
        match_fields={
            "hdr.ipv4.dstAddr": (new_dst_ip_addr, 32)
        },
        action_name="MyIngress.ipv4_forward",
        action_params={
            "dstAddr": new_dst_eth_addr,
            "port": new_port
        })
    ingress_sw.UpdateTableEntry(table_entry, old_table_entry)
    print "Installed forwarding rule on %s" % ingress_sw.name
```
What I hoped to achieve was to compare the table entries and update rules based on that, however I get the following error when I run my controller:

> gRPC Error: Connect Failed (UNAVAILABLE)

Can you help me with this issue by giving me some feedback about my approach or the mistakes I made?

Thanks and best regards

**Comment by antoninbas** [comment]
That seems to indicate that the P4Runtime server is not running (or no longer running). Did you check with netstat whether the port was still open (50051)?

You don't provide much information about when exactly the error is happening? Are you able to install the original rule, but you get the error when you try to modify it?

The most likely explanation (assuming you were able to run the tutorial exercise correctly before you made your changes) is that something you wrote is causing the P4Runtime server or the bmv2 switch to crash. The easiest way to debug this is to start bmv2 simple_switch_grpc yourself (run the binary directly, do not use the Makefiles included in the tutorials) and see if it starts properly and crashes after you start your controller. Use `--log-console` as it may provide some insight.

BTW, I don't think `if update.entity.table_entry == old_table_entry` will do what you want. AFAIK, you cannot compare Protobuf messages like this.
