### ISSUE TITLE
SIGCOMM_2016: P4 switch s1 did not start correctly

### ISSUE THREAD

**Issue by darksharkz** [p4lang/tutorials#27]
Hello,

I have a problem with the heavy_hitter example. When I run ./run_demo.sh the switch s1 can not be setup correctly with the following message:

`*** Starting 1 switches
s1 Starting P4 switch s1.
/home/simon/Documents/p4/tutorials/../bmv2/targets/simple_switch/simple_switch -i 1@s1-eth1 -i 2@s1-eth2 -i 3@s1-eth3 --pcap --thrift-port 22222 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 heavy_hitter.json
P4 switch s1 did not start correctly.`

Everything should be setup right, because it already worked last week with the 2015 tutorial "source routing"

Thanks for your help.

**Comment by antoninbas** [comment]
I was unable to reproduce this, ti works fine for me.
I would recommend trying to run the following command and see if the switch starts correctly:
```
sudo /home/simon/Documents/p4/tutorials/../bmv2/targets/simple_switch/simple_switch --pcap --thrift-port 22222 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 heavy_hitter.json
```
If it fails, you may have a useful error message.

**Comment by darksharkz** [comment]
Now I write my code to solve the exercise and run the demo again. This time it worked fine. Dont know what the problem was, but it seems to be gone.
