### ISSUE TITLE
Issue in install gRPC when sudo ./user-bootstrap.sh

### ISSUE THREAD

**Issue by mocaibupt** [p4lang/tutorials#270]
The newest .gitmodules file of gRPC in github show:
      [submodule "third_party/boringssl-with-bazel"]
	    path = third_party/boringssl-with-bazel
	    url = https://github.com/google/boringssl.git
but after "git checkout ${GRPC_COMMIT}",the .gitmodules file of gRPC show:
     [submodule "third_party/boringssl-with-bazel"]
	   path = third_party/boringssl-with-bazel
	   url = https://boringssl.googlesource.com/boringssl

Then I am in China,and I can't open this url,even use command ping this url have not response.At first, I think it's Chinese wall cause it,but when I use the vps to through the wall,I can't use ping command to link this url also.I try to change the .gitmodules file to change the url from "https://boringssl.googlesource.com/boringssl" to "https://github.com/google/boringssl.git" .but when I use the command of 
'git submodule update --init --recursive".The destination address also are "https://boringssl.googlesource.com/boringssl".

I want to know:how can I to complete the virtual machine?

**Comment by jnfoster** [comment]
Will it work to use the pre-packaged VM at http://stanford.edu/~sibanez/docs/ ?

**Comment by chenIshi** [comment]
according to the [solution](https://github.com/grpc/grpc/issues/12377#issuecomment-353711211) from [grpc issue #12377](https://github.com/grpc/grpc/issues/12377)， you still need to run `git submodule sync`
