### ISSUE TITLE
How to define Infinite-precision integers?

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/tutorials#274]
I want to implement division by P4. I can find that Infinite-precision integers can support division by reading P4_16 Spec.
![image](https://user-images.githubusercontent.com/38399275/62758942-69979e80-bab2-11e9-8234-a5a0407c6d9b.png)
However, when I define an  Infinite-precision integer using **int**, the compiler shows error like this:
![image](https://user-images.githubusercontent.com/38399275/62759142-14a85800-bab3-11e9-8b9e-30a65c0f9c55.png)
It shows that using **_int result_** to define an  Infinite-precision integer is not correct. But I need to use division in P4. How can I define an infinite-precision integer correctly? Thank you!

**Comment by jafingerhut** [comment]
At least partially answered here: https://github.com/p4lang/p4c/issues/2020
