### ISSUE TITLE
stuck with default vagrant login/password

### ISSUE THREAD

**Issue by KevinRiordan** [p4lang/tutorials#283]
I have tried installing dependencies but the vagrant up command still does not work properly

**Comment by jnfoster** [comment]
We are generally a friendly community, and happy to try to help you debug the VM build scripts. But we will need a little bit more information to help... "stuck" and "does not work properly" is a pretty vague description of the issue.

**Comment by KevinRiordan** [comment]
Thank you for not being to harsh, and my apologies for not being more clear. I followed the steps of the README, but am unable to access the tutorials. The Vagrant VM launches and i sign in with vagrant vagrant, and once i am in the vm in the vagrant the directories for the tutorials are not there.
![image](https://user-images.githubusercontent.com/26858835/65048822-c2204e00-d932-11e9-959c-f3fb2129adc1.png)

**Comment by KevinRiordan** [comment]
I tried executing the reboot command but then I am unable to open a terminal window. I tried right clicking but nothing happens (also tried with right-ctrl), and I have tried the keyboard shortcut for the terminal window. If I reset the VM then I can right click on the desktop and open a terminal window but it is missing the relevant files.

**Comment by jnfoster** [comment]
It sounds like something went quite wrong with the virtual machine build process on your machine.

Would it work for you to download a pre-built VM image? For instance, here is the VM we built for the tutorial we presented at SIGCOMM '19: http://stanford.edu/~sibanez/docs/
