### ISSUE TITLE
Assigning MAC and IP addresses

### ISSUE THREAD

**Issue by sanaa50** [p4lang/tutorials#295]
Hi everybody, 
I'm new to P4 and still learning the language. 
I need to know how p4apprunner.py assigns the MAC and IP addresses to hosts and switches? 
I tried to look at the code but really got nothing.
Another question, is it possible to create my own topology (i.e a switch with multiple hosts in the same network, each host connected to different port)?

**Comment by jnfoster** [comment]
The Python scripts set up an emulated environment for the structure described in `topology.json`. For the details, one needs to understand Mininet, Linux network namespaces, etc.
