### ISSUE TITLE
Error grpc._channel.Rendezvous

### ISSUE THREAD

**Issue by guimvmatos** [p4lang/tutorials#297]
[srv6.zip](https://github.com/p4lang/tutorials/files/3774608/srv6.zip)
Hi, i`m trying to implement srv6 routing and after some code changes I found this error..

  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 272, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, )>
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

I put the codes on drive, the link to download is

https://drive.google.com/file/d/1XP8nwAOeMIDtbN7d486vG6fNkvj-GUuU/view?usp=sharing

instructions to reproduce the error:

1 - copy file run_exercise_ipv6.py to /home/p4/tutorials/utils
2 - copy makefile to /home/p4/tutorials/utils
3 - copy directory srv6 to /home/p4/tutorials/exercises
4 - open terminal and navigate to /tutorial/exercises/srv6
5 - execute make command

Someone can help me, please?

I`m tired to try to understand this and get no results

I made some changes on makefile and run_exercise, but this work fine with others implementations. the problem is with srv6.p4, json of switches or topology. 

the _copy files is backup of old implementation. ignore then!

**Comment by guimvmatos** [comment]
someone?

**Comment by jafingerhut** [comment]
Also it would help to know if your system can successfully run any of the other tutorials in /home/p4/tutorials without these errors.

**Comment by guimvmatos** [comment]
hello @jafingerhut 

I am very glad with your help. It's just this code that didn't run in my environment. All others run perfectly.

but I discovered the problem, they had comments on the switch jsons files

again, thankful for you help!

**Comment by guimvmatos** [comment]
Can I close?

**Comment by jafingerhut** [comment]
You may close the issue.  Since you seem willing to do so, I will go ahead and close the issue.
