### ISSUE TITLE
socket.error: [Errno 19] No such device

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/tutorials#3]
Hi,

I'm trying to run copy_to_cpu example. However, I get the following error while running either 'udo python  send.py' or 'udo python receive.py' commands:
socket.error: [Errno 19] No such device

Any idea?

**Comment by antoninbas** [comment]
Please follow the README instructions (https://github.com/p4lang/tutorials/blob/master/examples/README.md#before-starting-the-exercises), you are supposed to run the `veth_setup.sh` script.

**Comment by ali64Mon** [comment]
Thanks.
