### ISSUE TITLE
P4 Switches running in NS?

### ISSUE THREAD

**Issue by ramonfontes** [p4lang/tutorials#301]
Is there any chance of running P4 switches such as BMV in Network Namespaces? I'm trying to do some work with wireless adhoc network, but instead of running Mininet hosts with wireless interface working in adhoc mode, I'd like to run a P4 switch equipped with such wireless interface working in adhoc mode. When all switches are placed to the root NS, nodes would communicate directly with each other without crossing their neighbors. Having each switch running in particular NS, I could make the wireless adhoc network work as expected.

BTW, I've created some tutorials for WiFi, for example: https://github.com/ramonfontes/tutorials/tree/master/exercises/handover. Some improvements still need to be made. This is only a first step.

**Comment by antoninbas** [comment]
You should be able to run bmv2 in its own network namespace with `ip netns exec`.

I don't know if it will work for your use case, but maybe the easiest thing to do is to run each bmv2 instance in a Docker container (https://hub.docker.com/r/p4lang/behavioral-model/). Then they will all run in their own network namespace. You can create veth pairs to connect neighbors as needed (with one end of the veth in one container's network namespace and the other end in the other container's network namespace).
