### ISSUE TITLE
Installation VM issue 

### ISSUE THREAD

**Issue by Gaurav-Pande** [p4lang/tutorials#302]
Hi,

I am trying to build the VM from the repo, but I am only able to see the xenial desktop with vagrant/vagrant credentials. I suppose the dependencies below dependencies installation is missing as pointed in the installation document.

sudo ./root-bootstrap.sh
sudo ./user-bootstrap.sh

However, It is mentioned that one can directly launch these scripts directly from the xenial terminal, but I cannot find these scripts inside the VM.
Do I need to change the vagrant file to mount the repo inside the VM or am I missing something?

**Comment by jafingerhut** [comment]
On the host OS, did you install vagrant, then clone this repository, change to the tutorials/vm directory and run the command `vagrant up`, then wait for an hour or so while it did all of the installation steps?

If you did something different, try that.

**Comment by Gaurav-Pande** [comment]
I did follow all those steps. However it asked the default username/password for vagrant(i.e: vagrant/vagrant). I see a blank xenial genome screen after login. I suppose based on your feedback i should wait for couple of hours for the installation to complete.

**Comment by jafingerhut** [comment]
When you say "blank xenial genome screen", do you mean completely blank, or is there a popup menu that you can make appear in the lower left corner (or any corner) that has many programs to choose from to run, e.g. a terminal?

If not for the 'vagrant' user, what about the 'p4' user?

Logging in doesn't normally start up any programs other than the desktop manager for this VM.

**Comment by Gaurav-Pande** [comment]
No, nothing shows up. Just the blank screen. here is the output of the screen(https://drive.google.com/file/d/1HUKvhRpWC4BVtsuKJ2EtvjUWI44yS2zF/view?usp=sharing)

**Comment by jafingerhut** [comment]
It sounds to me like something went wrong during 'vagrant up', or it did not complete.  I don't have any advice for determining which, but many many messages appear as output from 'vagrant up' for an hour or so if it goes well, in my experience.

**Comment by jafingerhut** [comment]
I just tried 'vagrant up' from the tutorials/vm directory this morning on a Mac with VirtualBox and vagrant installed on it.  It ended up creating files totaling about 20 GB of disk space on the host OS, and would have failed if that much free space were not available (my machine had much more than that much free when I started `vagrant up`).  With a decent reliable internet connection, it took about 80 mins to complete, and when complete, it booted to a Linux desktop showing several icons in a column on the left, and a task bar at the bottom, with the P4 'polar bear' mascot in the center of the screen, logged in as the user 'p4'.

**Comment by Gaurav-Pande** [comment]
Yes, thank for the feedback. I did clean up space and reinstalled vagrant again. It is similar to what you have mentioned. Thanks, I will proceed towards the examples to learn p4.
Also, is there a prebuilt VM available to use, so that one does not have to built the VM from scratch?

**Comment by jafingerhut** [comment]
There is a _different_ tutorials VM created two or three times per year for various live P4 teaching events.  One from April 2019 is linked to from this page: https://p4.org/events/2019-04-30-p4-developer-day/

Each such pre-built VM is likely to have slightly different contents from each other, i.e. different versions of open source P4 tools they were compiled from, and a different version of the tutorials repository cloned in them.

**Comment by jnfoster** [comment]
Correct. And there is an even more up-to-date VM linked to form the page
for the most recent tutorial at SIGCOMM '19 in August.

https://p4.org/events/2019-08-23-p4-tutorial/

-N

**Comment by jafingerhut** [comment]
Would you be open to a PR that added links to the most recent 2 or 3 pre-built VMs in the README of the tutorials repository?  We'd want to update it when a new one became available, but that isn't terribly often.

**Comment by jafingerhut** [comment]
For the versions of the tutorial that have public videos available, it would also be nice to have links to the videos that correspond to a particular pre-built tutorials VM, next to the link to that pre-built VM.  If someone is watching a particular tutorials video, it would be best if they had the precise version of the VM used for that instance of the tutorial presentation.

**Comment by jnfoster** [comment]
Yes, that would be great. Perhaps the Education WG co-chairs can take on
this task?
