### ISSUE TITLE
Can't deal with log levels

### ISSUE THREAD

**Issue by sergio-gimenez** [p4lang/tutorials#303]
I am doing a connectivity test for the availability of the bmv2 `simple_switch`. By now, the switch is loosing a quite decent amount of packets.

Sender is in `s1-eth2` and receiver is in `s1-eth1`.

```
s1-eth1   Link encap:Ethernet  HWaddr 00:00:00:00:01:0b  
          inet6 addr: fe80::200:ff:fe00:10b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10277 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:270 (270.0 B)  TX bytes:13324630 (13.3 MB)

s1-eth2   Link encap:Ethernet  HWaddr 00:00:00:00:01:01  
          inet6 addr: fe80::200:ff:fe00:101/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1618788 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2104420770 (2.1 GB)  TX bytes:3334 (3.3 KB)
```

For better results, I think that disable the log is a good idea (at most set it only in the error level).

I am doing the test within the [p4lang/tutorials](https://github.com/p4lang/tutorials) implementation, and I cannot really figure out how to change log level. I tried with setting `quiet` argument to `true` in `run_exercise.py`, which should stop writing log messages:

```python
parser.add_argument('-q', '--quiet', help='Suppress log messages.',
                    action='store_true', required=False, default=True)
```

But it did not worked. Any clues about how to supress log messages?

**Comment by antoninbas** [comment]
You can try setting `log_console` to `False` in these 2 places:
 * https://github.com/p4lang/tutorials/blob/master/utils/run_exercise.py#L87
 * https://github.com/p4lang/tutorials/blob/master/utils/run_exercise.py#L249

Your best shot however if you want to improve performance significantly may be to re-configure bmv2 with `--disable-logging-macros` (then re-build & re-install it). Without this, there is still the overhead of evaluating log function arguments, even if the messages are not actually logged. Assuming you are using the tutorials VM, this is the script in charge of building bmv2 (along with the rest of the p4lang software): https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L83

**Comment by sergio-gimenez** [comment]
Thanks @antoninbas for the answer. 

> You can try setting `log_console` to `False` 

That woked, but as you said, results are not  good as expected. I modified the debug level with the flag `--disable-logging--macros`, then I tried to re-install it by running the `user_bootstrap.sh` file in `/home/p4/tutorials/vm`. But it did not worked. I think the error appeared when running the command  `make -j${NUM_CORES}` in the `simple_switch_grpc` directory. 

I attach here the error ouptut:
```
make  all-recursive
make[1]: Entering directory '/home/p4/tutorials/vm/behavioral-model/targets/simple_switch_grpc'
Making all in .
make[2]: Entering directory '/home/p4/tutorials/vm/behavioral-model/targets/simple_switch_grpc'
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog  -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out   -g -O2 -std=c++11 -MT cpp_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.pb.lo -MD -MP -MF cpp_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.pb.Tpo -c -o cpp_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.pb.lo `test -f 'cpp_out/p4/bm/dataplane_interface.pb.cc' || echo './'`cpp_out/p4/bm/dataplane_interface.pb.cc
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog  -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out   -g -O2 -std=c++11 -MT grpc_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.lo -MD -MP -MF grpc_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.Tpo -c -o grpc_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.lo `test -f 'grpc_out/p4/bm/dataplane_interface.grpc.pb.cc' || echo './'`grpc_out/p4/bm/dataplane_interface.grpc.pb.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -g -O2 -std=c++11 -MT cpp_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.pb.lo -MD -MP -MF cpp_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.pb.Tpo -c cpp_out/p4/bm/dataplane_interface.pb.cc  -fPIC -DPIC -o cpp_out/p4/bm/.libs/libbm_grpc_dataplane_la-dataplane_interface.pb.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -g -O2 -std=c++11 -MT grpc_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.lo -MD -MP -MF grpc_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.Tpo -c grpc_out/p4/bm/dataplane_interface.grpc.pb.cc  -fPIC -DPIC -o grpc_out/p4/bm/.libs/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.o
make[2]: *** No rule to make target '../../PI/libbmpi.la', needed by 'libsimple_switch_grpc.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -g -O2 -std=c++11 -MT cpp_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.pb.lo -MD -MP -MF cpp_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.pb.Tpo -c cpp_out/p4/bm/dataplane_interface.pb.cc -o cpp_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.pb.o >/dev/null 2>&1
mv -f cpp_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.pb.Tpo cpp_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.pb.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -I./../simple_switch/gen-cpp -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -g -O2 -std=c++11 -MT grpc_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.lo -MD -MP -MF grpc_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.Tpo -c grpc_out/p4/bm/dataplane_interface.grpc.pb.cc -o grpc_out/p4/bm/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.o >/dev/null 2>&1
mv -f grpc_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.Tpo grpc_out/p4/bm/.deps/libbm_grpc_dataplane_la-dataplane_interface.grpc.pb.Plo
make[2]: Leaving directory '/home/p4/tutorials/vm/behavioral-model/targets/simple_switch_grpc'
Makefile:888: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/p4/tutorials/vm/behavioral-model/targets/simple_switch_grpc'
Makefile:547: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by antoninbas** [comment]
* it's `--disable-logging-macros` not `--disable-logging-macros`

* usually that build error happens when bmv2 is configured without `--with-pi`, but the script uses that flag so I'm not sure why it would fail unless you removed the flag yourself. You can probably re-install bmv2 without running the whole script again. Just cd into the `behavioral-model` folder and tun `./autogen.sh && ./configure --with-pi --disable-logging-macros && make && sudo make install && sudo ldconfig`. Then cd into `behavioral-model/targets/simple_switch_grpc` and run `./autogen.sh && ./configure --with-thrift && make && sudo make install`

* the throughput depends on which P4 program you are running. I'm going to assume the graph is wrong and that the packet size is in **bytes**, not in bits (otherwise the performance is way higher than it should be already). I would say that target performance for a simple P4 program which is 1) parsing the ethernet & ipv4 headers and 2) performing a couple of exact / LPM lookups with simple actions, should be around 100,000 pps, which is about twice what you are getting right now. But you are already in the correct ballpark, so don't expect a 10x improvement just by building without logging macros.

**Comment by sergio-gimenez** [comment]
>Just cd into the `behavioral-model` folder and tun `./autogen.sh && ./configure --with-pi --disable-logging-macros && make && sudo make install && sudo ldconfig`. Then cd into `behavioral-model/targets/simple_switch_grpc` and run `./autogen.sh && ./configure --with-thrift && make && sudo make install`

Tried this and worked. Thanks!

> I'm going to assume the graph is wrong and that the packet size is in bytes, not in bits (otherwise the performance is way higher than it should be already)

Yes, bytes (typo) :sweat_smile:.

> you are already in the correct ballpark, so don't expect a 10x improvement just by building without logging macros.

Although throughput is in the expected magnitude order, I am asking myself if the great amount of lost packets in the router interfaces is the expected.

>```
>s1-eth1   Link encap:Ethernet  HWaddr 00:00:00:00:01:0b  
>         inet6 addr: fe80::200:ff:fe00:10b/64 Scope:Link
>          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
>          TX packets:10277 errors:0 dropped:0 overruns:0 carrier:0
>          collisions:0 txqueuelen:1000
>          RX bytes:270 (270.0 B)  TX bytes:13324630 (13.3 MB)
>
>s1-eth2   Link encap:Ethernet  HWaddr 00:00:00:00:01:01  
>          inet6 addr: fe80::200:ff:fe00:101/64 Scope:Link
>          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>          RX packets:1618788 errors:0 dropped:0 overruns:0 frame:0
>          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
>          collisions:0 txqueuelen:1000
>          RX bytes:2104420770 (2.1 GB)  TX bytes:3334 (3.3 KB)
>```

The quote above, shows the bmv2 interfaces directly connected to the hosts: sender is in `s1-eth2` and receiver is in `s1-eth1`. I'm quite surprised with the lost packets:  
Received packets in `s1-eth2` `RX packets:1618788` and forwarded packets in `s1-eth1` `TX packets:10277` entails losses around **99%**.


I made a [program in c ](https://github.com/PouzinSociety/rinap4dataplane/files/3840771/efcp-generator.txt.txt)in order to test the performance of the router. In that program, I modified the inter arrival time of the packets in order to evaluate the losses:

![Losses vs  inter arrival time  μs](https://user-images.githubusercontent.com/42917235/68758479-306d4e00-060e-11ea-8532-788e18c8d769.png)

Is this the desired behavior in terms of losses? I have done the test in the tutorials VM inside Mininet.

**Comment by jnfoster** [comment]
Closing as this does not seem to be an issue with the tutorial code itself.
