### ISSUE TITLE
Is there any method/process to count number of ingress packets in switch

### ISSUE THREAD

**Issue by Gaurav-Pande** [p4lang/tutorials#306]
I am trying to understand how we can measure the traffic counters using the p4 packets processing pipeline. Is there any way to achieve this?

**Comment by jafingerhut** [comment]
Using the v1model architecture that I believe all of the tutorial code does, there is a Counter extern object that you can use to update packet and/or byte counts in your P4 program, with the API documented here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L107-L170

The rest of that #include file contains possibly useful features available in the v1model architecture as well, so you may want to read through all of that file if you are looking for other capabilities in the future.

This file is also a good source of capabilities and restrictions of the v1model implementation: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

This example P4_16 program demonstrates using a DirectCounter, which has a one-to-one association with table entries (as opposed to a Counter extern, which is an array of counter elements indexed by an integer, like an array): https://github.com/jafingerhut/p4-guide/blob/master/demo2/demo2.p4_16.p4#L83-L103

I don't have any P4Runtime API example code to point you at off the top of my head for reading these counters from the control plane.  Note that such counter externs are "update only" from the P4 program -- only the control plane code can read them, not the P4 program.

If you want counters (and more general things) that can be both updated and read from the P4 program (and from the control plane code), the Register extern can do that.  This example program shows how to use a Register extern to implement a packet count per input port: https://github.com/jafingerhut/p4-guide/blob/master/demo6/demo6.p4_16.p4#L86-L97
