### ISSUE TITLE
mri - OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Wasdns** [p4lang/tutorials#31]
Hi, all.

Happy to see that the P4D2_2017 have been published today. But I found a problem(or a bug?) which makes me puzzled as I tried the exercise named `mri`. 

## My Environment

- Ubuntu 14.04, 64bit

- Already install the bmv2, p4c-bm, p4c, mininet etc.

## My Steps

1.First fullfill the `env.sh` with my environment settings.

2.Fllow the steps below:
```
$ cd P4D2_2017/exercises/mri

// I use the solution in my first attempt:
$ mv mri.p4 oldmri.p4 
$ cp -r solution/mri.p4 ./

$ ./run.sh
```

## Error Details

The step `./run.sh` raised the error `OSError: [Errno 2] No such file or directory`: 

```
Entering build directory.
Extracting package.
Reading package manifest.
> p4c-bm2-ss --p4v 16 "mri.p4" -o "mri.p4.json"
*** Log directory /home/wasdns/tutorials/P4D2_2017/exercises/mri/build/logs
*** Pcap directory /home/wasdns/tutorials/P4D2_2017/exercises/mri/build
> python2 "/home/wasdns/tutorials/P4D2_2017/utils/mininet/multi_switch_mininet.py" --log-dir "/home/wasdns/tutorials/P4D2_2017/exercises/mri/build/logs" --manifest "./p4app.json" --target "multiswitch" --auto-control-plane --behavioral-exe "simple_switch" --json "mri.p4.json" --cli-message "mininet_message.txt"
*** Creating network
*** Adding hosts:
h1 h2 h3 
*** Adding switches:
s1 s2 s3 
*** Adding links:
Traceback (most recent call last):
  File "/home/wasdns/tutorials/P4D2_2017/utils/mininet/multi_switch_mininet.py", line 242, in <module>
    main()
  File "/home/wasdns/tutorials/P4D2_2017/utils/mininet/multi_switch_mininet.py", line 145, in main
    controller = None)
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 164, in __init__
    self.build()
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 357, in build
    self.buildFromTopo( self.topo )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 344, in buildFromTopo
    self.addLink( src, dst, srcPort, dstPort, **params )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 287, in addLink
    return cls( node1, node2, **defaults )
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 400, in __init__
    params2=params)
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 350, in __init__
    self.makeIntfPair( intfName1, intfName2 )
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 381, in makeIntfPair
    makeIntfPair( intf1, intf2  )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 154, in makeIntfPair
    quietRun( 'ip link del ' + intf1 )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 117, in quietRun
    return errRun( cmd, stderr=STDOUT, **kwargs )[ 0 ]
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 77, in errRun
    popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## Related Questions

After the attempt to fix this problem, I found a question that is most similar to my situation:

- [mininet/examples/limit.py cannot be run when not using VM](https://github.com/mininet/mininet/issues/141)

But the solution is useless to me. The problem is still remained. 

Could you give me some instructions on how to deal with it? Thanks a lot!

**Comment by robertsoule** [comment]
This looks like Mininet did not shut down correctly. I think you can run:
$ sudo mn -c

Which should get you back to a clean state.

**Comment by Wasdns** [comment]
@robertsoule Thank you for your help, but the question still remained.

**Comment by robertsoule** [comment]
I'm not able to recreate this issue.

**Comment by antoninbas** [comment]
Based on the error message, I would think that the `ip` tool is not available on your machine, but Mininet seems to be using the tool to create links.
Please try to install the `iproute2` package for ubuntu (`sudo apt-get install iproute2`) and let us know if it solves your issue.

**Comment by Wasdns** [comment]
@antoninbas 

Thanks a lot. But unfortunately, it did not work. The same error raised. Moreover, it showed me the same result when I tried the demo named `ipv4_forward`. One probably reason lies in the configurations of my laptop. Don't know why but I will try to migrate my experiments into a better environment(i.e.PC). I'll report my situation to you if it works fine with another env.  Thank you very much!

**Comment by NofelYaseen** [comment]
@Wasdns 
Were you able to solve this issue?

**Comment by Wasdns** [comment]
@NofelYaseen 
Nop. But I installed complete P416 environment on a PC and it works fine now.

**Comment by sajadys** [comment]
@Wasdns 
what do u mean by "P416 envi..." ?
i have ur problem already

**Comment by Wasdns** [comment]
@sajadys 
It cosists of bmv2, p4c-bm, and p4c. I didn't resolve this problem at that time. Instead, I installed all the software mentioned above on another PC.
BTW, I think this problem could be reproduced in some ways. Maybe it could be resolved by installing some missing dependencies.

**Comment by KallelSana** [comment]
Were you able to solve this issue? I have the same problem

**Comment by sajadys2003** [comment]
@KallelSana I installed fresh ubuntu desktop , and then installed mininet wifi , and done
