### ISSUE TITLE
is modify_field supported?

### ISSUE THREAD

**Issue by Gaurav-Pande** [p4lang/tutorials#311]
I am trying to run the following block of code:
action set_seq(tcp_t seq_num, egressSpec_t port) {
        modify_field(standard_metadata.egress_spec, port);
        }

But I am receiving below error:
vagrant@p4:~/tutorials/exercises/basic$ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
basic.p4(116): [--Werror=not-found] error: modify_field: Not found declaration
     modify_field(standard_metadata.egress_spec, port);
     ^^^^^^^^^^^^

I do not suppose we have to declare this in parsing the headers right? I see some github implementations, everywhere it is directly used.

**Comment by jafingerhut** [comment]
modify_field() and many other language constructs like it are specific to the P4_14 version of P4.  The p4c-bm2-ss command above uses the options `--p4v 16` which specifies that your source program is in the P4_16 version of P4.  While their capabilities are quite similar, the syntax of P4_14 and P4_16 are fairly different.

As an example of two probably-equivalent behavior programs, one written in P4_14 and one written in P4_16, you can look at these two:
https://github.com/jafingerhut/p4-guide/blob/master/demo1/demo1.p4_14.p4
https://github.com/jafingerhut/p4-guide/blob/master/demo1/demo1.p4_16.p4

It is up to you whether you want to write your source program in P4_14 or P4_16, but if you do not have a strong preference, I would recommend that P4_16 can be little bit less verbose, e.g. assignment statements and expressions look more like C/C++/Java assignments, for example.
