### ISSUE TITLE
Is there anyway to print messages we run the p4?

### ISSUE THREAD

**Issue by Gaurav-Pande** [p4lang/tutorials#312]
If I wanted to check or print some values of the specific header field (say hdr.ipv4.srcAddr), whenever a switch process the packets, how do I print it or debug what values are going, or is there a way to write the value of these variables to a file may be using P4?

**Comment by jnfoster** [comment]
A common debugging technique is to add a dummy table whose key is the value you want to debug.

For example:

```
table debug_ipv4_srcAddr {
  key = { hdr.ipv4.srcAddr : exact; }
  actions = {}
}
```
If you add `debug_ipv4_srcAddr.apply()` somewhere in your P4 program, the value of `ipv4.srcAddr` at that point will be added to the Bmv2 log.

**Comment by Gaurav-Pande** [comment]
Thank you.

**Comment by antoninbas** [comment]
As an alternative solution, we recently introduced a `log_msg` extern function, which can be used to log arbitrary strings & values: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L627

Support for `log_msg` was finalized in p4c & bmv2 in October 2019, so if you are using the tutorials VM (which is only updated about twice a year and therefore often contains older version of the software), you may not have access to it for now.
