### ISSUE TITLE
Two hosts in the same network

### ISSUE THREAD

**Issue by sanaa50** [p4lang/tutorials#314]
Hi,
I want to edit the "host2"  network from the basic forwarding so that both host1and host2 are in the same network.
```
        "h1": {"ip": "10.0.1.1/24", "mac": "08:00:00:00:01:11",
               "commands":["ip route add default via 10.0.1.10 dev eth0",
                           "arp -i eth0 -s 10.0.1.10 08:00:00:00:01:00"]},
        "h2": {"ip": "10.0.1.2/24", "mac": "08:00:00:00:02:22",
               "commands":["route add default gw 10.0.1.10 dev eth0",
                           "arp -i eth0 -s 10.0.1.10 08:00:00:00:01:00"]},
```

I edited the runtime.json files with the host2 new IP but ping to host2 failed.

What is wrong with my code?
Is it possible to edit the IP addresses in that way?

**Comment by jafingerhut** [comment]
The file topology.json is an input file to mininet, I believe, which is part of what you need to do.

However, I believe that changing the contents of the topology.json file does _nothing_ to change what table entries are added to the virtual switches in the network.  The table entries added are controlled _only_ by the contents of the files with names like `s1-runtime.json` `s2-runtime.json` etc.  Some Python program that is run, and acting as a "controller" for the switches, reads those files and uses their contents to decide what table entries to add to the switches.  I don't know which Python program, but it shouldn't take much eperimentation / code reading to figure out which one(s) are doing that.  You may not need to modify the Python program at all (not sure) to achieve your goals -- perhaps editing the `s1-runtime.json` and similar files for `s2` and `s3` will be enough.

**Comment by sanaa50** [comment]
> The file topology.json is an input file to mininet, I believe, which is part of what you need to do.
> 
> However, I believe that changing the contents of the topology.json file does _nothing_ to change what table entries are added to the virtual switches in the network. The table entries added are controlled _only_ by the contents of the files with names like `s1-runtime.json` `s2-runtime.json` etc. Some Python program that is run, and acting as a "controller" for the switches, reads those files and uses their contents to decide what table entries to add to the switches. I don't know which Python program, but it shouldn't take much eperimentation / code reading to figure out which one(s) are doing that. You may not need to modify the Python program at all (not sure) to achieve your goals -- perhaps editing the `s1-runtime.json` and similar files for `s2` and `s3` will be enough.

Well, to be  more clear, what I want to do is building costume network with costume IP addresses. How do I can do that ?

**Comment by jafingerhut** [comment]
First you create the topology of switches and hosts that you want.  In the case of the exercises, that can be done by modifying the mininet data file that is used to create the network, as you have already done.

Then you need to modify the table entries installed into the switches, such that packets are forwarded as you wish.  I would recommend getting out a big sheet of graph paper, draw the topology of the original, unmodified, working basic exercise, and then run it, and use whatever mechanisms you are familiar with to read the table entries in all 3 switches, in all tables of the P4 program, and understand how those table entries cause the packets to be forwarded to the hosts correctly.  For example, you should be able to use `simple_switch_CLI` and `table_dump` commands to read all table entries from the switches.  Then look in the files like `s1-runtime.json` to see how they correspond to the installed table entries that you read.  Then maybe do some experiments where you change the `s1-runtime.json` file a little bit, start the experiment over again, read the table entries in switch `s1` again, and see how they are different than before.

Then on another fresh sheet of paper, draw out the different network topology you wish to have, and think about how the P4 program works given the original working example.  Figure out how you need to install different table entries that will cause packets to be forwarded as you wish in your new network, and then when you have figured those out, write new `s1-runtime.json` etc. files that cause those table entries to be installed.

Paper, pencil, and brain can be wonderful tools when figuring out how something works.

**Comment by sanaa50** [comment]
I made my  own graphs and notes as you suggested, then worked with simple test such as changing h2 IP address to 10.0.22.3. That change caused the ping to both h1 and h2 to be failed. 
Is there a specific pattern to distribute the IP and MAC addresses?

**Comment by jafingerhut** [comment]
Do you know _exactly which_ sequence of switches and links that packets in a successful ping test of the unmodified basic tutorial example are being traversed, from h1 to h2?  From h2 to h1?

Do you know _exactly which_ contents the packet headers have when crossing each of those links?  Have you looked at the simple_switch log files for a packet being forwarded, and know exactly which sequence of tables are being applied, in what order?  And exactly which table entry is being matched when each table is applied, and which action is executed, with what action parameter values?  Or if a miss is occurring when the table is applied, and thus the default action is executed instead?

If you understand _all_ of those details for a working ping, and put them in your big figure, it should become much clearer what you need to change when making pings work in a different network of switches.

If you do not understand all of those things, then me telling you what table entries to use won't give you much understanding of why those table entries are the ones to be used.
