### ISSUE TITLE
ERROR during installing

### ISSUE THREAD

**Issue by minziran** [p4lang/tutorials#318]
:~/p4c/build$ make -j4
[ 90%] Built target linkgraphs
[ 90%] Built target linkbmv2
[ 90%] Built target linkp4test
[ 90%] Built target update_includes
[ 90%] Built target linkp4cebpf
[ 90%] Built target mkv1dirs
[ 90%] Built target mkp4dirs
[ 90%] Built target mkP4configdir
[ 90%] Built target p4ctoolkit
[ 90%] Built target p4c_driver
[ 90%] Built target gtest
[ 90%] Built target irgenerator
[ 90%] Generating IR class files
[ 90%] Built target genIR
[ 90%] Built target ir
[ 90%] Built target midend
[ 90%] Built target frontend
[ 90%] Built target controlplane
[ 90%] Linking CXX executable p4test
[ 90%] Built target p4c-ebpf
[ 90%] Built target p4c-graphs
[ 90%] Built target bmv2backend
[ 90%] Linking CXX executable p4c-bm2-ss
[ 90%] Linking CXX executable p4c-bm2-psa
[ 90%] Linking CXX executable gtestp4c
/home/minziran/p4c/control-plane/p4RuntimeSerializer.cpp:134: error: undefined reference to 'google::protobuf::util::MessageToJsonString(google::protobuf::Message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, google::protobuf::util::JsonPrintOptions const&)'
/home/minziran/p4c/control-plane/p4RuntimeSerializer.cpp:134: error: undefined reference to 'google::protobuf::util::Status::OK'
/usr/include/google/protobuf/generated_message_util.h:134: error: undefined reference to 'google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
/usr/include/google/protobuf/arena.h:649: error: undefined reference to 'google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:651: error: undefined reference to 'google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
/usr/include/google/protobuf/stubs/status.h:97: error: undefined reference to 'google::protobuf::util::Status::operator==(google::protobuf::util::Status const&) const'
/usr/include/google/protobuf/map_field_inl.h:312: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/usr/include/google/protobuf/map_field_inl.h:314: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SetMapDirty()'
/usr/include/google/protobuf/map_field_inl.h:312: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/usr/include/google/protobuf/map_field_inl.h:314: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SetMapDirty()'
/usr/include/google/protobuf/map_field_inl.h:312: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/usr/include/google/protobuf/map_field_inl.h:314: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SetMapDirty()'
/usr/include/google/protobuf/map_field_inl.h:312: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/usr/include/google/protobuf/map_field_inl.h:314: error: undefined reference to 'google::protobuf::internal::MapFieldBase::SetMapDirty()'
/usr/include/google/protobuf/arena.h:644: error: undefined reference to 'google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:644: error: undefined reference to 'google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/include/google/protobuf/arena.h:644: error: undefined reference to 'google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
.
.
.
.
.
.google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
/home/minziran/p4c/build/control-plane/p4/v1/p4data.pb.cc:150: error: undefined reference to 'google::protobuf::internal::RegisterAllTypes(google::protobuf::Metadata const*, int)'
/home/minziran/p4c/build/control-plane/p4/v1/p4data.pb.cc:175: error: undefined reference to 'google::protobuf::internal::InitProtobufDefaults()'
/home/minziran/p4c/build/control-plane/google/rpc/status.pb.cc:84: error: undefined reference to 'google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::InitDefaults()'
/home/minziran/p4c/build/control-plane/google/rpc/status.pb.cc:105: error: undefined reference to 'google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors()'
/usr/include/google/protobuf/wire_format_lite_inl.h:509: error: undefined reference to 'google::protobuf::Any::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)'
/usr/include/google/protobuf/repeated_field.h:599: error: undefined reference to 'google::protobuf::Any::Clear()'
/usr/include/google/protobuf/arena.h:649: error: undefined reference to 'typeinfo for google::protobuf::Any'
collect2: error: ld returned 1 exit status
backends/bmv2/CMakeFiles/p4c-bm2-ss.dir/build.make:96: recipe for target 'backends/bmv2/p4c-bm2-ss' failed
make[2]: *** [backends/bmv2/p4c-bm2-ss] Error 1
CMakeFiles/Makefile2:1300: recipe for target 'backends/bmv2/CMakeFiles/p4c-bm2-ss.dir/all' failed
make[1]: *** [backends/bmv2/CMakeFiles/p4c-bm2-ss.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jafingerhut** [comment]
What steps did you follow that led to this error?

For example, did you do the steps in the README here?  https://github.com/p4lang/tutorials#obtaining-required-software

If so:

Did you do that using the latest version of the tutorials repository files?

In the master branch, or some other branch?

Did you ensure you had at least 25 Gbytes of free disk space when the steps said to do that?

Was your Internet connection reliable throughout?  If not, the script may have failed to download the Google Protobuf source code as it should.

**Comment by jafingerhut** [comment]
Also, if your goal is to get a Linux VM created with the P4 tools installed, and not to debug the installation process, you can download an already-created Linux VM and install that, following the instructions here: https://github.com/p4lang/tutorials/tree/sigcomm19

**Comment by minziran** [comment]
Thank you for your help !
I am using this tutorial, https://github.com/p4lang/p4c
And in the step "make -j4", meet this error.

**Comment by jafingerhut** [comment]
p4c has quite a few dependencies, and while the README's are accurate, I think, it is very, very easy to miss a step.

If you want to start with a freshly installed Ubuntu 16.04 or 18.04 Linux system, and install most of the open source P4 tools using a script that follows the README instructions, you can the ones described here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by jnfoster** [comment]
Closing this for lack of discussion...
