### ISSUE TITLE
Error in tutorial text

### ISSUE THREAD

**Issue by hanw** [p4lang/tutorials#32]
In the arp example.
https://github.com/p4lang/tutorials/tree/master/P4D2_2017/exercises/arp

The description says:

An action (named ipv4_forward) to store information in the metadata structure, rather than immediately writing to the packet header.

A table (named ipv4_lpm) that will match on the destination IP address and invoke the ipv4_forward action.

But actually the action for ipv4_lpm should be `set_dst_info`in simple_router.config:
```
table_add ipv4_lpm set_dst_info 10.0.1.10/24 => 00:00:01:00:00:01 00:00:02:00:00:02 1
```

**Comment by haazy** [comment]
Hello All, I am new here. I am trying to play around with p4 on mininet and I am looking for resources online to help me but I have not found any.

Kindly please help me

Haazy
