### ISSUE TITLE
Changing the server IP

### ISSUE THREAD

**Issue by sanaa50** [p4lang/tutorials#321]
Hi,
In the load_balance exercise, when changing the IP address of the server from "10.0
0.1" to any other IP, both of h2 and h3 not receiving packets from h1 (I changed the IP in s1-runtime.json).

Can anyone explain the reason please?

**Comment by jafingerhut** [comment]
It is well worth the time when debugging P4 programs to learn how to read and follow the contents of the log files produced when processing packets. They contain detailed information about each if condition evaluated, what file name and line number the condition was at, whether it evaluated to true or false, each table applied, what the search key contents were, whether it matched a table entry or not, and if so, which one, which action was executed, etc.

Frankly, if you are trying to debug a P4 program's behavior, and your are _not_ looking at this log output, then I have no idea how anyone can do it, other than guessing.

**Comment by sanaa50** [comment]
OK, it may sound a dump question but where to find these log files?!

**Comment by jafingerhut** [comment]
Search for occurrences of the word "logs" in the README.md file here: https://github.com/p4lang/tutorials/tree/master/exercises/basic
