### ISSUE TITLE
some issues about INT,please help me

### ISSUE THREAD

**Issue by nosugerhcc** [p4lang/tutorials#322]
I am doing the MRI example.The code mri.p4 shows the switch's ID and queue length ,which the code is "standard_metadata.deq_qdepth".I want to know if I need other INT datas like the forwarding latency or queue occupacy or egress link utilization, can I find these datas in "standard_metadata",and how to get them?

**Comment by jafingerhut** [comment]
You can find more documentation about the v1model standard_metadata fields available in two places:

https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md
https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4

**Comment by nosugerhcc** [comment]
Thank you ! It helped me a lot

**Comment by nosugerhcc** [comment]
Hello. I tried to add "timedelta" in mri.p4 ,send.py and receive.py,but it shows that cannot receive the data pack .I could get the data packet if there is only "qdepth" or "timedelta" ,but it is not work for both of them. Is there some configuration file that limits this?

**Comment by jafingerhut** [comment]
If you can publish the complete code that you tried to use, e.g. in your own public Github repository with a link here, showing in detail what you tried, perhaps someone could take a look.  It would also be good to run this script on your system and publish the output, because that will show what versions of p4c, simple_switch, and several other software tools installed on your system: https://github.com/jafingerhut/p4-guide/blob/master/bin/p4-environment-info.sh

Without such details, it is not easy to determine what might be going wrong.

**Comment by nosugerhcc** [comment]
https://github.com/nosugerhcc/mriplus 
I just add "timedelta" in mri.p4 like "qdepth" and add IntField("timedelta",0) in send/receive.py like IntField("qdepth", 0). I dont know if I am doing right...

**Comment by sbibek** [comment]
I ran into the same issue where I add a field to switch_t as following
```
typedef bit<32> hoplatency_t;

header switch_t {
    switchID_t  swid;
    qdepth_t    qdepth;
    hoplatency_t hoplatency;
}
```

Then I populate it in the egress and update the length information accordingly.

` hdr.swtraces[0].hoplatency = (hoplatency_t) standard_metadata.deq_timedelta;`

```
 hdr.ipv4.ihl = hdr.ipv4.ihl + 3;
 hdr.ipv4_option.optionLength = hdr.ipv4_option.optionLength + 12; 
 hdr.ipv4.totalLen = hdr.ipv4.totalLen + 12;
```

I checked wireshark and it complains the following
Bogus IP header length (8 must be atleast 20).

I understand what the wireshark is complaining about but I am not sure why the above addition is causing that.  Am I missing something here?

**Comment by jfingerh** [comment]
That link does not seem to exist (or perhaps it exists, but it is not a public repo?).

In general, a reasonable debugging technique is to examine the raw sequence of bytes of the packet coming out, and see if the IHL field in the IPv4 header is truly less than 5, which is an error.  Do that not by believing Wireshark's decoding, but by decoding the packet bytes manually, by yourself, at least up to the beginning of the IPv4 header.  If the IHL field is less than 5, then check the input packet similarly, and also you can look at the simple_switch_grpc process logs created while it processes packets to see every assignment statement performed, every table looked up, etc. to see if you can determine when that IHL field was assigned a value you did not want.
