### ISSUE TITLE
ImportError: No module named grpc

### ISSUE THREAD

**Issue by raf759** [p4lang/tutorials#323]
I tried to run exercises in the tutorials repository and got this result, any solution would be helpful

$ sudo make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
 tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  tutorials/utils/p4runtime_lib/switch.py", line 19, in <module>
    import grpc
ImportError: No module named grpc
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jafingerhut** [comment]
It looks like you have a system where not all required software (like the Python grpc module) was installed.  Did you follow these instructions to set up your system?  https://github.com/p4lang/tutorials#obtaining-required-software

Or did you download a pre-built VM as described here?  https://github.com/p4lang/tutorials#older-tutorials

or something else?

**Comment by raf759** [comment]
above mentioned error came because I tried to run  p4lang tutorials without VM
I have followed the instruction of above mentioned link, and two login profile setup in VM
Now in basic.p4 while I am running mininet and execute this command 'h1 ping h2'
I am getting 100% packet loss
do you know what could be the problem?
Do I need to setup Network in VM?

**Comment by jafingerhut** [comment]
Are you using the original version of the file basic.p4 in the exercises/basic directory?  If so, that one has comments in it, mentioned in the README, that explain what is missing and needs to be added, and there is a solutions subdirectory with one correct solution.  Without those changes, all packets will be dropped, if I recall correctly.

**Comment by jnfoster** [comment]
Closing this for lack of discussion...
