### ISSUE TITLE
Error received from peer ipv4:127.0.0.1:50051

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#324]
salam'
I get this error when running  ''https://github.com/p4lang/tutorials/tree/master/exercises/p4runtime''   
                      **make run** 
I didn't have this error before and I didn't make any update

 File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 303, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "{"created":"@1577698817.289714420","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"","grpc_status":2}"
>
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jnfoster** [comment]
It's hard to say without more information. If you truly didn't change anything, perhaps try running `make clean` to make sure that all state from Mininet and the software switches is cleaned up, then try again?

**Comment by jnfoster** [comment]
Closing this for lack of discussion...
