### ISSUE TITLE
Question about ECN

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/tutorials#325]
Hello:
  I have a question about ECN in P4. If I install DCTCP in the kernel of Ubuntu, and run the P4 code of ecn tutorials. Will the sender reduce its sending window in a DCTCP way? Thank you so much!

**Comment by jnfoster** [comment]
In principle, I believe this will work. 

Of course, you may need to tune the threshold for marking packets. And keep in mind that Bmv2's default queuing behavior is simple. So I am not saying this will "just work" out of the box without any tweaks. But yes, I believe the form of IP ECN implemented by the tutorial solution is consistent with functionality requiured for DCTCP.

**Comment by Wannabeperfect** [comment]
@jnfoster  Thank you so much! I have another one question and wish you could help me solve it.   Is there a way in P4 to define a variable that can be both used in **ingress** and **egress**? How to define this variable?  :)

**Comment by cc10512** [comment]
You could declare the variable (or set of variables) as part of a header that you bridge between ingress and egress. You will need to assign and add the header in ingress, parse and use it in egress and drop it before sending the packet out.

**Comment by jafingerhut** [comment]
@cc10512 In the v1model architecture there is no egress parser.

I have not done detailed testing of this, but I believe that if you happen to declare the same user-defined metadata field names in ingress, and also in egress, then when a packet is unicast or multicast from ingress to egress, it just happens to preserve those field values.

Whether it does this across resubmit, clone, and recirculate operations is a separate question.

v1modle is a bit "magic" or "implicit" in this way, I believe intending to emulate this behavior in P4_14 programs, where all user-defined metadata has global scope.

**Comment by jafingerhut** [comment]
To clarify something in my previous comment, v1model restricts the type of the user-defined metadata inout parameter with type `M` to be the same type for both ingress and egress, so you do not "happen to declare the same user-defined metadata field in ingress, and also in egress", as I said before.  You have to use the same struct of user-defined fields that is completely identical for ingress and egress when writing v1model architecture programs.

Of course, you do not have to _use_ all of those fields in both ingress and egress.  Some might only be used in ingress, some only in egress, and some in both.  Regardless, I believe that at least for at least unicast and multicast packets, all of the user-defined field values that a packet had at the end of ingress, are preserved and are the initial values for those fields when egress processing begins.
