### ISSUE TITLE
Error creating interface pair (h10-eth0,s1-eth1): RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#328]
salam'
Please I m using a topology of 12 hosts connected to one switch. 
When compiling the program with "make run 
it gives Error
Exception: Error creating interface pair (h10-eth0,s1-eth1): RTNETLINK answers: File exists
I have already do sudo mn -c when running 'make clean

This is the topology
[topo.txt](https://github.com/p4lang/tutorials/files/4108960/topo.txt)

**Comment by jafingerhut** [comment]
There is a limitation in the current tutorials Python code for parsing the topology.json file where it only pays attention to a single digit of the switch port numbers of links.  The 1-line change proposed in this pull request enables the code to pay attention to multiple digits: https://github.com/p4lang/tutorials/pull/329/files
