### ISSUE TITLE
Unable to find vagrant image

### ISSUE THREAD

**Issue by Forslund2** [p4lang/tutorials#332]
I am trying to run the tutorials, but when i run the "vagrant up" command i get the following error:

The box 'lasp/ubuntu16.04-desktop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/lasp/ubuntu16.04-desktop"]
Error: The requested URL returned error: 404 Not Found

**Comment by jnfoster** [comment]
See #204
