### ISSUE TITLE
p4-tutorial: Box 'lasp/ubuntu16.04-desktop' could not be found.

### ISSUE THREAD

**Issue by computersarecool** [p4lang/tutorials#334]
Trying to follow your directions on Windows I get:

```
C:\Users\user\Documents\projects\p4lang\vm>vagrant up
Bringing machine 'p4-tutorial' up with 'virtualbox' provider...
==> p4-tutorial: Box 'lasp/ubuntu16.04-desktop' could not be found. Attempting to find and install...
   p4-tutorial: Box Provider: virtualbox
   p4-tutorial: Box Version: >= 0
The box 'lasp/ubuntu16.04-desktop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
 
URL: ["https://vagrantcloud.com/lasp/ubuntu16.04-desktop"]
Error: The requested URL returned error: 404 Not Found

```

Do you have any idea how to fix this?

**Comment by jafingerhut** [comment]
Near the end of the README are links to some previously given live tutorials, and most/all of those contain links to virtual machine images that have already compiled P4 dev tools on them, albeit not the latest versions, but the most recent ones are only a few months old.

You can also avoid using `vagrant up`, instead creating your own Ubuntu 16.04 Linux VM, then using the bash scripts that `vagrant up` runs on the VM, and run those yourself from the command line.  I have not tried this approach before myself, but believe others have done so: https://github.com/p4lang/tutorials/blob/master/vm/Vagrantfile#L27-L28

There are several other scripts in various other repositories that can also download and build all of the open source P4 development tools, if you do not like that approach.

**Comment by computersarecool** [comment]
Thanks for finding those links! I downloaded the `.ova` from one of those tutorials directly and it worked well.
