### ISSUE TITLE
Question about Multicast: "instance" param

### ISSUE THREAD

**Issue by davidcawork** [p4lang/tutorials#337]
Hi, everybody!

Before writing this issue I've been reading this [other closed issue](https://github.com/p4lang/tutorials/issues/22) but I haven't found the information I need..

I would like to know what the field "instance" indicates when defining the replicas of a Multicast group. Currently in multicast exercise it is indicated that the instance field of all the replicas is "**1**".

```json
"multicast_group_entries" : [
    {
      "multicast_group_id" : 1,
      "replicas" : [
        {
          "egress_port" : 1,
          "instance" : 1
        },
        {
          "egress_port" : 2,
          "instance" : 1
        },
        {
          "egress_port" : 3,
          "instance" : 1
        }
      ]
    }
  ]

```

What I understand is that the multicast group with identifier 1 will generate packet replies on ports 1, 2, and 3. But, what does indicate  ``"instance" : "1" `` ?

Thanks 😄 !

**Comment by antoninbas** [comment]
This is covered in the P4Runtime spec: https://p4.org/p4runtime/spec/v1.1.0/P4Runtime-Spec.html#sec-multicastgroupentry. This is just a way to distinguish between multiple multicast packets sent to the same port.

**Comment by davidcawork** [comment]
Thanks a lot for the resource! 😄

**Comment by gitMenv** [comment]
The specification states that you can distinguish the different instances in the egress using the `instance` metadata.
For the v1model.p4, this is not the case as it does not have an `instance` field in its metadata struct.
The information gets stored in the `egress_rid` field instead. 
Hope this helps for others that find this question!
