### ISSUE TITLE
Exception: Encoding objects of <type 'tuple'> is not supported

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#339]
salam 
I create a P4runtime control program in python language as you can see in attached 
[mycontroller.txt](https://github.com/p4lang/tutorials/files/4390254/mycontroller.txt)

The program allows to populate the ipv4_lpm table :

  action ipv4_forward(macAddr_t dstMac, egressSpec_t port)  {	
        standard_metadata.egress_spec = port;	
        hdr.ethernet.srcMac = hdr.ethernet.dstMac;
        hdr.ethernet.dstMac = dstMac;
        hdr.ipv4.ttl = hdr.ipv4.ttl - 1;
    }
    table ipv4_lpm {
        key = {
            hdr.ipv4.srcAddr: exact;
            hdr.ipv4.dstAddr: exact;
        }
        actions = {
            ipv4_forward;
            drop;
            NoAction;
        }
        size = 1024;
        default_action = drop();
    }

when running the controller program it gives the following error:
Installed P4 Program using SetForardingPipelineConfig on s1
Traceback (most recent call last):
  File "./P4_controller_SYN.py", line 115, in <module>
    main(args.p4info, args.bmv2_json)
  File "./P4_controller_SYN.py", line 76, in main
    writeACKReply(p4info_helper, sw=s1, in_port=1, src_ip_addr="10.0.1.1", dst_ip_addr="10.0.2.2", dst_eth_addr="08:00:00:00:02:22")
  File "./P4_controller_SYN.py", line 31, in writeACKReply
    "port": SWITCH_TO_HOST_PORT
  File "/home/safaa/tuto_Andy/tutorials/exercises/dmd/../../utils/p4runtime_lib/helper.py", line 176, in buildTableEntry
    for match_field_name, value in match_fields.iteritems()
  File "/home/safaa/tuto_Andy/tutorials/exercises/dmd/../../utils/p4runtime_lib/helper.py", line 102, in get_match_field_pb
    exact.value = encode(value, bitwidth)
  File "/home/safaa/tuto_Andy/tutorials/exercises/dmd/../../utils/p4runtime_lib/convert.py", line 77, in encode
    raise Exception("Encoding objects of %r is not supported" % type(x))
Exception: Encoding objects of <type 'tuple'> is not supported

Please how can I fix that

**Comment by antoninbas** [comment]
You changed the table definition and you are now using exact matches instead of lpm matches. As a result, you should no longer be providing a tuple `(<match prefix>, <match prefix length>)`, but a single `<match value>`. Unfortunately there does not seem to be available documentation for that API, so you will need to figure out correct usage by looking at the code and the examples.

Maybe try with that instead and iterate from there if you run into any other issue:
```
    table_entry = p4info_helper.buildTableEntry(
        table_name="MyIngress.ipv4_lpm",
        match_fields={
            "hdr.ipv4.srcAddr": src_ip_addr,
            "hdr.ipv4.dstAddr": dst_ip_addr,
        },
        action_name="MyIngress.ipv4_forward",
        action_params={
            "hdr.ethernet.dstMac": dst_eth_addr,
	    "port": SWITCH_TO_HOST_PORT
        })
```

**Comment by antoninbas** [comment]
By the way, leaving the name as `"MyIngress.ipv4_lpm"` when you no longer have any lpm match is very confusing...

**Comment by Safaamahrach** [comment]
Yes it's ok 
thanks
