### ISSUE TITLE
condition hd4.ipv4.isValid() is false 

### ISSUE THREAD

**Issue by haseebnaseem** [p4lang/tutorials#34]
I am trying to run the solution of mri. hosts fail to ping each other. switch log says  condition hd4.ipv4.isValid() is false. What could be the issue?

**Comment by antoninbas** [comment]
Nobody said the hosts where supposed to be able to ping each other. Does it say so in the README?
AFAIK there is only L3 connectivity in one direction, so ping is not going to work. That's not the point of the exercise anyway. If you want to run ping, feel free to modify the CLI commands and possibly the P4 program.
