### ISSUE TITLE
Tutorial - MRI

### ISSUE THREAD

**Issue by leandrocalmeida** [p4lang/tutorials#340]
Hello,

First, thanks for these tutorials.

I have a question about MRI exercise. In fact, the value stored in "qdeph" is what?  The number of packets? The number of bytes? The size of congestion?

**Comment by jafingerhut** [comment]
The comment in mri.p4 that I see in the master branch of this repository suggests storing the value `standard_metadata.deq_qdepth` into the qdepth variable.

If you look in this file of documentation about the v1model architecture: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

and search for occurrences of "qdepth", it says:

"deq_qdepth: the depth of queue when the packet was dequeued, in units of number of packets (not the total size of packets)."

There are other P4 implementations that make other values available, e.g. the total depth of the queue in units of bytes, or something more close approximately bytes like "cells".  Check the documentation of your particular P4 implementation to find out what it provides.  This is not standardized across implementations.

**Comment by leandrocalmeida** [comment]
Andy, thanks fo help me.
