### ISSUE TITLE
BMv2 Queues: independent from qdisc?

### ISSUE THREAD

**Issue by shahzad46** [p4lang/tutorials#343]
Hello folks,
I am trying to modify the current ECN exercise from the tutorials. I am trying to see the effects of different queue sizes for BBR and CUBIC algorithms. I am confused about one thing here. Are the BMv2 queues independent from tc qdisc set limit for the same link? E.g. if we run the ECN exercise as it is, the BMv2 queue size is 64 by default for all output ports but when I check the link qdisc (`tc -s qdisc show`) I can see that the queue limit set here is 1000. So my question is, are these two queues independent from each other?
Are packets queued in each buffer sequentially?
This is important because it is affecting BBR's performance.

**Comment by jafingerhut** [comment]
I have seen some experiment results where if you put a rate limit on the links created by Mininet between virtual switches, such a rate-limited link has its own packet buffer that is completely outside of the simple_switch process, and can definitely affect the overall behavior of the network performance-wise.

If you want the links between switches to behave like rate-limited links and no internal buffers, then I think one way to achieve that is to rate-limit the queues inside of simple_switch, such that they do not send faster than the desired rate to the inter-switch links.

**Comment by shahzad46** [comment]
Thanks for the quick reply Andy. 
If we have agreed that the queues are independent then it brings up some other questions like what about the ECN mechanism, as we know a p4 program running on the simple_switch marks packets based on the internal queues of the switch. So in that case, the packets are marked internally just to be put into the outer queue (tc qdisc)? Doesn't that beat the purpose of having ECN in the first place?
About your suggestion, I think it is not suitable in my case (ecn) and I am also not sure how I can match the rates by setting the queue rate in the switch. Because the queue rate is set in the form of packets per second (pps). E.g. If tc link --> rate: 1Gbit, limit: 1000packets. How many pps am I supposed of set, to match this link?

**Comment by jafingerhut** [comment]
I am not aware of any mechanism in simple_switch to set a queue rate or link rate to some number of bits per second, only to some number of packets per second.

If most of the packets traversing a link during some experiment were the same size, e.g. the default Ethernet MTU of 1500 bytes, you could set a packet rate on simple_switch's queue that when multiplied by 1500 bytes, was equal to the bits/sec of the link you wanted to simulate.  Not very satisfying, I suspect, but the best I know how to do at the moment.

**Comment by jnfoster** [comment]
Closing this issue as it seems to be addressed.

**Comment by jafingerhut** [comment]
Oh, another possibility I have never tried, but perhaps there is a way in the rate-limited links between two emulated devices to set a rate limit, and also make the 'buffer size' of the link very small, e.g. one or two MTU-sized packets.  That is still not exactly the same as a constant bit rate link, but significantly closer than the default buffer size of a rate-limited link, which I would guess is significantly larger than that.
