### ISSUE TITLE
Failed to Vagrant up vm

### ISSUE THREAD

**Issue by LaironSk** [p4lang/tutorials#344]
Hi, I'm having issues in installing the VM. I attempted to fix the problem many times.

I'm using a Window 10(I already tried to unable Hyper-V and it got only worse), I have enabled the virtualization(I have an Intel i7).

Here is the problem:
![image](https://user-images.githubusercontent.com/63989157/79708659-6c2fd200-8296-11ea-9ec8-7b14ca094b3a.png)

I beg you all to help me.

**Comment by LaironSk** [comment]
Btw, in the VM the error that appears is this: 
![image](https://user-images.githubusercontent.com/63989157/79783608-4a2a6400-8317-11ea-8c0d-ebac1cbc9548.png)

**Comment by jafingerhut** [comment]
I have not seen that particular error before, but I have a strong suspicion that somehow the VirtualBox software is either not installed correctly, is an old/wrong version for your host OS, or has bad options configured for it for the host/guest VM combination you are attempting to use.

Can you create an Ubuntu 16.04 or 18.04 VM guest image and boot it up successfully on your system using VirtualBox, and use it successfully without a similar kind of error occurring?

If you cannot do that, then the problem would seem to be something to do with your host system, not with the vagrant scripts in this repository.

If so, one option is to do that, then run the bash script described at the following link to install all of the open source P4 development tools: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by andre91998** [comment]
When I run "vagrant up" the VM installs, but no GUI... Does anyone have any idea what could be happening?

Here is the end of the install log:

![image](https://user-images.githubusercontent.com/30624044/81443832-03b47200-912b-11ea-8e3e-c3e58464b2de.png)

**Comment by jafingerhut** [comment]
The last 10 lines or so show it attempting to execute the command `git clone https://github.com/google/protobuf.git` and then that fails, with an error message that I am not deeply familiar with.

I do that `git clone` command about 3 to 5 times per month on various machines of my own, and it usually succeeds.  Maybe check that your Internet connection is stable throughout the multi-hour `vagrant up` process, and try again?

**Comment by jafingerhut** [comment]
Another thing that can go wrong: If your host machine runs out of disk space during `vagrant up`, it can fail in any number of spectacular and confusing ways.  I do not know yet exactly how much space it will require on the host machine, and it might even vary slightly from host OS to host OS, but on my Mac I believe having at least 15 Gbytes of free disk space before running `vagrant up` is advisable.  5 Gbytes or less will almost certainly fail on any host OS.  10 Gbytes is on the edge of maybe it will work, maybe it will not -- I would guess no
