### ISSUE TITLE
Can't use log_msg() & Debugging

### ISSUE THREAD

**Issue by MichaelHoe** [p4lang/tutorials#346]
Hi everyone,

I came across log_msg() in https://github.com/p4lang/behavioral-model/commit/51f58614a0dbbe8d6381de0ee31a99aec644b007 and wanted to incooperate into my tutorial-program for debugging-purposes.
Nevertheless it doesn't work.
Usage: `log_msg("foo");` like in https://github.com/p4lang/behavioral-model/commit/51f58614a0dbbe8d6381de0ee31a99aec644b007
Is there something I am missing or is it just not possible?

Is there any other way to debug a program? I also didn't manage to get the debugger working.
Concerning the debugger I don't know there to pass the `--debugger` command within the tutorial enviroment.

**Comment by jafingerhut** [comment]
log_msg was a feature added fairly recently to p4c and behavioral-model code, about Nov 2019 if I remember correctly.  What versions of p4c and simple_switch are you using?  e.g. what is the output of `p4c --version` and `simple_switch --version` commands on your system?

If you have more recent versions that should have the feature, in what way does it not work?  Compile time error?  If no compile time error, but no messages, you need to use at least one of these sets of options when running `simple_switch` to enable log messages:

`--log-console` Your log messages, and many others besides that can be very useful for debugging, appear on the standard output where you ran `simple_switch`

`--log-file filename --log-flush` Log messages will be written to the file `filename` (perhaps with a suffix like `.txt` or `.log` appended to it -- I have forgotten).

**Comment by MichaelHoe** [comment]
Results:
`p4c --version:
p4c 1.1.0-rcl (SHA: 8742052)`
`simple_switch --version:
1.13.0-b447ac4c`

Yes I have logging enabled and it is already helping a lot, but it is still not enough for me. :/
I also came across debugging-tables and will give them a try: https://github.com/nsg-ethz/p4-learning/tree/master/examples/debugging_table

**Comment by jafingerhut** [comment]
Can you clarify what you mean when you say "it doesn't work"?

Do you get a compile-time error when you have a program that calls `log_msg`, or does it compile without errors?

**Comment by MichaelHoe** [comment]
Sorry for not specifying.

I am having this error at compile-time:
`p4src/basic.p4(254): [--Werror=not-found] error: log_msg: Not found declaration
        log_msg("foo");
        ^^^^^^^
Compilation Error
`

**Comment by jafingerhut** [comment]
The version of p4c that you mention earlier:

p4c --version: p4c 1.1.0-rcl (SHA: 8742052)

is from September 2018, which is before log_msg support was implemented.  Similarly for the version of simple_switch that you gave:

simple_switch --version: 1.13.0-b447ac4c

You need p4c and simple_switch built from more recent versions of their source code in order for log_msg to work.

The 'debug tables' approach will work, if you would prefer not to install more recent versions of p4c and simple_switch.  You can find a brief description of what I call 'debug tables' here: https://github.com/jafingerhut/p4-guide/blob/e4b929e22be266cc2a10abf1d078e80c8c01af87/v1model-special-ops/README.md

**Comment by MichaelHoe** [comment]
Okay, now it's clear to me. I thought my bmv2- & p4c-version would be sufficient.

Thank you very much.
