### ISSUE TITLE
Unable to use link_monitor

### ISSUE THREAD

**Issue by ls760008979** [p4lang/tutorials#347]
I have successfully installed dependencies and do some exercises before, but when i try the exercises of link_monitor recently, it report error like this:
![image](https://user-images.githubusercontent.com/30166591/80276000-f30e0000-8717-11ea-9606-9eed21cae16f.png)
How to solve the issue ?

**Comment by jnfoster** [comment]
It sounds like you have an out-of-date version of the compiler.

What does
```
p4c-bm2-ss --version
```
return?

**Comment by ls760008979** [comment]
> It sounds like you have an out-of-date version of the compiler.
> 
> What does
> 
> ```
> p4c-bm2-ss --version
> ```
> 
> return?

it returns version 0.0.5

**Comment by jnfoster** [comment]
That is very old (I am on 1.2.0.)

It should work if you upgrade to a more recent version.
