### ISSUE TITLE
what happend when call "h1 ping h2"？

### ISSUE THREAD

**Issue by nosugerhcc** [p4lang/tutorials#349]
Hello, I am doing p4runtime exercise. It adds a header type called "myTunnel" in advanced_tunnel.p4,but when calls "h1 ping h2" in CLI,it can parse and get the Counter number.Howerver, in "basic_tunnel" exercise, it shows that it is necessary to create a new Class names myTunnel_header,and call bind() fuction.
Thank you so much if you can help me out！

**Comment by jnfoster** [comment]
This is the repository for tracking technical issues in the P4 tutorial source code. I don't see a question or issue here?

You might try on the [p4-dev](http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) list or the [P4 Slack](https://p4-lang.slack.com/join/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
