### ISSUE TITLE
You requested P4 v1.1 but the corresponding p4-hlir package does not seem to be installed

### ISSUE THREAD

**Issue by cxy910420** [p4lang/tutorials#35]
When I run run_demo.sh in p4v1_1 simple router folder, it gives me "You requested P4 v1.1 but the corresponding p4-hlir package does not seem to be installed". I am pretty sure I have installed p4-hlir because I have successfully setup.py in p4-hlir folder. Can someone help me with that? 

Here is the full output error message when I run run_demo.sh:

You requested P4 v1.1 but the corresponding p4-hlir package does not seem to be installed
*** Creating network
*** Adding hosts:
h1 h2 
*** Adding switches:
Invalid JSON file.

**Comment by antoninbas** [comment]
Being able to compile P4 v1.1 programs require something more than the regular p4-hlir package. In particular you need to check out this branch (https://github.com/p4lang/p4-hlir/tree/p4v1.1) and install it. You can refer to this old email to the p4-dev mailing list for more details: http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-February/000179.html
That being said, P4 v1.1 has been deprecated and is not even maintained anymore. We recommend that you write your programs in P4_14 (P4 v1.0) which has been out for a while and is well-supported, or in the new version of the language, P4_16, which was officially released a couple weeks ago.
