### ISSUE TITLE
Provide pre-built VirtualBox VMs of tutorials for download?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/tutorials#353]
I know that there are some VMs available for download of previous tutorials given based upon the contents of this repo, but they seem to typically use someone's personal storage space, or explicitly temporarily set up during the tutorial, then they disappear.

Would p4.org and/or its parent organization have storage space available for 100 Gbytes or so, enough for several recent versions of pre-built VMs from this tutorials repo, e.g. somewhere around two to four versions built per year from different versions of P4 dev tools source code?

I know there are not a huge number of issues regarding failures to install these things, but having a stable place to link to downloadable images could quickly resolve some of those, it seems.

**Comment by jnfoster** [comment]
This is an excellent suggestion. We could do a proper release of tutorial versions and park a VM somewhere. 

Let me inquire about where that would best be...

**Comment by jafingerhut** [comment]
I have been creating pre-build VMs for several months now, currently hosting them using my personal Google Drive account which has a limit of 100 GBytes of storage, enough for the latest 12 monthly VMs and more, even for a free account.  If there is a desire to host them in a place that ONF/P4.org manages centrally, I'm happy to copy the files there.
