### ISSUE TITLE
Access to invalid header in ecn.p4

### ISSUE THREAD

**Issue by nouredd2** [p4lang/tutorials#356]
In the solution for `ecn.p4`, couldn't line 133, namely
```p4
if (hdr.ipv4.ecn == 1 || hdr.ipv4.ecn == 2){
```
cause access to an invalid header if the received packet is not an IP packet (`ethtype != 0x0800`)? 

If I understand correctly, the packet would not trigger a lookup in `ipv4_lpm` because the IP header is invalid. However, in the `egress` pipeline, no such check is performed and the ecn bits are read from what might be an invalid packet.

**Comment by jnfoster** [comment]
These exercises are intended to introduce various features of P4 in the simplest possible way. Note that the `send.py` packet only ever sends IPv4 packets. 

To turn this into an industrial-grade P4 program, one would want to extend it handles all packets (and also handle checksums, etc.) But that would make the program more complicated...

If you have an idea for how to improve it, we welcome PRs.
