### ISSUE TITLE
"ReadRegisters" function in python

### ISSUE THREAD

**Issue by brunofraga-rs** [p4lang/tutorials#357]
Hello, everyone.

I'm new in p4 language and I was wondering if anyone could give me a tip.

On p4runtime_lib we have **switch.py** which presents the functions **ReadTableEntries** and **ReadCounters** but I didn't find anywhere else a function for the controller to read data plane registers from the switches.

Is there such a library that does it in python ? I mean, did someone implement a .py code defining a "ReadRegisters" function ?

Thanks in advance.
Bruno Fraga

**Comment by antoninbas** [comment]
This is not implemented yet in the P4Runtime server reference server implementation. There is a Github issue to track this (https://github.com/p4lang/PI/issues/376), but no one has had the time to work on this yet.
