### ISSUE TITLE
P4Runtime

### ISSUE THREAD

**Issue by suniljha555** [p4lang/tutorials#358]
Is there any P4_16 implementation/tutorials which shows the packet_in from the switch and then controller receives packet ( packet_out) and pushes appropriate rules using P4Runtime for v1model switch?(i.e, both way communication)

**Comment by antoninbas** [comment]
I don't think there is any example in this repo, but there is an interesting discussion here about how to do this in Python: https://github.com/p4lang/p4runtime-shell/issues/26. 

If you want a complete stand-alone example, you can look here: https://github.com/p4lang/PI/tree/master/proto/demo_grpc. It is a toy L3 P4Runtime controller written in C++ and it implements ARP using PacketIn / PacketOut.
