### ISSUE TITLE
Get minimum value from registers

### ISSUE THREAD

**Issue by suniljha555** [p4lang/tutorials#359]
I have some data in registers(floating numbers), i want to get minimum value among it(and it's index in the register).Is there any way to do this using registers as P4 doesn't support loops. And if we can't use register is there any other anyone can suggest which allows to store certain values and then get minimum value from it?

Thank You

**Comment by jnfoster** [comment]
P4 also doesn't support floating point...?

As best I know, you can either retrieve all of the registers from the P4Runtime. Or you could extend the data plane program to maintain the minimum in a separate 1-element register.
