### ISSUE TITLE
Create Mininet limited hosts

### ISSUE THREAD

**Issue by SanaaComp** [p4lang/tutorials#360]
Can I create a Mininet limited host (CPULimitedHost which can use `setCPUFrac()` function) by editing the topology json file? Something like :
```
        "h1": {"ip": "10.0.1.1/24", "mac": "08:00:00:00:01:11", "CPULimitedHost":"true"
               "commands":["route add default gw 10.0.1.10 dev eth0",
                           "arp -i eth0 -s 10.0.1.10 08:00:00:00:01:00"]},
```
Is it possible?

**Comment by jnfoster** [comment]
I think the current code simply passes all parameters to the Mininet `Host` class.

You can see how the `topology.json` file is loaded here: 
https://github.com/p4lang/tutorials/blob/master/utils/run_exercise.py#L169

And how the P4 hosts are set up here:
https://github.com/p4lang/tutorials/blob/master/utils/mininet/p4_mininet.py#L26
