### ISSUE TITLE
Merge Parser code

### ISSUE THREAD

**Issue by Yvan6492** [p4lang/tutorials#361]
Hello, 

i'm trying to merge this two codes in the parser of my code : 

 state parse_ipv4 {
        packet.extract(hdr.ipv4);
        transition select(hdr.ipv4.protocol) {
            6: parse_tcp;
            default: accept;
        }
    }

With 

 state parse_ipv4 {
        packet.extract(hdr.ipv4);
        verify(hdr.ipv4.ihl >= 5, error.IPHeaderTooShort);
        transition select(hdr.ipv4.ihl) {
            5             : accept;
            default       : parse_ipv4_option;
        }
    }

I didn't find a solution, the topology refuse multiple transition select on the same parse_ipv4, i tried to do transition select (hdr.ipv4.ihl,hdr.ipv4.protocol) {
}

I have no more errors, but the argument after are bad. I think i'm missing something on the logic on the parser selection.

I'm searching on this document : https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html#sec-select
Actually a solution, but if someone can help me it could be nice.
Regards,

**Comment by jnfoster** [comment]
Hi. Happy to try to help if I can understand what it is you want to do. The statement "trying to merge this two codes" is rather vague.

Can you precisely describe what you want the parser to do? Is it to parse IPv4 with IP Options and then proceed to TCP? And are you happy to do the merging by hand, or do you want a compiler to do it for you?

**Comment by Yvan6492** [comment]
Hi, Thanks for your answer. 

I'm trying to merge the code in the tutorials Load_balancing and MRI in the exercises.

https://github.com/p4lang/tutorials/blob/master/exercises/load_balance/solution/load_balance.p4 

https://github.com/p4lang/tutorials/blob/master/exercises/mri/solution/mri.p4

I merge the two codes but, i have one problem. I can't use load_balance and mri in the same time. I tried to debug this and i found the problem come from the parser parse_ipv4. I'm trying to coexist the two for use load balance and mri in the same time.

I'm begineer in programmation, sorry if my question seems stupid.

Regards,

**Comment by jnfoster** [comment]
Would something like this work?

```p4
    state parse_ipv4 {
        packet.extract(hdr.ipv4);
        verify(hdr.ipv4.ihl >= 5, error.IPHeaderTooShort);
        transition select(hdr.ipv4.ihl) {
            5 : dispatch_ipv4_protocol;
            default : parse_ipv4_option;
    }

    state parse_ipv4_option {
        packet.extract(hdr.ipv4_option);
        transition select(hdr.ipv4_option.option) {
            IPV4_OPTION_MRI: parse_mri;
            default: dispatch_ipv4_protocol;
        }
    }

    state parse_mri {
        packet.extract(hdr.mri);
        meta.parser_metadata.remaining = hdr.mri.count;
        transition select(meta.parser_metadata.remaining) {
            0 : dispatch_ipv4_protocol;
            default: parse_swtrace;
        }
    }

    state parse_swtrace {
        packet.extract(hdr.swtraces.next);
        meta.parser_metadata.remaining = meta.parser_metadata.remaining  - 1;
        transition select(meta.parser_metadata.remaining) {
            0 : dispatch_ipv4_protocol;
            default: parse_swtrace;
        }
    } 
   
    state dispatch_ipv4_protocol {
        transition select(hdr.ipv4.protocol) {
            6: parse_tcp;
           default: accept;
        }
    }
```
I've basically sequentially composed the state machines -- by hand -- so we do IPv4, IPv4 options, then TCP.

**Comment by Yvan6492** [comment]
Yes, it works thank you. I understood the problem but didn't know how to fix it, the sequentially is exactly what i need. Thank you very much

**Comment by jnfoster** [comment]
Glad I could help.
