### ISSUE TITLE
Run P4Runtime through Python 3

### ISSUE THREAD

**Issue by j91157j91157** [p4lang/tutorials#362]
Dear P4-Community, 
I have questions about the P4Runtime exercise of this repository.

I want to ask if it is possible to execute "mycontroller.py" using Python 3?

Actually, I tried to modify the import path to support the format of Python 3, also use pip3 to install related modules (e.g. grpcio, googleapis-common-protos), but now I am having difficulties, it seems to be related to the encoding of BMv2:

```python-traceback
~/tutorials/exercises/p4runtime$ sudo python3 mycontroller.py 
Traceback (most recent call last):
  File "mycontroller.py", line 232, in <module>
    main(args.p4info, args.bmv2_json)
  File "mycontroller.py", line 180, in main
    bmv2_json_file_path=bmv2_file_path)
  File "/tutorials/utils/p4runtime_lib/switch.py", line 78, in SetForwardingPipelineConfig
    device_config = self.buildDeviceConfig(**kwargs)
  File "/tutorials/utils/p4runtime_lib/bmv2.py", line 30, in buildDeviceConfig
    return buildDeviceConfig(**kwargs)
  File "/tutorials/utils/p4runtime_lib/bmv2.py", line 24, in buildDeviceConfig
    device_config.device_data = f.read()
TypeError: '{\n  "header_types" : [\n    {\n      "name" : "scalars_0",\n      "id" : 0,\n      "fields" : [\n  has type str, but expected one of: bytes
```

When reading "advanced_tunnel.json",  found that the field after "fields" has not been converted to bytes, this confuses me. Does anyone have an idea about this problem?

**Comment by j91157j91157** [comment]
New progress!

In file "/tutorials/utils/p4runtime_lib/bmv2.py", line 23, in buildDeviceConfig
Modified to the following syntax:
`with open(bmv2_json_file_path, "rb") as f:`

In this way, it can be converted into bytes normally when reading "advanced_tunnel.json"

If you omit the code from line 187 to line 192 in "mycontroller.py".
In other words, do not write any rules and behaviors.
Executing P4Runtime with Python 3 is feasible:
```
~/tutorials/exercises/p4runtime$ sudo python3 mycontroller.py 
Installed P4 Program using SetForwardingPipelineConfig on s1
Installed P4 Program using SetForwardingPipelineConfig on s2

----- Reading tables rules for s1 -----

----- Reading tables rules for s2 -----

----- Reading tunnel counters -----
s1 MyIngress.ingressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.egressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.ingressTunnelCounter 200: 0 packets (0 bytes)
s1 MyIngress.egressTunnelCounter 200: 0 packets (0 bytes)

----- Reading tunnel counters -----
s1 MyIngress.ingressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.egressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.ingressTunnelCounter 200: 0 packets (0 bytes)
s1 MyIngress.egressTunnelCounter 200: 0 packets (0 bytes)
```

**Comment by j91157j91157** [comment]
Unfortunately, this is not what we expected, we need to write some rules.
When I do not ignore lines 187 to 192 in "mycontroller.py"

e.g. 
bit<16> dst_id (the value is integer 100), the following happens:
```
~/tutorials/exercises/p4runtime$ sudo python3 mycontroller.py 
Installed P4 Program using SetForwardingPipelineConfig on s1
Installed P4 Program using SetForwardingPipelineConfig on s2
<class 'int'>
100
Convert the entered valus to hexadecimal:  b'0064'
Length after encoding:  4
Length of the header 2
Traceback (most recent call last):
  File "mycontroller.py", line 232, in <module>
    main(args.p4info, args.bmv2_json)
  File "mycontroller.py", line 188, in main
    dst_eth_addr="08:00:00:00:02:22", dst_ip_addr="10.0.2.2")
  File "mycontroller.py", line 48, in writeTunnelRules
    "dst_id": tunnel_id,
  File "/home/test/tutorials/exercises/p4runtime/../../utils/p4runtime_lib/helper.py", line 189, in buildTableEntry
    for field_name, value in list(action_params.items())
  File "/home/test/tutorials/exercises/p4runtime/../../utils/p4runtime_lib/helper.py", line 189, in <listcomp>
    for field_name, value in list(action_params.items())
  File "/home/test/tutorials/exercises/p4runtime/../../utils/p4runtime_lib/helper.py", line 158, in get_action_param_pb
    p4runtime_param.value = encode(value, p4info_param.bitwidth)
  File "/home/test/tutorials/exercises/p4runtime/../../utils/p4runtime_lib/convert.py", line 82, in encode
    assert(len(encoded_bytes) == byte_len)
AssertionError
```

We can see in the "assert" function, the length of "encoded_bytes" is not equal to "byte_len", which is unreasonable.

This is my modified code in file "tutorials/utils/p4runtime_lib/convert.py" (show only lines 47 to 83):
```
def bitwidthToBytes(bitwidth):
    return int(math.ceil(bitwidth / 8.0))

def encodeNum(number, bitwidth):
    byte_len = bitwidthToBytes(bitwidth)
    num_str = '%x' % number
    print (number)
    if number >= 2 ** bitwidth:
        raise Exception("Number, %d, does not fit in %d bits" % (number, bitwidth))
    return ('0' * (byte_len * 2 - len(num_str)) + num_str).encode()#.decode('hex')

def decodeNum(encoded_number):
    return int(encoded_number.encode('hex'), 16)

def encode(x, bitwidth):
    'Tries to infer the type of `x` and encode it'
    byte_len = bitwidthToBytes(bitwidth)
    if (type(x) == list or type(x) == tuple) and len(x) == 1:
        x = x[0]
    encoded_bytes = None
    if type(x) == str:
        if matchesMac(x):
            encoded_bytes = encodeMac(x)
        elif matchesIPv4(x):
            encoded_bytes = encodeIPv4(x)
        else:
            # Assume that the string is already encoded
            encoded_bytes = x
    elif type(x) == int:
        encoded_bytes = encodeNum(x, bitwidth)
        print ("Convert the entered valus to hexadecimal: ", encoded_bytes)
        print ("Length after encoding: ", len(encoded_bytes))
        print ("Length of the header", byte_len)
    else:
        raise Exception("Encoding objects of %r is not supported" % type(x))
    assert(len(encoded_bytes) == byte_len)
    return encoded_bytes
```

I think this already involves P4Runtime low-level coding. Does anyone have other ideas about this situation?

**Comment by jafingerhut** [comment]
I do not have specific coding suggestions for you in this situation, but I would warn you that a significant amount of Python code in open source P4 tools is Python2.

We realize that this is an undesirable position to be in, given official support for Python2 was discontinued starting in January 2020.  Despite the existence of tools like `2to3` in translating such code to Python3, there are things that it does not handle automatically, and Python's dynamic nature often leads to situations where having high assurance that the translated code is correct, requires running tests that execute most or all branches of the new code.

If you are truly interested in getting this code to work with Python3, I suspect that either making the same Python code work with both Python2 and Python3, or having completely separate source files for Python3, would be preferable in the future.

**Comment by jnfoster** [comment]
I've been tidying the issues on this repository. I'll leave this open for now, but I suspect this will sit until someone decides to take it on.

**Comment by j91157j91157** [comment]
@jafingerhut Thank you for taking the time to read my question. In response to this issue, if there is new progress, I will report here.

@jnfoster Got it, thanks for your help.

**Comment by blp** [comment]
I can't figure out how to reasonably make the P4Runtime stuff work on the newest Fedora, which has only the barest Python 2 support. Notably, it doesn't come with a pip2 RPM, which means that it's difficult to install grpc for python2. This kind of bit-rot is only going to get worse over time.

**Comment by jafingerhut** [comment]
For those interested, I have a version of a bash script that starting from an unmodified Ubuntu 20.04 Desktop Linux installation for the amd64 architecture, seems to successfully build all open source P4 development tools, and with a small patch applied to the main branch of this p4lang/tutorials repository, can install the necessary table entries to get pings to work.

How to run that script is described here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md.  It is the install-p4dev-v4.sh script that tries to avoid using Python2.  The older install-p4dev-v2.sh script doesn't work on Ubuntu 20.04, and relies on Python2 being already installed on the system when it begins running.

As mentioned in that README, the patch that enabled me to get at least the basic tutorial exercise working was this one: https://github.com/jafingerhut/p4-guide/blob/master/bin/patches/tutorials-python3-changes1.patch

I could try creating a PR for this repository with those changes, but note that if this were done, people using the latest version of code in this p4lang/tutorials repository might not work unless they use an installation script like my install-p4dev-v4.sh that is careful to add all of the needed Python3 modules, and to build the open source p4 dev tools with Python3 support.  They are getting closer to doing that "out of the box" in their latest versions as of 2021, but I'm not sure whether they are completely there yet, following the instructions in their README files.

**Comment by jnfoster** [comment]
I think it would be great to update the scripts for this repository *and*
to host a pre-built VM.

-N

**Comment by jafingerhut** [comment]
I created a PR with one version of some potential changes to consider in the direction of this issue.  They likely need further changes before they should be merged in, if ever: https://github.com/p4lang/tutorials/pull/403

**Comment by jafingerhut** [comment]
#403 has been merged in some time ago, and creates an Ubuntu 20.04 Linux VM that has no Python2 installed at all, only Python3.  Closing this issue.
