### ISSUE TITLE
Bit slicing from header field

### ISSUE THREAD

**Issue by suniljha555** [p4lang/tutorials#363]
I am trying to implement some program where at each switch i need some part of a field of header.
`header source{
    bit<72> ports;
    bit<8> start;
    bit<16> etherType;
}`
At each switch i need different part of bitstring ports. For eg. at switch 1 i need ports[start:start+5], at switch 2 ports[start+5:start+10] and so on. Start value in header will be updated at each switch(like ttl in routers). But as these indices needs to be compile time constants, therefore i cannot code like this. Can someone please suggest if there is any other way of doing this.

**Comment by jnfoster** [comment]
This is the repository for tracking technical issues in the P4 tutorial source code.

Questions of this form should be asked somewhere else. For example, you could try on the [p4-dev](http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) list or the [P4 Slack](https://p4-lang.slack.com/join/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
