### ISSUE TITLE
Interested in having multiple 'vm' directories with 'vagrant up' scripts for major Ubuntu versions?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/tutorials#364]
The current vm directory in this repo has scripts that create an Ubuntu 16.04 VM, with open source P4 tools built from source code dated in 2019-Aug.

I have proposed changes for that to update to open source P4 tools for 2020-May, as well as a separate directory that can do similar for Ubuntu 18.04 Linux, which has a few small changes required from the Ubuntu 16.04 scripts.

If these would be of interest, would it be acceptable to have separate directories for major Ubuntu OS versions, given that they are likely to continue to have at least small differences between them, and perhaps more as Ubuntu 20.04 if it is supported in future?

e.g. instead of the existing 'vm' directory, there could be 'vm-ubuntu-16.04' and 'vm-ubuntu-18.04' directories.  I would not expect there to be more than 2 or 3 of these at one time, since eventually the older ones would be removed (still accessible in git).

**Comment by jnfoster** [comment]
We could certainly do that. To reduce the maintenance load, also releasing pre-built binaries (as you suggested elsewhere) would be good...

**Comment by mchoudary** [comment]
Definitely of interest. I am spending quite some time trying to make the scripts work on a vm Ubuntu 16.04 installation, but would also like to have this working on my Ubuntu 18 machine.

**Comment by jafingerhut** [comment]
There has been a working vm-ubuntu-20.04 directory for several months now, tested monthly.  Closing this issue.
