### ISSUE TITLE
Questions about the queueing_metadata header

### ISSUE THREAD

**Issue by ls760008979** [p4lang/tutorials#365]
I want to know why the field "enq_timestamp" is only 32 bits rather than 48 bits? whether the clock is the same as for "ingress_global_timestamp" ? and the clock of  "ingress_global_timestamp" wouldn't be set to 0 every time the switch starts as saying in this document: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by jafingerhut** [comment]
"I want to know why the field "enq_timestamp" is only 32 bits rather than 48 bits?"

I do not know.  It was defined that way with this commit in May 2017 by @hanw.  Maybe Han remembers the reason for this choice of bit width for `enq_timestamp` in v1model?  I would not be surprised if it was made to match the bit width of a similar field from another P4 architecture somewhere.

"whether the clock is the same as for "ingress_global_timestamp" ?"

I am nearly certain the answer is "yes".  Have you tried using a debug table to show the value of these fields for a few dozen packets being passed through simple_switch, to see if this is true?  It should be quite easy to confirm or deny that way, experimentally.

"and the clock of "ingress_global_timestamp" wouldn't be set to 0 every time the switch starts as saying in this document: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md"

That is not a question, and I do not know what you are claiming.  As far as I know, the statement in that documentation is correct -- all timestamps begin at 0 near the time that a simple_switch process starts.  Do you have some evidence that indicates this is not so?

**Comment by ls760008979** [comment]
> "I want to know why the field "enq_timestamp" is only 32 bits rather than 48 bits?"
> 
> I do not know. It was defined that way with this commit in May 2017 by @hanw. Maybe Han remembers the reason for this choice of bit width for `enq_timestamp` in v1model? I would not be surprised if it was made to match the bit width of a similar field from another P4 architecture somewhere.
> 
> "whether the clock is the same as for "ingress_global_timestamp" ?"
> 
> I am nearly certain the answer is "yes". Have you tried using a debug table to show the value of these fields for a few dozen packets being passed through simple_switch, to see if this is true? It should be quite easy to confirm or deny that way, experimentally.
> 
> "and the clock of "ingress_global_timestamp" wouldn't be set to 0 every time the switch starts as saying in this document: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md"
> 
> That is not a question, and I do not know what you are claiming. As far as I know, the statement in that documentation is correct -- all timestamps begin at 0 near the time that a simple_switch process starts. Do you have some evidence that indicates this is not so?

When i doing the exercise of link-monitor in the tutorials, i get the field enq_timestamp and ingress_global_timestamp directly from the standard_metadata as shows in picture below
![1](https://user-images.githubusercontent.com/30166591/83734375-7c9edf00-a681-11ea-92a4-10744e3cab2f.png)
their format are not the same, nor begin at 0.

**Comment by jafingerhut** [comment]
If you have made local modifications to your version of the code, it is very easy to make a mistake in keeping the P4 header definition and the Python Scapy definition for decoding the packet headers, to match each other.  The latest master branch version of the code has this in link_monitor.p4:
```
typedef bit<48> time_t;

// .. and later ...

// The data added to the probe by each switch at each hop.
header probe_data_t {
    bit<1>    bos;
    bit<7>    swid;
    bit<8>    port;
    bit<32>   byte_cnt;
    time_t    last_time;
    time_t    cur_time;
}
```
The Python file `probe_hdr.py` contains this definition for how to decode that same header:
```
class ProbeData(Packet):
   fields_desc = [ BitField("bos", 0, 1),
                   BitField("swid", 0, 7),
                   ByteField("port", 0),
                   IntField("byte_cnt", 0),
                   BitField("last_time", 0, 48),
                   BitField("cur_time", 0, 48)]
```
If you have changed those in your code, please share what you have for those two things.  It may be that they do not match up to each other.

**Comment by ls760008979** [comment]
> If you have made local modifications to your version of the code, it is very easy to make a mistake in keeping the P4 header definition and the Python Scapy definition for decoding the packet headers, to match each other. The latest master branch version of the code has this in link_monitor.p4:
> 
> ```
> typedef bit<48> time_t;
> 
> // .. and later ...
> 
> // The data added to the probe by each switch at each hop.
> header probe_data_t {
>     bit<1>    bos;
>     bit<7>    swid;
>     bit<8>    port;
>     bit<32>   byte_cnt;
>     time_t    last_time;
>     time_t    cur_time;
> }
> ```
> 
> The Python file `probe_hdr.py` contains this definition for how to decode that same header:
> 
> ```
> class ProbeData(Packet):
>    fields_desc = [ BitField("bos", 0, 1),
>                    BitField("swid", 0, 7),
>                    ByteField("port", 0),
>                    IntField("byte_cnt", 0),
>                    BitField("last_time", 0, 48),
>                    BitField("cur_time", 0, 48)]
> ```
> 
> If you have changed those in your code, please share what you have for those two things. It may be that they do not match up to each other.

I have add some P4 header to get these fields in standard_metadata.
![2](https://user-images.githubusercontent.com/30166591/83830229-31cfa680-a717-11ea-8a88-f2d24f5cd36b.png)
![3](https://user-images.githubusercontent.com/30166591/83830242-37c58780-a717-11ea-96b6-3de3153a1876.png)
deq_delay is to get field of 'deq_timedelta'
enq_t is to get field of 'enq_timestamp'
ingress_t is to get field of 'ingress_global_timestamp', and the reason i set enq_t to 32 bits is there would be error for " cannot unify bit<32> to bit<48>"

**Comment by jafingerhut** [comment]
The order of fields in those two places should match each other, or else the Python decoding will not give you useful results.

**Comment by ls760008979** [comment]
> The order of fields in those two places should match each other, or else the Python decoding will not give you useful results.

Okay，thanks a lot! it works well.
