### ISSUE TITLE
Basic Forwarding: food for thought

### ISSUE THREAD

**Issue by andre91998** [p4lang/tutorials#366]
Has anyone been able to implement any of the "food for thought items" in the basic.p4 exercise (such as traceroute, ARP, and next hops)? I'm new to P4 and haven't been able to think of how to do so. Thanks.

**Comment by panos-ece** [comment]
Hello,
Have you made any progress with it?

**Comment by jafingerhut** [comment]
https://forum.p4.org is a good place for discussion of P4 development questions of all kinds.
