### ISSUE TITLE
P4 runtime issue- possibly sX-runtime.json error

### ISSUE THREAD

**Issue by baset-vsy** [p4lang/tutorials#367]
I just compiled a p4 program and saw the error. Can sb help?
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 383, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 199, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 304, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 276, in program_switch_p4runtime
    proto_dump_fpath=outfile)
  File "/home/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 129, in program_switch
    insertTableEntry(sw, entry, p4info_helper)
  File "/home/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 158, in insertTableEntry
    sw.WriteTableEntry(table_entry)
  File "/home/p4/tutorials/utils/p4runtime_lib/switch.py", line 101, in WriteTableEntry
    self.client_stub.Write(request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 221, in __call__
    compression=compression)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 333, in result
    raise self
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "{"created":"@1591728647.730517127","description":"Error received from peer ipv4:127.0.0.1:50053","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"","grpc_status":2}"
>
Here is my p4 code:
```
    /* -*- P4_16 -*- */
    #include <core.p4>
    #include <v1model.p4>


    /* Value Definitions */
    #define NUM_STAGES 4        // number of stages
    #define STAGE_CAPACITY 16   // size of the table
    #define WEIGHT_WIDTH 16     // size of weight feild in    DASH probe packet
    #define PORT_WIDTH 15       // size of port field in source routing packet
    #define MAX_HOPS 5          // maximum number of 
/*------- ToDo: here you can write your value definitions -------*/
    #define HASH_VAL_SIZE 16

/* Constant values */
    const bit<16> TYPE_IPV4 = 0x800;
    const bit<16> TYPE_DASH = 0x4567;    // our convention for dash packets

/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/

/* Type Definition */
    typedef bit<48> macAddr_t;
    typedef bit<32> ip4Addr_t;
    typedef bit<WEIGHT_WIDTH> weight_t;
    typedef bit<WEIGHT_WIDTH> boundary_t;
    typedef bit<PORT_WIDTH> port_t;
/*------- ToDo: here you can write your type definitions -------*/
    typedef bit<HASH_VAL_SIZE> hash_t;
/* Headers */
    header ethernet_t {
        macAddr_t dstAddr;
        macAddr_t srcAddr;
        bit<16>   etherType;
    }

    header ipv4_t {
        bit<4>    version;
        bit<4>    ihl;
        bit<8>    diffserv;
        bit<16>   totalLen;
        bit<16>   identification;
        bit<3>    flags;
        bit<13>   fragOffset;
        bit<8>    ttl;
        bit<8>    protocol;
        bit<16>   hdrChecksum;
        ip4Addr_t srcAddr;
        ip4Addr_t dstAddr;
    }

    header udp_t {
        bit<16> srcPort;
        bit<16> dstPort;
        bit<16> length_;
        bit<16> checksum;
    }

    header dash_t {
        weight_t weight;
    }

    header srcRoute_t {
       bit<1>    bos;
       port_t   port;
    }

    struct metadata {
       /*------- ToDo: here you can define your metadata -------*/
       hash_t hash;
    }

    struct headers {
        ethernet_t              ethernet;
        srcRoute_t[MAX_HOPS]    srcRoutes;
        ipv4_t                  ipv4;
        udp_t                   udp;
        dash_t                  dash;
    }

/*************************************************************************
*********************** P A R S E R  ***********************************
*************************************************************************/

/* Keep this unchanged */

    parser MyParser(packet_in packet,
                    out headers hdr,
                    inout metadata meta,
                    inout standard_metadata_t   standard_metadata) {

        state start {
           transition parse_ethernet;
        }

        state parse_ethernet {
            packet.extract(hdr.ethernet);
            transition select(hdr.ethernet.etherType) {
                TYPE_DASH : parse_dash;
                TYPE_IPV4 : parse_ipv4;
                default   : accept;
            }
        }

        state parse_dash {
            packet.extract(hdr.dash);
            transition parse_srcRouting;
        }

        state parse_srcRouting {
            packet.extract(hdr.srcRoutes.next);
            transition select(hdr.srcRoutes.last.bos) {
                1       : parse_ipv4;
                default : parse_srcRouting;
            }
        }

       state parse_ipv4 {
           packet.extract(hdr.ipv4);
           transition select(hdr.ipv4.protocol) {
               8w17: parse_udp;
               default: accept;
            }
       }

       state parse_udp {
           packet.extract(hdr.udp);
           transition accept;
       }

    }

/*************************************************************************
************   C H E C K S U M    V E R I F I C A T I O N   *************
*************************************************************************/

/* Keep this unchanged */

    control MyVerifyChecksum(inout headers hdr, inout   metadata meta) {
        apply { }
    }


/*************************************************************************
**************  I N G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

    control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    /* Registers */
        register<boundary_t>(STAGE_CAPACITY)    boundary_stage_reg;
   /* register<boundary_t>(STAGE_CAPACITY)   boundary_stage2_reg
    register<boundary_t>(STAGE_CAPACITY) boundary_stage3_reg
    register<boundary_t>(STAGE_CAPACITY) boundary_stage4_reg*/


    /* This action will drop packets */
        action drop() {
            mark_to_drop(standard_metadata);
        }
    /*------- ToDo: here you can define your actions and tables -------*/
        action srcRoute_nhop(){
	        standard_metadata.egress_spec = (bit<9>)hdr.srcRoutes[0].port;
	        hdr.srcRoutes.pop_front(1);
    }
        action write_stage(){
     boundary_stage_reg.write((bit<32>)standard_metadata.ingress_port-1,
     hdr.dash.weight);
         }
        action ipv4_forward_normal(){
	

    }
    
        action split(bit<1> isS1,bit<9> port ){
	        hash(meta.hash,HashAlgorithm.crc16,(bit<16>)0,
            {hdr.ipv4.srcAddr,hdr.ipv4.dstAddr},
            (bit<16>)30);
	        boundary_t reg1;
            boundary_stage_reg.read(reg1,0);
	        boundary_t reg2;
            boundary_stage_reg.read(reg2,1);
            boundary_t reg3;
	        boundary_stage_reg.read(reg3,2);
	        boundary_t reg4;
            boundary_stage_reg.read(reg4,3);
	        if (isS1==1){
		        if (meta.hash < reg1){
	                standard_metadata.egress_spec = 1;
		        }else if(meta.hash < reg2){ 
		            standard_metadata.egress_spec = 2;
		        }else if(meta.hash < reg3){  
		            standard_metadata.egress_spec = 3;
		        }else if(meta.hash < reg4){
		            standard_metadata.egress_spec = 4;
		        }	

	       }else{
		        standard_metadata.egress_spec = port;
	       }
	   
        } 
          
        action ipv4_forward(bit<9> port){
	        standard_metadata.egress_spec = port;
        }
    
        table switch_split{
	        key = {
	            hdr.ipv4.dstAddr: lpm;
	        }
	        actions = {
	            split;
	            drop;
	            NoAction;
	        }
	        size = 30;
	        default_action = drop();
       }


       apply {

            if (hdr.dash.isValid()){
	            if (hdr.srcRoutes[0].isValid()){
		            srcRoute_nhop();
	            }else{
		            write_stage();	
       	        }
	   
 
            }else if (hdr.ipv4.isValid()){
	            switch_split.apply();
	        }else{
	            drop();
	        }
    }
}

/*************************************************************************
****************  E G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

/* Keep this unchanged */

    control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
        apply { }
}

/*************************************************************************
*************   C H E C K S U M    C O M P U T A T I O N   **************
*************************************************************************/

/* Keep this unchanged */

    control MyComputeChecksum(inout headers hdr, inout metadata meta) {
         apply {
	         update_checksum(
	    hdr.ipv4.isValid(),
            { hdr.ipv4.version,
	      hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr },
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);
    }
}


/*************************************************************************
***********************  D E P A R S E R  *******************************
*************************************************************************/

/* Keep this unchanged */

    control MyDeparser(packet_out packet, in headers hdr) {
        apply {
            packet.emit(hdr.ethernet);
            packet.emit(hdr.dash);
            packet.emit(hdr.srcRoutes);
            packet.emit(hdr.ipv4);
            packet.emit(hdr.udp);
       }
}

/*************************************************************************
***********************  S W I T C H  *******************************
*************************************************************************/

/* Keep this unchanged */

//switch architecture
    V1Switch(
    MyParser(),
    MyVerifyChecksum(),
    MyIngress(),
    MyEgress(),
    MyComputeChecksum(),
    MyDeparser()
    ) main;
```
I'm trying to do a load balancing task in S1 switch using DASH packets that come from h2. Here is the topology:
![topo](https://user-images.githubusercontent.com/53315662/84358376-932fc380-abb6-11ea-8be0-5cb56e709ebd.JPG)
here is what I'm implementing:
Scenario Description
The network we are going to simulate is shown in Fig.5. Consider a scenario in which h1 wants to send
packets, for example UDP, to h2 and there are 4 possible paths from which S1 can choose using DASH load
balancing scheme.
According to the DASH scheme, switches in the path, i.e. S3, S4, S5 and S6, update the DASH probe
packets with their performance metrics. Based on these values, the load balancer, i.e. S1, calculates an
appropriate distribution for stage boundaries regarding each path. However, due to arithmetic calculation
limitations in P4, designing a suitable mapping logic is somehow challenging; therefor to sake simplicity,
we assume that h2 sets the DASH probe packet values and the intermediate switches, i.e. S3, S4, S5 and
S6, don’t change it at all and S1 sets the boundaries using these values without using any algorithms to
calculate a suitable boundary distribution. Note that we should generate appropriate DASH probe packets
in h2 in order to correctly set the boundaries in S1.
Consider a fixed UDP flow from h1 to h2, meanwhile DASH probe packets are sent from h2 to h1 in each
possible path in four rounds. (In each round four DASH probe packets are sent in total, one for each path)
The weight of these DASH Probe packets are shown in the table below. In this simple scenario between the
first and second round, all of the UDP packets originating from h, would be forwarded via S3, whereas S4
is responsible for packet forwarding between the second and the third round, accordingly.
here is S1-runtime.json file:
```
    {
        "target": "bmv2",
        "p4info": "build/dash.p4.p4info.txt",
        "bmv2_json": "build/dash.json",
         "table_entries": [
         {
		     "table":	"MyIngress.switch_split",
		     "default_action":    true,
		     "action_name":	"MyIngress.drop",
		     "action_params":    {   }
	     },
	     {
		     "table":	"MyIngress.switch_split",
		     "match": {
		         "hdr.ipv4.dstAddr": ["10.0.1.1", 24]
		     },
		     "action_name": "MyIngress.split",
	 	     "action_params": {
			     "isS1": 1,
			     "port": 5
             }
	     },
	     { 
		     "table":	"MyIngress.switch_split",
		     "match": {
		         "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		     },
		     "action_name": "MyIngress.split",
		     "action_params": {
			     "isS1": true,
			     "port": 1
		     }
	     }
    ]
    }
```
Here is s2-runtime.json:
```
    {
        "target": "bmv2",
        "p4info": "build/dash.p4.p4info.txt",
        "bmv2_json": "build/dash.json",
        "table_entries": [
        {
		    "table":	"MyIngress.switch_split",
		    "match": {
		        "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		    },
		    "action_name": "MyIngress.split",
		        "action_params": {
			        "isS1": 0,
			        "port": 5
            }
	    }
    ]
    }

```
and Here is sX-runtime.json, X form 3 to 6:

```
    {
        "target": "bmv2",
        "p4info": "build/dash.p4.p4info.txt",
        "bmv2_json": "build/dash.json",
        "table_entries": [
        	{  
		        "table":	"MyIngress.switch_split",
		        "match": {
		            "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		        },
		        "action_name": "MyIngress.split",
		        "action_params": {
         			"isS1": 0,
			        "port": 2
		        }
	        },
        {
		    "table":	"MyIngress.switch_split",
		    "match": {
		        "hdr.ipv4.dstAddr": ["10.0.1.1", 24]
		    },
		    "action_name": "MyIngress.split",
         		"action_params": {
			    "isS1": 0,
    			"port": 1
		    }
	    }
    ]
    }
```

**Comment by jafingerhut** [comment]
I moved this issue from the p4lang/p4-spec repository, to the p4lang/tutorials repository, since tutorials is definitely mentioned in parts of the error messages, and the p4lang/p4-spec repository is intended only for issues about the P4 language specification.

**Comment by baset-vsy** [comment]
Here is my p4 code:
    ` /* -*- P4_16 -*- */
    #include <core.p4>
#include <v1model.p4>


/* Value Definitions */
    #define NUM_STAGES 4        // number of stages
#define STAGE_CAPACITY 16   // size of the table
#define WEIGHT_WIDTH 16     // size of weight feild in DASH probe packet
#define PORT_WIDTH 15       // size of port field in source routing packet
#define MAX_HOPS 5          // maximum number of 
/*------- ToDo: here you can write your value definitions -------*/
#define HASH_VAL_SIZE 16

/* Constant values */
const bit<16> TYPE_IPV4 = 0x800;
const bit<16> TYPE_DASH = 0x4567;    // our convention for dash packets

/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/

/* Type Definition */
typedef bit<48> macAddr_t;
typedef bit<32> ip4Addr_t;
typedef bit<WEIGHT_WIDTH> weight_t;
typedef bit<WEIGHT_WIDTH> boundary_t;
typedef bit<PORT_WIDTH> port_t;
/*------- ToDo: here you can write your type definitions -------*/
typedef bit<HASH_VAL_SIZE> hash_t;
/* Headers */
header ethernet_t {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16>   etherType;
}

header ipv4_t {
    bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
    bit<16>   identification;
    bit<3>    flags;
    bit<13>   fragOffset;
    bit<8>    ttl;
    bit<8>    protocol;
    bit<16>   hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

header udp_t {
    bit<16> srcPort;
    bit<16> dstPort;
    bit<16> length_;
    bit<16> checksum;
}

header dash_t {
    weight_t weight;
}

header srcRoute_t {
    bit<1>    bos;
    port_t   port;
}

struct metadata {
    /*------- ToDo: here you can define your metadata -------*/
    hash_t hash;
}

struct headers {
    ethernet_t              ethernet;
    srcRoute_t[MAX_HOPS]    srcRoutes;
    ipv4_t                  ipv4;
    udp_t                   udp;
    dash_t                  dash;
}

/*************************************************************************
*********************** P A R S E R  ***********************************
*************************************************************************/

/* Keep this unchanged */

parser MyParser(packet_in packet,
                out headers hdr,
                inout metadata meta,
                inout standard_metadata_t standard_metadata) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        packet.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
            TYPE_DASH : parse_dash;
            TYPE_IPV4 : parse_ipv4;
            default   : accept;
        }
    }

    state parse_dash {
        packet.extract(hdr.dash);
        transition parse_srcRouting;
    }

    state parse_srcRouting {
        packet.extract(hdr.srcRoutes.next);
        transition select(hdr.srcRoutes.last.bos) {
            1       : parse_ipv4;
            default : parse_srcRouting;
        }
    }

    state parse_ipv4 {
        packet.extract(hdr.ipv4);
        transition select(hdr.ipv4.protocol) {
            8w17: parse_udp;
            default: accept;
        }
    }

    state parse_udp {
        packet.extract(hdr.udp);
        transition accept;
    }

}

/*************************************************************************
************   C H E C K S U M    V E R I F I C A T I O N   *************
*************************************************************************/

/* Keep this unchanged */

control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}


/*************************************************************************
**************  I N G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    /* Registers */
    register<boundary_t>(STAGE_CAPACITY) boundary_stage_reg;
   /* register<boundary_t>(STAGE_CAPACITY) boundary_stage2_reg
    register<boundary_t>(STAGE_CAPACITY) boundary_stage3_reg
    register<boundary_t>(STAGE_CAPACITY) boundary_stage4_reg*/


    /* This action will drop packets */
    action drop() {
        mark_to_drop(standard_metadata);
    }
    /*------- ToDo: here you can define your actions and tables -------*/
    action srcRoute_nhop(){
	standard_metadata.egress_spec = (bit<9>)hdr.srcRoutes[0].port;
	hdr.srcRoutes.pop_front(1);
    }
    action write_stage(){
	boundary_stage_reg.write((bit<32>)standard_metadata.ingress_port-1,
 hdr.dash.weight);
    }
    action ipv4_forward_normal(){
	

    }
    
    action split(bit<1> isS1,bit<9> port ){
	    hash(meta.hash,HashAlgorithm.crc16,(bit<16>)0,
            {hdr.ipv4.srcAddr,hdr.ipv4.dstAddr},
            (bit<16>)30);
	    boundary_t reg1;
            boundary_stage_reg.read(reg1,0);
	    boundary_t reg2;
            boundary_stage_reg.read(reg2,1);
            boundary_t reg3;
	    boundary_stage_reg.read(reg3,2);
	    boundary_t reg4;
            boundary_stage_reg.read(reg4,3);
	    if (isS1==1){
		if (meta.hash < reg1){
	            standard_metadata.egress_spec = 1;
		}else if(meta.hash < reg2){ 
		    standard_metadata.egress_spec = 2;
		}else if(meta.hash < reg3){  
		    standard_metadata.egress_spec = 3;
		}else if(meta.hash < reg4){
		    standard_metadata.egress_spec = 4;
		}	

	    }else{
		standard_metadata.egress_spec = port;
	    }
	   
    } 
          
    action ipv4_forward(bit<9> port){
	standard_metadata.egress_spec = port;
    }
    
    table switch_split{
	key = {
	    hdr.ipv4.dstAddr: lpm;
	}
	actions = {
	    split;
	    drop;
	    NoAction;
	}
	size = 30;
	default_action = drop();
    }


    apply {

        if (hdr.dash.isValid()){
	    if (hdr.srcRoutes[0].isValid()){
		srcRoute_nhop();
	    }else{
		write_stage();	
       	    }
	   

        }else if (hdr.ipv4.isValid()){
	    switch_split.apply();
	}else{
	    drop();
	}
    }
}

/*************************************************************************
****************  E G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

/* Keep this unchanged */

control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
    apply { }
}

/*************************************************************************
*************   C H E C K S U M    C O M P U T A T I O N   **************
*************************************************************************/

/* Keep this unchanged */

control MyComputeChecksum(inout headers hdr, inout metadata meta) {
     apply {
	update_checksum(
	    hdr.ipv4.isValid(),
            { hdr.ipv4.version,
	      hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr },
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);
    }
}


/*************************************************************************
***********************  D E P A R S E R  *******************************
*************************************************************************/

/* Keep this unchanged */

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.dash);
        packet.emit(hdr.srcRoutes);
        packet.emit(hdr.ipv4);
        packet.emit(hdr.udp);
    }
}

/*************************************************************************
***********************  S W I T C H  *******************************
*************************************************************************/

/* Keep this unchanged */

//switch architecture
V1Switch(
MyParser(),
MyVerifyChecksum(),
MyIngress(),
MyEgress(),
MyComputeChecksum(),
MyDeparser()
) main;
`

**Comment by baset-vsy** [comment]
I'm trying to do a load balancing task in S1 switch using DASH packets that come from h2. Here is the topology:
![topo](https://user-images.githubusercontent.com/53315662/84358376-932fc380-abb6-11ea-8be0-5cb56e709ebd.JPG)
here is what I'm implementing:
Scenario Description
The network we are going to simulate is shown in Fig.5. Consider a scenario in which h1 wants to send
packets, for example UDP, to h2 and there are 4 possible paths from which S1 can choose using DASH load
balancing scheme.
According to the DASH scheme, switches in the path, i.e. S3, S4, S5 and S6, update the DASH probe
packets with their performance metrics. Based on these values, the load balancer, i.e. S1, calculates an
appropriate distribution for stage boundaries regarding each path. However, due to arithmetic calculation
limitations in P4, designing a suitable mapping logic is somehow challenging; therefor to sake simplicity,
we assume that h2 sets the DASH probe packet values and the intermediate switches, i.e. S3, S4, S5 and
S6, don’t change it at all and S1 sets the boundaries using these values without using any algorithms to
calculate a suitable boundary distribution. Note that we should generate appropriate DASH probe packets
in h2 in order to correctly set the boundaries in S1.
Consider a fixed UDP flow from h1 to h2, meanwhile DASH probe packets are sent from h2 to h1 in each
possible path in four rounds. (In each round four DASH probe packets are sent in total, one for each path)
The weight of these DASH Probe packets are shown in the table below. In this simple scenario between the
first and second round, all of the UDP packets originating from h, would be forwarded via S3, whereas S4
is responsible for packet forwarding between the second and the third round, accordingly.

**Comment by baset-vsy** [comment]
here is S1-runtime.json file:
`{
  "target": "bmv2",
  "p4info": "build/dash.p4.p4info.txt",
  "bmv2_json": "build/dash.json",
  "table_entries": [
       {
		"table":	"MyIngress.switch_split",
		"default_action":    true,
		"action_name":	"MyIngress.drop",
		"action_params":    {   }
	},
	{
		"table":	"MyIngress.switch_split",
		"match": {
		    "hdr.ipv4.dstAddr": ["10.0.1.1", 24]
		},
		"action_name": "MyIngress.split",
		"action_params": {
			"isS1": 1,
			"port": 5
}
	},
	{
		"table":	"MyIngress.switch_split",
		"match": {
		    "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		},
		"action_name": "MyIngress.split",
		"action_params": {
			"isS1": true,
			"port": 1
		}
	}
  ]
}
`
Here is s2-runtime.json:
`{
  "target": "bmv2",
  "p4info": "build/dash.p4.p4info.txt",
  "bmv2_json": "build/dash.json",
  "table_entries": [
{
		"table":	"MyIngress.switch_split",
		"match": {
		    "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		},
		"action_name": "MyIngress.split",
		"action_params": {
			"isS1": 0,
			"port": 5
}
	}
  ]
}
`
and Here is sX-runtime.json, X form 3 to 6:
`{
  "target": "bmv2",
  "p4info": "build/dash.p4.p4info.txt",
  "bmv2_json": "build/dash.json",
  "table_entries": [
	{
		"table":	"MyIngress.switch_split",
		"match": {
		    "hdr.ipv4.dstAddr": ["10.0.1.2", 24]
		},
		"action_name": "MyIngress.split",
		"action_params": {
			"isS1": 0,
			"port": 2
		}
	},
{
		"table":	"MyIngress.switch_split",
		"match": {
		    "hdr.ipv4.dstAddr": ["10.0.1.1", 24]
		},
		"action_name": "MyIngress.split",
		"action_params": {
			"isS1": 0,
			"port": 1
		}
	}
  ]
}`

**Comment by baset-vsy** [comment]
@jafingerhut 
I did what you said. Can you or anyone guide me through this?
