### ISSUE TITLE
How to make the switches in topo use the same clock to achieve time synchronization？

### ISSUE THREAD

**Issue by welink321** [p4lang/tutorials#369]
We want to simulate the delay measurement in network performance, but we find that the time of each switch is activated when the packets are sent to the switch. There is no time synchronization, so we would like to ask you how to make the switches in topo use the same clock to achieve time synchronization.Or can you tell us where the code is for the switches in topo to synchronize?

**Comment by jafingerhut** [comment]
Here is an answer I have written to another recent question on this topic, and either it or some slightly updated variant of it will probably be added to the p4lang/behavioral-model repository documentation of simple_switch within a week or so.  Please read it over and see if it answers your questions: https://github.com/jafingerhut/behavioral-model/blob/add-notes-on-timestamp-synchronization/docs/simple_switch.md#BMv2-timestamp-implementation-notes

**Comment by jafingerhut** [comment]
Closing this issue, as there has been no follow-up in some time.  I would recommend forum.p4.org as a good place to discuss similar topics in the future, and in fact this discussion linked here is specifically on this topic: https://forum.p4.org/t/how-to-obtain-switch-startup-time-to-synchronize-ingress-timestamp/128
