### ISSUE TITLE
Register cannot be declared at the top-level

### ISSUE THREAD

**Issue by qizhe** [p4lang/tutorials#37]
I use v1model (v1model.p4) to build the program. When I tried to instantiate extern registers at the top-level of my program and read register values at one of actions, I got error:

P4 switch s1 did not start correctly.Check the switch log file.

S1 log:
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Calling target program-options parser

After I changed to declare registers in the ingress control block, I can run my program.
I don't find in P4_16 spec that forbids us to declare extern objects in the top-level.

**Comment by jafingerhut** [comment]
If you can reproduce these results with the most recent version of the code in the p4c repository with a short P4-16 program, and attach that program to an issue in that repository, the would help get the right people's attention on it.

**Comment by qizhe** [comment]
Follow the suggestion: [#696](https://github.com/p4lang/p4c/issues/696).
Can you close this issue??
