### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by vonhoro** [p4lang/tutorials#370]
Hello, I had been trying to install the tutorial via vagrant for weeks but my internet connection is really bad so it always stops midway through, I can't fix my connection because I live in Venezuela. What I actually want is that you upload the resource in a torrent, or a ftp server, so I can download them by parts and also send all the configurations needed on the virtual machine. I know it is a lot to ask but I will really appreciate the effort.

**Comment by jafingerhut** [comment]
This is something we are hoping to do in the not too distant future.  Follow this issue if you want to know when it has been done: https://github.com/p4lang/tutorials/issues/353

**Comment by vonhoro** [comment]
Thank you for the reply, I will follow the issue.
