### ISSUE TITLE
QoS metering; How to configure meter parameters in controller

### ISSUE THREAD

**Issue by baset-vsy** [p4lang/tutorials#372]
Hi everyone. I'm trying to use meter in my p4 program for a QoS exercise. I'm using a python file (controller.py) to control and add flow to switches. how should I configure meter in my controller.py? I mean how should I set PIR or CIR params in my python program? Please answer as quickly as you can I have a deadline to catch.

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
