### ISSUE TITLE
How to implement Fast Reroute for P4?

### ISSUE THREAD

**Issue by blepodog** [p4lang/tutorials#373]
Hello,
I am trying to implement an algorithm in p4 that can handle a very simple node/link failure for one of the switches in the tutorial. Has anyone perhaps already implemented this type of thing? If so, could you share your code or send me a link? I really don't know how to implement this at all, so any type of help will be great. Thank you in advance!

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
