### ISSUE TITLE
The queue of the P4 switch

### ISSUE THREAD

**Issue by welink321** [p4lang/tutorials#374]
We want to calculate the occupancy ratio of the queue, but there is no physical space size of the queue in the metadata of the P4 switch . 
We have two questions to ask for you. The first question is how can we query the physical space size of the queue of the P4 switch? The second question is do all ports of our P4 switch share the same queue, or each port of our P4 switch have their own queue？

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
