### ISSUE TITLE
how to calculate the actual length of ip header when there is a option

### ISSUE THREAD

**Issue by smartlxh** [p4lang/tutorials#377]
I just want use varbit to represent the options in the ip header ,but how can i  get the actual length of ip header

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).

**Comment by jnfoster** [comment]
But while we're here... look at the [IHL field](https://en.wikipedia.org/wiki/IPv4#IHL) in the IPv4 header.
