### ISSUE TITLE
How to use switch statement?

### ISSUE THREAD

**Issue by KuiWei004** [p4lang/tutorials#378]
In my control block, I write condition code as:
`            switch(trust_type){
                2w0b01:{
                    dscp2cos.apply();    
                }
                2w0b10:{
                    pri2cos.apply();
                }
                2w0b11:{
                    map_portpri_cos();
                }
                default:{}
            }`

where the type of 'trust_type' is bit<2>.
when I compile my p4 program, an error happens like:
 syntax error, unexpected INTEGER
                2w0b01

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).

**Comment by jnfoster** [comment]
But while I'm here, let me refer you to the section on [switch statements](https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-switch-stmt) in the P4 Language Specification. You'll see that switch statements are used to conditionally branch on the result produced by executing a table, not a general expression.
