### ISSUE TITLE
Missing vagrant image

### ISSUE THREAD

**Issue by pranagupt** [p4lang/tutorials#382]
https://github.com/p4lang/tutorials/blob/67fd07bf996b450081098ae066a7a6f40f6fdd43/vm/Vagrantfile#L5

fso/xenial64-desktop no longer exists. The p4app branch should probably be updated or removed, as it is referenced in some workshops.

**Comment by jafingerhut** [comment]
Closing this issue, as the 'vm' directory's README now says it is of historical interest only, and the 'vm-ubuntu-20.04' scripts are tested monthly and promptly updated if anything is found wrong with them.
