### ISSUE TITLE
Some questions about table properties

### ISSUE THREAD

**Issue by ls760008979** [p4lang/tutorials#387]
I want to know how the “match_kind”works in detail ,for example,
![image](https://user-images.githubusercontent.com/30166591/96421349-407fab80-1229-11eb-963a-ffeeca7ada0f.png)
As the picture shows,it specify the exact identifier to match the ttl field,is it means when the packet’s ttl=0,it going to do the action “copy_to_metadata”? And I don’t know how these three match_kind work exactly.I haven’t found these answers in the p4-spec, https://p4.org/p4-spec/docs/P4-16-v1.2.1.html
Hope for your answers!

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the [p4-dev](https://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) email list or the [P4 Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
