### ISSUE TITLE
Include the documentation for v1model in tutorial README's.

### ISSUE THREAD

**Issue by pranagupt** [p4lang/tutorials#390]
I've been trying to learn about P4 for a while and realised that the only official source of learning is specifications for P4, specifications for PSA and this tutorial repository. All workshop videos are also based on this tutorials repository. As such, there is no dedicated documentation on the v1model which can be found inside the README.md files of any of these tutorials or that is talked about in the videos. Considering that these tutorials are based on v1model, the documentation for v1model should be linked inside the README.md files for each tutorial.

The only documentation that I could find is located at:
1. https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md
2. https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4

The second link above is the include file itself and the documentation thus is the comments.

**Comment by jafingerhut** [comment]
Those are the two primary sources that I am aware of for documentation of the v1model architecture.

Are you proposing that both your items #1 and #2 be linked from one or more README's in this tutorial repository?  If so, I think that is a fine idea.  Please create a PR doing so, and I would guess the maintainers of the tutorials are likely to find it a useful addition.

**Comment by pranagupt** [comment]
That's exactly what I'm proposing. I've created a PR for this.

**Comment by jafingerhut** [comment]
Closing this issue, as the PR has been created, and if the last CLA requirement is met, I expect it will be merge in.
