### ISSUE TITLE
Creating and sending packets from P4

### ISSUE THREAD

**Issue by sbibek** [p4lang/tutorials#392]
Hi,

I know there is a tutorial regarding setting ipv4.ecn in traffic when there is a congestion condition. What I want to do is create a UDP packet and send it to a receiver host when there is congestion from p4 itself instead of just setting the header field. I searched and I am not able to see any examples of that specific case. Any resource for this case?

Thanks

**Comment by jafingerhut** [comment]
You can clone (also called mirror) the original packet, sending the original packet where you normally would, and modifying the clone/mirror packet as much as you wish, e.g. adding new headers to the front of it, modifying headers, removing headers.  The payload will still be attached, but as long as the headers you have in front of that are of appropriate kinds, you can probably ensure the receiving host can know that it should ignore that payload.

Some devices enable truncating cloned/mirrored packets, and that could optionally be used to remove some or all of the original packet's payload.

**Comment by sbibek** [comment]
I want to be able to create the payload too. Is that not supported?

**Comment by jafingerhut** [comment]
How big of a payload?  High speed targets let you create "headers only" but some of them can create up to around the neighborhood of 100 to 200 bytes of headers.  If you want to create a full payload of 1500 bytes with every byte specified by your software, then it will significantly limit your ability to find a device that can support that.  You can create such packets in a general purpose CPU just fine.

**Comment by sbibek** [comment]
Let us suppose a scenario where each p4 enabled switch stores the max queue depth, max hop latency, and max link latency from its neighbors (~100-200bytes of information lets suppose). I was able to attach that information in the payload of a UDP probe packet when it's encountered. Is this approach good?

But what I really want to do is the ability to create that UDP packet in the P4 enabled switch itself and add those all information as the payload of that created packet instead of using the probe packet.

**Comment by jafingerhut** [comment]
In the 100 to 200 byte range, many P4 implementations can add that many bytes of what P4 calls "headers", but could very well be the UDP payload of a packet when received by a host.  Don't get hung up on the fact that P4 calls them headers -- they are sequences of bytes in a packet.  If that sequence of bytes would be recognized as a UDP payload by networking software running in a host, then if P4 calls it headers, the host networking software won't know or care about that.

What event do you want to cause that UDP packet to be created in the P4 enabled switch?  Periodically?  If so, how often?  Every 10 milliseconds?  Every microsecond?  Something else?  The slower the rate you want to do it, the more easily a control plane CPU can do the job.  The faster the rate you want to do it, there exist P4-programmable switch ASICs that can generate packets periodically with quite fast rates, based solely upon time elapsing as the trigger to generate them.

Do you want the packets created in response to packets being received?  Then the clone/mirror method I mentioned should be quite possible to make it work.

**Comment by sbibek** [comment]
1. As you said, I want to be able to periodically send out packets each second with information such as Queue occupancy, link latency, hop latency to a specific sink node in the network. 

_When you said control plane CPU, you mean generate and send packets from the controller application right. For example a module in ONOS maybe? This would mean that the controller would generate a kind of probe packet periodically and then the p4 would attach information to it and forward it to the sink node right?_

2. Also I would like to have a functionality where the switch would create and send packet when it meets certain conditions. For example, when the queue occupancy is greater than 50% etc. 

_For this, I can use the clone/mirror method like you said I guess where I clone the packet when the condition meets and attach information to that packet and send it to the sink node right?_

These functionalities above, I want to achieve them using the bmv2 switch.

**Comment by jafingerhut** [comment]
1. Short answer: yes.

Longer answer: Having a controller application send a probe packet to the switch once per second is a trivially slow rate of packets for it to generate.  You might not get 1 second plus or minus 1 nanosecond of precision on the interarrival times of such packets, but you probably don't need better than 1 second plus or minus 10 milliseconds.

2. If you want the trigger to be "when a packet is received for some other reason, and the queue occupancy is greater than 50%", then yes, clone/mirror can be used.  Note that if the trigger conditions is _exactly_ that, then once the queue occupancy exceeds 50%, every single packet arriving after that will also trigger that same condition.  You could use a meter to limit the rate of the mirror operation, if that helps you, among other ways of limiting the rate of such mirror packets.

All of the things described in this comment are possible by writing P4 code for the bmv2 switch, using the v1model architecture, today.

**Comment by sbibek** [comment]
Thanks a ton, @jafingerhut.
