### ISSUE TITLE
basic run "make run" error "P4 switch s1 did not start correctly."

### ISSUE THREAD

**Issue by zhangzicheng0428** [p4lang/tutorials#394]
root@ubuntu:~/P4/p4_tutorials/exercises/basic# make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter dstAddr
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter port
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
P4 switch s1 did not start correctly.
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by zhangzicheng0428** [comment]
I tried it your way and the result is still the same.Virtual machine reboots and shutdowns have been tried.
![image](https://user-images.githubusercontent.com/35160702/101305443-b1346300-387d-11eb-94e4-2e40979ef431.png)
tutorials代码我是取最新的，commit：4914893445ae24bd1fa3b4aeea4910eeb412f7de.

**Comment by jnfoster** [comment]
Next questions:
* How did you install all of the required dependencies?
* What happens if you run `simple_switch_grpc` directly?
* And what happens if you run the command 
```
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
```
directly?

**Comment by Mtze** [comment]
I have the same problem:

```
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc

Reading topology file.
Building mininet topology.
P4 switch s1 did not start correctly.
```
do you have any other hints?

**Comment by jafingerhut** [comment]
@Mtze There are many ways you might have obtained and installed the open source P4 tools.  We cannot tell how you did so, unless you tell us.  Some methods of installing the tools produce a system that can run the tutorials, but most do not.

One way that can run at least the basic exercise successfully is to start from a fresh, unmodified Ubuntu 18.04 Linux system (or virtual machine), and run the install scripts suggested here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

There are other paths to success, too, of course.

**Comment by Mtze** [comment]
@jafingerhut Oh my god. I was fiddling for days with the bootstrap scripts in this repository. Finally I have a working test environment using your guide and scripts. Thank you so much! I really appreciate it! Maybe you could link your great guide in the readme of this repo. I think this could save beginners a lot of time.

**Comment by jafingerhut** [comment]
Strange.  You did not try the instructions in the README of this repository to install Vagrant, then do `cd vm ; vagrant up` ?  That uses versions of the open source P4 tools from August 2019 installed on Ubuntu 16.04 Linux, I know, not the most recent ones, but last I checked I thought that was another path to success.

**Comment by Mtze** [comment]
I tried that last week. It didn't work for me. Some strange error I never saw before. I can't remember what it was - However that could also be due to my setup.

**Comment by jafingerhut** [comment]
@Mtze I have seen the `vagrant up` approach fail if the host operating system does not have enough free disk space to hold the final size that the VM image grows to.  The README says "Before proceeding, ensure that your system has at least 25 Gbytes of free disk space, otherwise the installation can fail in unpredictable ways."

I am not saying that is the only reason that `vagrant up` could fail, but it is certainly one of the ways, and there is nothing in the `vagrant up` sequence of steps that will check _for_ you whether your system has enough free disk space before starting.  It will try, and if at some arbitrary place in the middle of installing the open source P4 tools your disk space runs out, something will fail with no obvious indication as to why.

**Comment by XH961209** [comment]
> I tried it your way and the result is still the same.Virtual machine reboots and shutdowns have been tried.
> ![image](https://user-images.githubusercontent.com/35160702/101305443-b1346300-387d-11eb-94e4-2e40979ef431.png)
> I am taking the latest tutorials code, commit: [4914893](https://github.com/p4lang/tutorials/commit/4914893445ae24bd1fa3b4aeea4910eeb412f7de) ae24bd1fa3b4aeea4910eeb412f7de.

I have the same problem as you and I have solved it. Maybe you can refer to my solution:
Check logs/s1.log in current directory and it reminds me that port 9090 has been occupied. Kill the process that occupies port 9090, make clean, make run again and it works!

**Comment by jafingerhut** [comment]
Closing this issue as it seems that the problems were solved a while ago.

**Comment by LYuanLing** [comment]
I have a same question.Other files can be successfully `made`, only this file I created myself can not `make`successfully,  is it that I wrote wrong?

`^Cbella@bella-virtual-machine:~/tutorials/exercises/INT GitHub1$ make
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/networkflow.p4.p4info.txt -o build/networkflow.json networkflow.p4
sudo python3 ../../utils/run_exercise.py -t topology.json -j build/networkflow.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 383, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 193, in run_exercise
    self.create_network()
  File "../../utils/run_exercise.py", line 254, in create_network
    self.net = Mininet(topo = self.topo,
  File "/usr/local/lib/python3.8/dist-packages/mininet/net.py", line 178, in __init__
    self.build()
  File "/usr/local/lib/python3.8/dist-packages/mininet/net.py", line 508, in build
    self.buildFromTopo( self.topo )
  File "/usr/local/lib/python3.8/dist-packages/mininet/net.py", line 495, in buildFromTopo
    self.addLink( **params )
  File "/usr/local/lib/python3.8/dist-packages/mininet/net.py", line 406, in addLink
    link = cls( node1, node2, **options )
  File "/usr/local/lib/python3.8/dist-packages/mininet/link.py", line 568, in __init__
    Link.__init__( self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mininet/link.py", line 456, in __init__
    self.makeIntfPair( intfName1, intfName2, addr1, addr2,
  File "/usr/local/lib/python3.8/dist-packages/mininet/link.py", line 501, in makeIntfPair
    return makeIntfPair( intfname1, intfname2, addr1, addr2, node1, node2,
  File "/usr/local/lib/python3.8/dist-packages/mininet/util.py", line 270, in makeIntfPair
    raise Exception( "Error creating interface pair (%s,%s): %s " %
Exception: Error creating interface pair (s1-eth1,s3-eth1): RTNETLINK answers: File exists
 
make: *** [../../utils/Makefile:35: run] Error 1
`

**Comment by LYuanLing** [comment]
I have a same question.Other files can be successfully made, only this file I created myself can not makesuccessfully, is it that I wrote wrong?
![image](https://user-images.githubusercontent.com/93515058/158002627-a12b0b74-39d7-4056-a9b0-6cb075d48406.png)
