### ISSUE TITLE
make: *** No rule to make target 

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#397]
Salam,
Please I have already run my p4 program in /p4lang/tutorials/ It was Ok .
But now it gives me an error

@admin-P4:~/tutorials/exercises/dmd$ **make**
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/SYN_cookie.p4.p4info.txt -o build/SYN_cookie.json SYN_cookie.p4
make: *** No rule to make target 'SYN_cookie', needed by 'build'.  Stop.

**Comment by jnfoster** [comment]
There is no file named SYN_cookie.p4 in the tutorials repository. So I can only assume you are trying to develop a new application based on the tutorials infrastructure. 

There is some logic in the Makefiles to try to auto-detect the main P4 program. But it's not guaranteed to work if you start changing the structure of the template.

Perhaps you can provide a more detailed description of what you are trying to do and, more importantly, exactly which files and commands you are running, and we can try to help...

I'm going to close this issue though as it doesn't sound like a problem with the tutorial code itself.
