### ISSUE TITLE
Parse payload from the packet

### ISSUE THREAD

**Issue by baganal** [p4lang/tutorials#402]
I wanted to know if we can parse few bits of payload from the packet and use those bits to match in table for forwarding.

**Comment by jnfoster** [comment]
Yes.

**Comment by jafingerhut** [comment]
A P4 implementation doesn't know anything about any RFCs or standards documents.  It is up to you to decide how to interpret the bits at the beginning of the packet.  If an RFC calls it the UDP payload, your P4 program can call it "mycustomheader" that is 8 bytes long, if you write your P4 program that way.

**Comment by baganal** [comment]
I am new to P4 programming. I am using socket programming to send and receive data. I am able define "myCustomHeader" of 8 bits long and parse it. But in socket programming I can only send and receive "strings" and type "string" is not available in P4 program. I want to know how can I take this parsed value which is string and use it.

> A P4 implementation doesn't know anything about any RFCs or standards documents. It is up to you to decide how to interpret the bits at the beginning of the packet. If an RFC calls it the UDP payload, your P4 program can call it "mycustomheader" that is 8 bytes long, if you write your P4 program that way.
