### ISSUE TITLE
How to run simple_switch_grpc with root privileges?

### ISSUE THREAD

**Issue by liuningchun** [p4lang/tutorials#406]
Hi All,

I build a P4 environment successful, but when trying to connect to ONOS, I meet some problems with root privileges.

**Now the situation is**
```
ps aux | grep simple_switch
simple_switch_grpc -i 1@s1-eth1 -i 2@s1-eth2 --pcap /home/njliuningchun/P4/tutorials/exercises/basic/pcaps --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 build/basic.json --log-console --thrift-port 9090 -- --grpc-server-addr 172.18.0.211:50051
```

I want to run simple_switch_grpc with root privileges. I tried to modify the.py file, but I couldn't do it. Please tell me how to fix it?

Thanks,
Ningchun Liu

**Comment by jafingerhut** [comment]
The P4 Slack community might be a better place to ask such questions (not guaranteed to get an answer there, but it if someone is willing to help, it can be easier to interactively ask you questions about what you are trying to do, what code you are using, etc.).

For example, my first question would be: If you are trying to connect to ONOS, are you using any code in this p4lang/tutorials repository at all?  Perhaps your questions are more appropriate for someone familiar with ONOS, and/or as a Github issue on some ONOS project you are using?

**Comment by jafingerhut** [comment]
FYI, you should be able to join the P4 Slack community by going to the p4.org web site, click on the "COMMUNITY" pop-down menu title near the top right, and select "Slack" from the menu that appears.

**Comment by jafingerhut** [comment]
Closing this issue as there has not been any follow-up in many months.   I would also recommend forum.p4.org for asking similar questions in the future, and there are also ONOS-specific on line discussion places, too.
