### ISSUE TITLE
make run error: cannot import name p4runtime_pb2

### ISSUE THREAD

**Issue by Benature** [p4lang/tutorials#407]
Hello, I am new in P4, and I am trying to run the tutorials in my own vm(Ubuntu 18.04 LTS) on VirtualBox.

I install p4c, bmv2, PI with these commit id
```bash
BMV2_COMMIT="b447ac4c0cfd83e5e72a3cc6120251c1e91128ab"
PI_COMMIT="41358da0ff32c94fa13179b9cee0ab597c9ccbcc"
P4C_COMMIT="120503837d4a9b9822e59356c8ff13d72491196e"

PROTOBUF_COMMIT="v3.2.0" #3.2.0/3.6.1
GRPC_COMMIT="v1.3.2" #1.3.2/1.17.2
```
and I checkout the tutorials to branch `p4d2-2018-spring` (ref from some other issues)

I can successfully `make build` by modifying `mark_to_drop(standard_metadata)`, but `make run` has some problem

```shell
user@user-VirtualBox ~/p/t/e/basic> make
mkdir -p build pcaps logs
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/home/user/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/home/user/p4/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/home/user/p4/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4 import p4runtime_pb2
ImportError: cannot import name p4runtime_pb2
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1
```
I found #178 discussed the same problem, but here my `PI_COMMIT` consists with https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L8

**Comment by AkashiLi** [comment]
I also had this error when running sigcomm19. The error came from using incorrect pip libraries. Perhaps downgrade/upgrade to these versions 

enum34 (1.1.10)
grpcio (1.20.0)
mininet (2.3.0)
pip (8.1.1)
protobuf (3.2.0)
psutil (3.4.2)
setuptools (20.10.1)
six (1.10.0)

Then, retry running the ./autogen.sh an ./configure for the different packages. That should fix it

**Comment by jafingerhut** [comment]
Closing this issue since there has not been any follow-up in some time.  I run the `vagrant up` script monthly, and have not had any issues using `make run` to run the basic tutorial exercise code.
