### ISSUE TITLE
Deflection routing in p4

### ISSUE THREAD

**Issue by visatish** [p4lang/tutorials#408]
Hi,

I am new to p4 and trying to implement deflection routing. I would like to implement a simple deflection policy that redirects packets to a different port as specified in the packet header if the queue for the default port exceeds some capacity (in particular I am interested in 0, N, and the maximum capacity). I have a few questions regarding how to implement this functionality:

1. The `enq_qdepth` and `deq_qdepth` fields seem of relevance; however, I cannot find any documentation for them. Where can I find this?
2. How can I configure the maximum queue capacity and is there a way to programmatically query this?
3. It seems that for the `psa_switch` it is not possible to modify the output port in the egress pipeline as per the PSA [specification](https://p4.org/p4-spec/docs/PSA.html#appendix-rationale-egress-cannot-change-output-port). Is this also true for the `simple_switch`? If so, would the recommended place to implement this behavior be in the ingress pipeline? I have seen some examples of `enq_qdepth` and `deq_qdepth` used/queried in the egress pipeline but never in the ingress pipeline. Are they still valid in the ingress pipeline?

Thanks

**Comment by jnfoster** [comment]
Hi. Welcome to the P4 Community!

This is a repository for teaching materials. It's not a great place to ask general technical questions. May I suggest the P4 Slack? You can join here: https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI
