### ISSUE TITLE
'Make run' fails in basic tutorial exercise

### ISSUE THREAD

**Issue by mgucc** [p4lang/tutorials#413]
Hello, I just started with P4 and I am trying to do the tutorial's exercises.

I downloaded the VM image (as recommended), cloned the tutorials and attempted to 'make run' in _basic_ example.
I managed to solve the first issue I found updrading grpcio library to version 1.20.1 (as described [here](https://github.com/p4lang/tutorials/issues/253)).

Now I have another error:
```

p4@p4:~/tutorials/exercises/basic$ sudo make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter dstAddr
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter port
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
P4 switch s1 did not start correctly.
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1
```

As the error seems to be related to _simple_switch_grpc_ I also tried to run it alone. Here is what I got:

```
p4@p4:~/tutorials/exercises/basic$ sudo simple_switch_grpc pod-topo/topology.json 
Calling target program-options parser
Field standard_metadata.egress_port is required by switch target but is not defined
```

Is possible that simple switch is missing some required metadata? Otherwise what could be the problem?

Thanks a lot for any help,
Michele

**Comment by AkashiLi** [comment]
Perhaps retry running 

# Simple_switch_grpc target
cd targets/simple_switch_grpc
./autogen.sh
./configure --with-thrift
make -j${NUM_CORES}
sudo make install
sudo ldconfig

after changing dependencies. Also, you can try rebuilding mininet. That is how I solved it.

**Comment by jafingerhut** [comment]
Closing this issue since there has not been any follow-up in some time. I run the vagrant up script monthly, and have not had any issues using make run to run the basic tutorial exercise code.

**Comment by jarenass001** [comment]
Hello, I'm having this problem after compiling my .p4 program, when I run: `sudo simple_switch --log-console -i 0@eth0 -i 1@eth1 myprogram.json`, I'm trying to find targets/simple_switch_grpc directory, but I can't. What can I do to solve that problem?
Thank you in advance for any help.
