### ISSUE TITLE
user-bootstrap.sh - ares_parse_ptr_reply.c

### ISSUE THREAD

**Issue by ddaya** [p4lang/tutorials#414]
=> Ubuntu 20.04.2 LTS (5.4.0-73-generic)

p4@p4:~/tutorials/vm$ sudo ./user-bootstrap.sh
...
...
[MAKE]    Generating /home/p4/tutorials/vm/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
[C]       Compiling third_party/cares/cares/ares__get_hostent.c
[C]       Compiling third_party/cares/cares/ares__read_line.c
[C]       Compiling third_party/cares/cares/ares__timeval.c
[C]       Compiling third_party/cares/cares/ares_cancel.c
[C]       Compiling third_party/cares/cares/ares_create_query.c
[C]       Compiling third_party/cares/cares/ares_data.c
[C]       Compiling third_party/cares/cares/ares_destroy.c
[C]       Compiling third_party/cares/cares/ares_expand_name.c
[C]       Compiling third_party/cares/cares/ares_expand_string.c
[C]       Compiling third_party/cares/cares/ares_fds.c
[C]       Compiling third_party/cares/cares/ares_free_hostent.c
[C]       Compiling third_party/cares/cares/ares_free_string.c
[C]       Compiling third_party/cares/cares/ares_getenv.c
[C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
[C]       Compiling third_party/cares/cares/ares_gethostbyname.c
[C]       Compiling third_party/cares/cares/ares_getnameinfo.c
[C]       Compiling third_party/cares/cares/ares_getopt.c
[C]       Compiling third_party/cares/cares/ares_getsock.c
[C]       Compiling third_party/cares/cares/ares_init.c
[C]       Compiling third_party/cares/cares/ares_library_init.c
[C]       Compiling third_party/cares/cares/ares_llist.c
[C]       Compiling third_party/cares/cares/ares_mkquery.c
[C]       Compiling third_party/cares/cares/ares_nowarn.c
[C]       Compiling third_party/cares/cares/ares_options.c
[C]       Compiling third_party/cares/cares/ares_parse_a_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_aaaa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_mx_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ns_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_soa_reply.c
In file included from /usr/include/string.h:495,
                 from third_party/cares/cares/setup_once.h:35,
                 from third_party/cares/cares/ares_setup.h:214,
                 from third_party/cares/cares/ares_parse_ptr_reply.c:17:
In function ‘strncpy’,
    inlined from ‘ares_parse_ptr_reply’ at third_party/cares/cares/ares_parse_ptr_reply.c:134:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: In function ‘ares_parse_ptr_reply’:
third_party/cares/cares/ares_parse_ptr_reply.c:134:47: note: length computed here
  134 |           strncpy(aliases[aliascnt], rr_data, strlen(rr_data)+1);
      |                                               ^~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:2470: /home/p4/tutorials/vm/grpc/objs/opt/third_party/cares/cares/ares_parse_ptr_reply.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by rst0git** [comment]
@ddaya You can use Andy's [branch](https://github.com/jafingerhut/tutorials/tree/add-2021-mar-vm-based-on-ubuntu-20.04) for Ubuntu 20.04.

> cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]

Have you installed [all dependencies](https://github.com/jafingerhut/tutorials/blob/9bb39314dcd15cd3b941162d514fd41bbfdd04e2/vm-ubuntu-20.04/root-bootstrap.sh#L32)?

**Comment by ddaya** [comment]
Hi Radostin:

Thank you for your quick response.

Ok, will download Andy's branch I'll provide update next week.

Yes, all dependencies were installed:

root@p4:/home/p4# apt-get install -y --no-install-recommends --fix-missing\
...
...
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Virtual packages like 'linux-headers' can't be removed
autoconf is already the newest version (2.69-11.1).
automake is already the newest version (1:1.16.1-4ubuntu6).
bison is already the newest version (2:3.5.1+dfsg-1).
cmake is already the newest version (3.16.3-1ubuntu1).
cpp is already the newest version (4:9.3.0-1ubuntu2).
flex is already the newest version (2.6.4-6.2).
g++ is already the newest version (4:9.3.0-1ubuntu2).
iproute2 is already the newest version (5.5.0-1ubuntu1).
libboost-dev is already the newest version (1.71.0.0ubuntu2).
libboost-filesystem-dev is already the newest version (1.71.0.0ubuntu2).
libboost-program-options-dev is already the newest version (1.71.0.0ubuntu2).
libboost-system-dev is already the newest version (1.71.0.0ubuntu2).
libboost-thread-dev is already the newest version (1.71.0.0ubuntu2).
libelf-dev is already the newest version (0.176-1.1build1).
libevent-dev is already the newest version (2.1.11-stable-1).
libffi-dev is already the newest version (3.3-4).
libfl-dev is already the newest version (2.6.4-6.2).
libgc-dev is already the newest version (1:7.6.4-0.4ubuntu1).
libgmp-dev is already the newest version (2:6.2.0+dfsg-4).
libpcap-dev is already the newest version (1.9.1-3).
libpython3-dev is already the newest version (3.8.2-0ubuntu2).
libreadline-dev is already the newest version (8.0-4).
libtool is already the newest version (2.4.6-14).
libtool-bin is already the newest version (2.4.6-14).
make is already the newest version (4.2.1-1.2).
net-tools is already the newest version (1.60+git20180626.aebd88e-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu4).
python3 is already the newest version (3.8.2-0ubuntu2).
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-setuptools is already the newest version (45.2.0-1).
tcpdump is already the newest version (4.9.3-4).
unzip is already the newest version (6.0-25ubuntu1).
vim is already the newest version (2:8.1.2269-1ubuntu5).
wget is already the newest version (1.20.3-1ubuntu1).
clang is already the newest version (1:10.0-50~exp1).
emacs is already the newest version (1:26.3+1-1ubuntu2).
libboost-graph-dev is already the newest version (1.71.0.0ubuntu2).
libboost-iostreams-dev is already the newest version (1.71.0.0ubuntu2).
libboost-test-dev is already the newest version (1.71.0.0ubuntu2).
libgflags-dev is already the newest version (2.2.2-1build1).
libjudy-dev is already the newest version (1.0.5-5).
llvm is already the newest version (1:10.0-50~exp1).
lubuntu-desktop is already the newest version (20.04.8).
xcscope-el is already the newest version (1.4-1).
build-essential is already the newest version (12.8ubuntu1.1).
ca-certificates is already the newest version (20210119~20.04.1).
curl is already the newest version (7.68.0-1ubuntu2.5).
git is already the newest version (1:2.25.1-1ubuntu3.1).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.4).
valgrind is already the newest version (1:3.15.0-1ubuntu9.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.5).
xterm is already the newest version (353-1ubuntu1.20.04.2).
atom is already the newest version (1.57.0).
sublime-text is already the newest version (3211).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@p4:/home/p4#

**Comment by rst0git** [comment]
There is a pre-build virtual machine image based on Ubuntu 20.04 that you can use with Virtual Box.
https://drive.google.com/file/d/13SwWBEnApknu84fG9otwbL5NC78tut-d/view?usp=sharing

**Comment by ddaya** [comment]
Hi Radostin:

Thanks for the above link, which is the same image I'd used earlier--I re-downloaded the image to produce the same issue as follows:

p4@p4:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

p4@p4:~$ uname -a
Linux p4 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
p4@p4:~$ 

p4@p4:~/tutorials/vm$ sudo ./root-bootstrap.sh 
+ DEBIAN_FRONTEND=noninteractive
+ sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:2 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu focal InRelease                                                               
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                
Get:4 https://download.sublimetext.com apt/stable/ InRelease [2,557 B]                                                                         
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                                        
Err:6 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu focal Release                                          
  404  Not Found [IP: 91.189.95.85 80]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [237 kB]                      
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [664 kB]                     
Get:10 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [134 kB]         
Get:11 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [207 kB]                                          
Get:12 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [30.7 kB]                              
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [578 kB]                                             
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [457 kB]                                              
Get:15 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                                                    
Get:16 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [90.1 kB]                                               
Get:17 http://security.ubuntu.com/ubuntu focal-security/multiverse i386 Packages [5,380 B]                                                     
Get:18 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [19.9 kB]                                                    
Get:19 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [4,316 B]                                                    
Get:20 https://download.sublimetext.com apt/stable/ Packages [791 B]                                                                           
Get:21 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [989 kB]                                             
Get:8 https://packagecloud.io/AtomEditor/atom/any any InRelease [23.2 kB]       
Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [481 kB]           
Get:23 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [224 kB]                    
Get:24 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [226 kB]
Get:25 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [33.3 kB]
Get:26 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [777 kB]
Get:28 http://archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [574 kB]
Get:29 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [167 kB] 
Get:30 http://archive.ubuntu.com/ubuntu focal-updates/multiverse i386 Packages [6,128 B] 
Get:31 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.7 kB]
Get:32 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [5,564 B]
Get:27 https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages [47.9 kB]      
Reading package lists... Done                                      
E: The repository 'http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

p4@p4:~/tutorials/vm$ sudo ./user-bootstrap.sh 
...
...
 /usr/bin/install -c -m 644  google/protobuf/compiler/csharp/csharp_generator.h google/protobuf/compiler/csharp/csharp_names.h '/usr/include/google/protobuf/compiler/csharp'
 /usr/bin/mkdir -p '/usr/include/google/protobuf/compiler/objectivec'
 /usr/bin/install -c -m 644  google/protobuf/compiler/objectivec/objectivec_generator.h google/protobuf/compiler/objectivec/objectivec_helpers.h '/usr/include/google/protobuf/compiler/objectivec'
make[3]: Leaving directory '/home/p4/tutorials/vm/protobuf/src'
make[2]: Leaving directory '/home/p4/tutorials/vm/protobuf/src'
make[1]: Leaving directory '/home/p4/tutorials/vm/protobuf/src'
+ sudo ldconfig
+ unset CFLAGS CXXFLAGS LDFLAGS
+ cd python
+ sudo python setup.py install
sudo: python: command not found

=> p4@p4:~/tutorials/vm$ python3 -V
Python 3.8.5

=> Modified  ./user-bootstrap.sh to use python3:

p4@p4:~/tutorials/vm$ sudo ./user-bootstrap.sh
...
...
[MAKE]    Generating /home/p4/tutorials/vm/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
[C]       Compiling third_party/cares/cares/ares__get_hostent.c
[C]       Compiling third_party/cares/cares/ares__read_line.c
[C]       Compiling third_party/cares/cares/ares__timeval.c
[C]       Compiling third_party/cares/cares/ares_cancel.c
[C]       Compiling third_party/cares/cares/ares_create_query.c
[C]       Compiling third_party/cares/cares/ares_data.c
[C]       Compiling third_party/cares/cares/ares_destroy.c
[C]       Compiling third_party/cares/cares/ares_expand_name.c
[C]       Compiling third_party/cares/cares/ares_expand_string.c
[C]       Compiling third_party/cares/cares/ares_fds.c
[C]       Compiling third_party/cares/cares/ares_free_hostent.c
[C]       Compiling third_party/cares/cares/ares_free_string.c
[C]       Compiling third_party/cares/cares/ares_getenv.c
[C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
[C]       Compiling third_party/cares/cares/ares_gethostbyname.c
[C]       Compiling third_party/cares/cares/ares_getnameinfo.c
[C]       Compiling third_party/cares/cares/ares_getopt.c
[C]       Compiling third_party/cares/cares/ares_getsock.c
[C]       Compiling third_party/cares/cares/ares_init.c
[C]       Compiling third_party/cares/cares/ares_library_init.c
[C]       Compiling third_party/cares/cares/ares_llist.c
[C]       Compiling third_party/cares/cares/ares_mkquery.c
[C]       Compiling third_party/cares/cares/ares_nowarn.c
[C]       Compiling third_party/cares/cares/ares_options.c
[C]       Compiling third_party/cares/cares/ares_parse_a_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_aaaa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_mx_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ns_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_soa_reply.c
In file included from /usr/include/string.h:495,
                 from third_party/cares/cares/setup_once.h:35,
                 from third_party/cares/cares/ares_setup.h:214,
                 from third_party/cares/cares/ares_parse_ptr_reply.c:17:
In function ‘strncpy’,
    inlined from ‘ares_parse_ptr_reply’ at third_party/cares/cares/ares_parse_ptr_reply.c:134:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: In function ‘ares_parse_ptr_reply’:
third_party/cares/cares/ares_parse_ptr_reply.c:134:47: note: length computed here
  134 |           strncpy(aliases[aliascnt], rr_data, strlen(rr_data)+1);
      |                                               ^~~~~~~~~~~~~~~
[C]       Compiling third_party/cares/cares/ares_parse_srv_reply.c
third_party/cares/cares/ares_parse_ptr_reply.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:2472: /home/p4/tutorials/vm/grpc/objs/opt/third_party/cares/cares/ares_parse_ptr_reply.o] Error 1
make: *** Waiting for unfinished jobs....
p4@p4:~/tutorials/vm$

**Comment by rst0git** [comment]
>p4@p4:~/tutorials/vm$ sudo ./user-bootstrap.sh

The scripts in Andy's branch for Ubuntu 20.04 are stored in the `tutorials/vm-ubuntu-20.04` folder (not `tutorials/vm`), but everything should already be installed in the VM.

**Comment by ddaya** [comment]
Thanks Radostin! - its works!
