### ISSUE TITLE
ABI version mismatch between PI core library (3) and PI implementation (0) 

### ISSUE THREAD

**Issue by ZchuanP** [p4lang/tutorials#417]
Hello, I just started with P4 and I am trying to build a P4 environment on my Ubuntu 16.04. But I have encountered some problems and I am looking forward to your help. Thank you.

When I execute `make run` in practice, I always get this output:
```
P4 switch s11 did not start correctly.
utils/Makefile:27: recipe for target'run' failed
make: *** [run] Error 1
```
I have checked the log:
```
ABI version mismatch between PI core library (3) and PI implementation (0)
simple_switch_grpc: pi.c:160: pi_init: Assertion `abi_version == PI_ABI_VERSION && "PI ABI version mismatch"' failed.
Calling target program-options parser
````
What I want to know is what PI implementation refers to? And how should I update it?

Thanks a lot for any help.

**Comment by antoninbas** [comment]
That's a pretty rare error. It means that you built the P4Runtime server and bmv2 with different versions of the PI headers. I am not even 100% sure of which steps you would need to follow to get this error, it feels like it would be pretty convoluted. PI_ABI_VERSION of 0 is also very old.

The PI implementation it is referring to is https://github.com/p4lang/behavioral-model/tree/main/PI

The steps to follow to build simple_switch_grpc from source are in https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch_grpc/README.md. If that's what you want to do, I recommend starting from a new environment. There are alternatives however:
* @jafingerhut maintains some installation scripts in https://github.com/jafingerhut/p4-guide that may be useful
* there are a few ready-to-use VM images which already include all the software; @jafingerhut uploaded this one recently: https://drive.google.com/file/d/1ZkE5ynJrASMC54h0aqDwaCOA0I4i48AC/view?usp=sharing

**Comment by baixi123** [comment]
Thank you very much for your help.

I have rebuilt my bmv2 and simple_switch_grpc. This error will no longer appear now, but this output still appears when I execute make run.
```
P4 switch s1 did not start correctly.
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1
```
There is no error message in the log：
```
Calling target program-options parser
[21:37:24.798] [bmv2] [D] [thread 22082] Set default default entry for table 'MyIngress.ipv4_lpm': NoAction -
Adding interface s1-eth1 as port 1
[21:37:24.798] [bmv2] [D] [thread 22082] Adding interface s1-eth1 as port 1
Adding interface s1-eth2 as port 2
[21:37:24.823] [bmv2] [D] [thread 22082] Adding interface s1-eth2 as port 2
Adding interface s1-eth3 as port 3
[21:37:24.827] [bmv2] [D] [thread 22082] Adding interface s1-eth3 as port 3
Adding interface s1-eth4 as port 4
[21:37:24.844] [bmv2] [D] [thread 22082] Adding interface s1-eth4 as port 4
```
I can already be sure that it exited at line 194 of run_exercise.py.
```
self.net.start()
```
I have no solution to this. Do you have any ideas?

Thanks again.

**Comment by antoninbas** [comment]
There is no error in the logs. I don't remember the check used to validate that the switch is running, as I am no longer familiar with the tutorials code. But if it's checking whether the bmv2 Thrift service is available, you may want to check out https://github.com/p4lang/behavioral-model/tree/main/targets/simple_switch_grpc#enabling-the-thrift-server

**Comment by jafingerhut** [comment]
Closing this issue as there has been no follow-up for a while.  I have successfully run at least the basic tutorials exercise, which in the latest versions does use PI and the P4Runtime API to configure bmv2 switches, so the latest install scripts as of now can work, at least most of the time if not 100% of the time, when the README directions are followed.

**Comment by jafingerhut** [comment]
Antonin's answer in an earlier comment here is still true, and I would recommend considering following one of the links there to either (a) get a script that you can run on an fresh Ubuntu Linux system to build the open source P4 development tools from scratch, or (b) download a VM image where they have already been compiled for you: https://github.com/p4lang/tutorials/issues/417#issuecomment-864205105
