### ISSUE TITLE
Combining MRI and P4runtime tutorials 

### ISSUE THREAD

**Issue by yiwenshen92** [p4lang/tutorials#418]
Hi, I'm just starting out with p4lang and after finishing the MRI and p4runtime tutorials I thought to combine the code from the two tutorials so that I could use the controller to add table entries as well as perform MRI on tunneling packets. Basically I have a .p4 file that has both the MRI functionality and ability to get input from controller for tunneling, I have mycontroller.py from the p4runtime tutorial to add table entries, and I have send.py and receive.py from the MRI tutorial to test MRI functionality.

I can ping between h1 and h2 but when I run the send.py and receive.py, the swtrace for the MRI part is always empty. Comparing the s1.log files of the regular MRI tutorial and my code, I find that it says

Regular MRI tutorial s1.log:

> 2694 [19:36:32.286] [bmv2] [T] [thread 6458] [131.0] [cxt 0] mri.p4(274) Condition "hdr.mri.isValid()" (node_6) is true
> 2695 [19:36:32.286] [bmv2] [T] [thread 6458] [131.0] [cxt 0] Applying table 'MyEgress.swtrace'
> 2696 [19:36:32.286] [bmv2] [D] [thread 6458] [131.0] [cxt 0] Looking up key:
> 2697
> 2698 [19:36:32.286] [bmv2] [D] [thread 6458] [131.0] [cxt 0] Table 'MyEgress.swtrace': miss
> 2699 [19:36:32.286] [bmv2] [D] [thread 6458] [131.0] [cxt 0] Action entry is MyEgress.add_swtrace - 1,

My code with MRI and P4runtime combined s1.log:

> 2034 [19:56:30.108] [bmv2] [T] [thread 6984] [96.0] [cxt 0] advanced_tunnel.p4(333) Condition "hdr.mri.isValid()" (node_8) is true
> 2035 [19:56:30.108] [bmv2] [T] [thread 6984] [96.0] [cxt 0] Applying table 'MyEgress.swtrace'
> 2036 [19:56:30.108] [bmv2] [D] [thread 6984] [96.0] [cxt 0] Looking up key:
> 2037
> 2038 [19:56:30.108] [bmv2] [D] [thread 6984] [96.0] [cxt 0] Table 'MyEgress.swtrace': miss
> 2039 [19:56:30.108] [bmv2] [D] [thread 6984] [96.0] [cxt 0] Action entry is NoAction -
> 2040 [19:56:30.108] [bmv2] [T] [thread 6984] [96.0] [cxt 0] Action NoAction

So the difference is that the action entry in the egress pipeline should be going to add_swtrace but instead it's doing NoAction. Can anyone explain why this is happening? Many thanks.

**Comment by jnfoster** [comment]
Suggest asking this question on forum.p4.org.

Github issues are more for technical problems related to the tutorial starter code.
