### ISSUE TITLE
Range Check in Action Part

### ISSUE THREAD

**Issue by hireTutor** [p4lang/tutorials#421]
Here is the complete description of my problem, Please read it completely in help me.

What i want to do is, first check 1 field of incoming packet in Match-Part of table then i want to check another field of incoming packet in action part of same table and then set a marker field. 
After that i want to use that marker field in second table that is sequentially after the first table in pipeline and when packet goes out that marker field should be droped.                                                                     
 I will once again brief my main problems.                                                                                                                                                      1)How to do range check over any field in action part of table and how the p4 code will look. I had heard about some limit also about range check in action part, if there is something like this please enlighten about that also.                                                            2)In the same action part of, How to set marker bit/field.                                                                                                                           3)How tp use that marker field in second subsequent table.

**Comment by jnfoster** [comment]
This repository is for source code related to the P4 tutorial. 

For general programming questions like this, I recommend asking on the [P4 Forum](https://forum.p4.org) instead.
