### ISSUE TITLE
UDP/TCP traffic with advance_tunnel.p4 (P4Runtime exercise)

### ISSUE THREAD

**Issue by GiadaR95** [p4lang/tutorials#423]
I was trying to test the program with TCP traffic by using "iperf h1 h2", but the connection doesn't work. I tried also using UDP, by xterm h1 and h2 and with the commands "iperf -c  10.0.2.2 -p 100 -u " on h1 and "iperf -s -p 100 -u" on h2, but still doesn't work. 
I've implemented tcp/udp parsing on advanced_tunnel but nothing changed. I dont know if someone had this problem. Thanks in advance.

-Giada

**Comment by jnfoster** [comment]
Hi Giada,

First, I recommend asking this question on the [P4 Forum](https://forum.p4.org). 

Second, have you tried running the provided solution (in the `solution` directory)?

-N

**Comment by GiadaR95** [comment]
Yes, I already tried to run the solution, but i got the same issue. So I think that something is missing in the implementation of the tunnel. Anyway, I'll ask this question on P4 Forum. Thanks for the suggestion.

-Giada

**Comment by GiadaR95** [comment]
I've find the issue, the MSS cross the limit after the tunnel encapsulation. 
Giving the command: "# ifconfig eth0 mtu 1000" on the client terminal the program works.
Anyway, thanks for the answer.
