### ISSUE TITLE
mri hops

### ISSUE THREAD

**Issue by Vuk0dlak** [p4lang/tutorials#428]
Greetings,
I was studying the MRI exercise, and I think I found some issues. First, the maximum hop value is 9, but I think it can only do 4 hops (4 bytes (the standard option fields) + 4 hops * 8 bytes for each hop = 36 bytes). The maximum size of the options field is 40 bytes. So we must have headers of much smaller size than 32 bit to achieve the 9 hops. Furthermore, I cant understand why the IHL header starts with the value 6 and not 24.

**Comment by jafingerhut** [comment]
Feel free to follow up in forum.p4.org for such questions.

One quick answer is that these tutorials may indeed have limitations where they cannot support everything that the README claims to.  I don't know if that might even be an exercise for the reader in this case to discover that, or whether the person writing the README documentation mistakenly believed that when they wrote it.

For IHL, note that the units of the IPv4 IHL fields are in 32-bit words, not bytes.
