### ISSUE TITLE
make Digest send messages in a non-blocking way

### ISSUE THREAD

**Issue by butuizd** [p4lang/tutorials#430]
Hi everyone! I have questions about using `digest` in bmv2. Does bmv2 send digest message in a way of blocking? If so, how can I send digest message in a non-blocking way?

I did a simple experiment using `thrift_api` in which bmv2 switch will send a digest message to controller when missing a table, and controller will print some information. 

(**exp. 1**)I found that when I ping before running controller, the controller will not print any information. 
(**exp. 2**).But when I run controller before pinging, the controller will print some information 

I think the reason is:  in exp. 1, the switch sends some digest messages before running controller, the controller miss the beginning digest message and **don't response . The switch don't receive ack message and thus block subsequent digest message**, so controller will not print any information.

**Comment by butuizd** [comment]
I raised the issue on slack p4#general, `Antonin` said 

> P4Runtime defines an ack_timeout_ns: https://p4.org/p4-spec/p4runtime/main/P4Runtime-Spec.html#sec-digestentry. By default it is 0, so the switch should keep sending digests for every packet.

So now I want to search for **solutions in thrigt_api** instead of p4runtime_api.

**Comment by jnfoster** [comment]
Hi! Can you ask your question on the [P4 Forum](https://forum.p4.org)? You'll get a faster response, and it will be preserved so it can be searched and read by others in the future. This repository is only for the P4 tutorial code.
