### ISSUE TITLE
OR ascii character

### ISSUE THREAD

**Issue by totox93** [p4lang/tutorials#44]
https://github.com/p4lang/tutorials/blob/30ecf6fc07545869a9e6af6a59180dc25701cec5/P4D2_2017/exercises/calc/solution/calc.p4#L67

The ASCII of '|' should be 0x7c, not 0x7e.
Just a small thing, but obviously he will wait a '~' to do the OR as it is

**Comment by jnfoster** [comment]
Thanks! I just created a pull request that fixes this.

Cheers,
N
