### ISSUE TITLE
How can I add another controller like ONOS ?

### ISSUE THREAD

**Issue by zakariaCreate** [p4lang/tutorials#440]
Hi,

I want to add another controller like ONOS to the simulated network, and I am asking for some clear steps on the changes. I already installed ONOS on the P4 tutorial VM. Regarding connecting to the ONOS, I tried to change to the run_exercise.py in these lines (but it does not work):
            
from mininet.node import Controller, RemoteController

self.net = Mininet(topo = self.topo,
                      link = TCLink,
                      host = P4Host,
                      switch = defaultSwitchClass
                      controller = RemoteController)
                      self.net.addController('c1',
                                controller = RemoteController,
                                ip = "127.0.0.1",
                                port = 6653)

Thank you.

**Comment by faliakbari** [comment]
Dear all, 

I have the same problem. I appreciate it if you would guide me how I can add ONOS to the P4 tutorial. 

Best regards, 
Fatemeh

**Comment by jnfoster** [comment]
I think this question may be better suited for ONF developers. 

Consider asking here?

https://github.com/opennetworkinglab/ngsdn-tutorial

**Comment by faliakbari** [comment]
Dear Nata,

Thank you for email. I worked with ngsdn-tutorial including the ONOS
container, but right now I am trying to add the ONOS controller in the P4
tutorial VM, instead of simple controller in the P4 tutorial. I was
wondering if you would help me to find the answer.

Best regards,
Fatemeh

**Comment by jnfoster** [comment]
I'm not sure what "the answer" is... The tutorial VM and the ONF NG-SDN VM both use Mininet and Bmv2. In principle, you could port the exercises to that architecture. But it would take some work.

I don't think it would be easy to install ONOS on this VM and get everything to work...

I can say this currently isn't a priority for the volunteer group who maintains the tutorial materials. 

I would ask the ONF folks if they want to take this on, or perhaps ask on the [P4 Forum](https://forum.p4.org).

**Comment by faliakbari** [comment]
Thank you so much for your consideration.
