### ISSUE TITLE
If I write the code in ingress's apply, how will it be implemented? 

### ISSUE THREAD

**Issue by Jinghui-Jiang** [p4lang/tutorials#441]
Hi,
If I write the code in ingress's apply, how will it be implemented? Is it deployed as something like action? I wrote some code in ingress's apply and reported the following error (I did not explicitly call table):
![image](https://user-images.githubusercontent.com/84329935/141604067-58c4b870-3380-4a70-b6cf-5738be88658f.png)

**Comment by jfingerh** [comment]
If this is while using Tofino's development tools, I would recommend asking in Intel-specific support forums for Intel.

If this is using open source P4 development tools, I would recommend asking on forum.p4.org.  Others will be able to help you more if you are willing to publish the P4 program you are using as part of your question, e.g. as a link to some public Github repo where you have committed your code.

**Comment by jafingerhut** [comment]
Closing this issue, as I think it has been addressed as much as it can be without further follow-up in Intel-specific forums.  forum.p4.org is also recommended for general P4 questions.
