### ISSUE TITLE
Something went wrong when "vagrant up"

### ISSUE THREAD

**Issue by TreeFalling** [p4lang/tutorials#442]
![MFE5(C }TCPJHTWZ{ D $I](https://user-images.githubusercontent.com/42139893/141937737-803e6f27-5e5d-4141-bcf6-8601018198d4.png)
I've tried many times but every time it issues this error

**Comment by jfingerh** [comment]
Did you run `vagrant up` from the directory `vm`, or the directory `vm-ubuntu-20.04` ?

I have tested it in `vm-ubuntu-20.04` recently and have never experienced that problem.

The `vm` directory is there primarily for historical interest now.  The top level README instructions no longer mention it, and the README in the `vm` directory says it is only of historical interest.

**Comment by jfingerh** [comment]
The error message you show suggests that the reason for the failure is that there is no `python3` command installed on the system.  As far as I know, `python3` is installed by default on all version of Ubuntu 20.04  (i.e. 20.04, 20.04.1, 20.04.2, etc.).  If the `vagrant up` script is somehow getting a different version of Ubuntu that doesn't have `python3` installed on it, I have never seen that happen, and not sure why it would.  Have you modified any of the files in your copy of the tutorials repository?  What are the outputs of these commands when run from the root directory of your copy of the tutorials repo?

```
git log -n 1 .
git status .
```

**Comment by rst0git** [comment]
From the screenshot I can see that Vagrant has failed to run the `py3localpath.py` script. This script is only in `vm-ubuntu-20.04`.

However, it looks like you are building the VM on Windows and this may be the reason for the error:

https://www.vagrantup.com/docs/provisioning/shell#inline-scripts

> For Windows guest machines, the supported inline script is dependent upon the communicator in use. When using the winrm communicator, the inline script must be PowerShell. Batch scripts are not allowed as inline scripts when using the winrm communicator. When using the winssh communicator, the inline script will be run using the configured shell which defaults to PowerShell.

**Comment by TreeFalling** [comment]
It seems that the problem is the line ending characters. I've just converted the .py file from CRLF to LF and it run successfully. TKS!

**Comment by jafingerhut** [comment]
Glad you found the issue.  I just double-checked, and the latest versions of the files checked into this repository have only LF line endings, except for the LICENSE file, which isn't executable code.  If you had CRLF in any Python files, I suspect that might be because of the way your 'git' on Windows is configured to transform text files, and/or you might have edited and saved the file using a Windows text editor?

**Comment by TreeFalling** [comment]
@jafingerhut I just tested about this and the reason should be the former one——git on windows will transform text files to CRLF automatically without git status change...... （missing my MacBook  o_O
