### ISSUE TITLE
UNFIXED: uninitialized parser value error

### ISSUE THREAD

**Issue by causimmi** [p4lang/tutorials#445]
I want to ask a general question, which is when I compile a statement

### 
state parse_srv6_list {      
      packet.extract(hdr.srh_segment_list.next);      
      bool next_segment = (bit<32>)hdr.srh. seg_left - 1 == (bit<32>)hdr.srh_segment_list.lastIndex; 
      transition select(next_segment) {
            true: mark_current_srv6;
            default: check_last_srv6; 
} 
### 

`error:` Use of uninitialized parser value  [ ingress::parse_srh : (bit<1>)(0 == ingress::hdr_0_srh_segment_list. lastIndex[31:8] && ingress::hdr_0_srh. seg_left == ingress::hdr_0_srh_segment_list.lastIndex[7:0]); (bit<1>)(0 == hdr_0_srh_segment_list. lastIndex[31:8] && hdr_0_srh. seg_left == hdr_0_srh_segment_list.lastIndex[7:0]); ] Number of errors exceeded set maximum of 1  `

I don‘t know how to fix it, could you please help me to solve this issue? thanks a lot.

**Comment by causimmi** [comment]
### hdr.srh. seg_left is ’ bit<8> ‘ type

**Comment by jnfoster** [comment]
Hi! Can you ask your question on the [P4 Forum](https://forum.p4.org)? That's a better place than on this repository, which I don't believe implements SR V6.

**Comment by causimmi** [comment]
thanks a lot
