### ISSUE TITLE
There is nothing in /tmp/p4s.s1.log

### ISSUE THREAD

**Issue by zhma989** [p4lang/tutorials#447]
When I was doing exercise source_routing,  I found there is nothing in `/tmp/p4s.s1.log` no matter the switch was programmed with incomplete starter code or completed p4 code. 

But the README of exercise source_routing writes "You can verify this by looking at `/tmp/p4s.s1.log`". 

Has anyone else had this problem? Thanks.

![image](https://user-images.githubusercontent.com/96609799/149946365-12ac290f-cb89-485d-9464-881b7cb2be24.png)

**Comment by rst0git** [comment]
@zhma989 It looks like since commit https://github.com/p4lang/tutorials/commit/76a9067deaf35cd399ed965aa19997776f72ec55 all switch log files have been moved into the `logs` folder:
```diff
-The `/tmp/p4s.<switch-name>.log` files contain detailed logs
+The `logs/sX.log` files contain detailed logs
```
However, not all README files have been updated. I have opened a pull request to update all the README files:

**Comment by zhma989** [comment]
Thanks for your comment.
