### ISSUE TITLE
error: unknown option --p4runtime-files

### ISSUE THREAD

**Issue by Archor001** [p4lang/tutorials#450]
![图片](https://user-images.githubusercontent.com/60682236/153720226-6f1f727c-26b7-4d38-8739-1552347965b7.png)

only "--p4runtime-file" available, how can I use "--p4runtime-files" in the Makefile?

**Comment by rst0git** [comment]
@Archor001 the `--p4runtime-files` option has been introduced with this commit https://github.com/p4lang/p4c/commit/117a92221aa107dac5ca204669c54e8cb258ca1e

**Comment by Archor001** [comment]
Thanks to both of the contributors above, I'll see what I can do
