### ISSUE TITLE
How to import P4 switch to the miniEdit?

### ISSUE THREAD

**Issue by chandaweia** [p4lang/tutorials#456]
Hi,

I'm learning about the P4 and watch videos and documents. However, I'm confused about the first picture. I could run miniedit as the second picture without P4Switch button but I can't import the P4Switch button to the miniedit unless accessing to the programmable switches workshop platform(3rd picture). Can I have the similar environment as the first picture in my own machine? I really appreciate your help!
<img width="526" alt="image" src="https://user-images.githubusercontent.com/22185737/158250422-caea035f-d7f1-48aa-94b1-88084b92b4bd.png">
<img width="383" alt="image" src="https://user-images.githubusercontent.com/22185737/158251481-a22db707-d843-4acc-82c0-ac34d5ffb35d.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/22185737/158250881-20650b19-76f2-460f-84f4-bd74726b8378.png">

**Comment by jafingerhut** [comment]
I suspect the reason there are no responses to this question are that most people have not used miniEdit before (I have not).  The tutorials repository comes with some tesxt scripts and configuration files that are used by mininet to construct small virtual networks of hosts, switches, and links between them, and I believe most people who want to change these do so by editing those text files.

**Comment by chandaweia** [comment]
> I suspect the reason there are no responses to this question are that most people have not used miniEdit before (I have not). The tutorials repository comes with some tesxt scripts and configuration files that are used by mininet to construct small virtual networks of hosts, switches, and links between them, and I believe most people who want to change these do so by editing those text files.

Yeah. I think so and I would use the similar way to build my virtual networks. But I'm still curious about how to import P4 switch to miniEdit because it seems really easy to do that. 😁

**Comment by bibo7086** [comment]
As mentioned in the example containing miniEdit, It "is a simple demonstration of how one might build a
GUI application using Mininet as the network model". If you want something more advanced you would have to extend the miniEdit yourself to include a P4 switch similar to the first image you included. You should note that the P4 switch is run using containers (Docker) and by pushing your p4 program to the switch. Something similar has been done in the FOP4 project allowing you to use P4 enabled switches in mininet topologies (or directly using miniEdit), which you can find here: https://github.com/ANTLab-polimi/FOP4.
