### ISSUE TITLE
p4.config Module Not Found

### ISSUE THREAD

**Issue by RaihanHeggi** [p4lang/tutorials#462]
Hello, I'm just trying to install P4 Development Tools, I'm following this step (https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md) for the information I'm installing using install-p4dev-v4.sh on Ubuntu 18.04, then I'm want to try my P4 Development tools installed correctly, p4c is fine, but when I'm trying to run basic tutorials, the system gives back error ModuleNotFound: no modules named p4.config, what the cause of the problem and how to solve this problem.

![error_p4](https://user-images.githubusercontent.com/58820833/161465412-2d50c3e3-e9fd-4b01-80a3-a8c8fedd8439.PNG)

I'm sorry if this issue is not in the correct place but I think this is related to tutorials. 

Thanks,
Heggi

**Comment by jafingerhut** [comment]
I last tested my install-p4dev-v4.sh script on a _freshly installed_ Ubuntu 18.04 system about a week ago, and it ran the basic exercise `make run` just fine, with no error like the one you showed.

When you ran the install-p4dev-v4.sh script, did you save its output in a file as recommended in the instructions?  If you still have a copy of that file, I could compare it against the one I saved on my last run to see if there are any noticeable differences, e.g. perhaps when you ran it there was some error that did not occur when I last ran that script.

**Comment by RaihanHeggi** [comment]
yes, I'm saving the log file when I'm running the script, I'm attaching the log file in this response or you can access it on this [Link](https://drive.google.com/file/d/1FEj1I_Z5yhLXOmpZRTzEySCFFxmHGj10/view?usp=sharing) if the file did not show up.

[log.txt](https://github.com/p4lang/tutorials/files/8406993/log.txt)

**Comment by jafingerhut** [comment]
One difference I noticed so far is that your Ubuntu 18.04 system had Python 2 installed when running the install script.  Python 2 is end of life as of 2020-Jan-01, and my install-p4dev-v4.sh script is written assuming that Python2 is not installed on the system when it starts.  If you can try it on a system that does not have Python 2 installed, I suspect you will have better results.

As mentioned on this page, you can also download a VM image with the open source P4 software already compiled and installed, and run the VM image on VirtualBox (and perhaps other VM software like VMware Fusion, Parallels for Mac, VMware workstation, etc., although I have not tested that myself): https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by RaihanHeggi** [comment]
Okay, I will try to reinstalling again with fresh Ubuntu 18.04 and make sure didn't have Python 2 installed, I will close this issue after that, Thanks for your advice
