### ISSUE TITLE
no matching function for call SetTotalBytesLimit(int, int) in building grpc

### ISSUE THREAD

**Issue by sschaud2** [p4lang/tutorials#468]
Hi,
I am setting up P4 tutorial environment on my Ubuntu server (**not VM**). 
**OS version: Ubuntu 20.04.4 LTS**
Release:	20.04
Codename: focal
For this I'm following scripts in tutorial/vm-ubuntu-20.04 and executed scripts in following sequence:

1. root-dev-bootstrap.sh

2. user-dev-bootstrap.sh

For user-dev-bootstrap.sh, I got errors while building grpc while executing statement "sudo make install". Following are the errors:

In file included from /afs/unity.ncsu.edu/users/s/sschaud2/tutorials/vm-ubuntu-20.04/grpc/gens/src/proto/grpc/core/stats.grpc.pb.h:29,
                 from /afs/unity.ncsu.edu/users/s/sschaud2/tutorials/vm-ubuntu-20.04/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:6:
include/grpcpp/impl/codegen/proto_utils.h: In function ‘grpc::Status grpc::GenericDeserialize(grpc::ByteBuffer*, grpc::protobuf::Message*)’:
include/grpcpp/impl/codegen/proto_utils.h:86:48: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)’
   86 |     decoder.SetTotalBytesLimit(INT_MAX, INT_MAX);
      |                                                ^
In file included from /afs/unity.ncsu.edu/users/s/sschaud2/tutorials/vm-ubuntu-20.04/grpc/gens/src/proto/grpc/core/stats.pb.h:23,
                 from /afs/unity.ncsu.edu/users/s/sschaud2/tutorials/vm-ubuntu-20.04/grpc/gens/src/proto/grpc/core/stats.grpc.pb.cc:5:
/usr/local/include/google/protobuf/io/coded_stream.h:401:8: note: candidate: ‘void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’
  401 |   void SetTotalBytesLimit(int total_bytes_limit);
      |        ^~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/io/coded_stream.h:401:8: note:   candidate expects 1 argument, 2 provided

Protobuf is already installed making grpc.

**Comment by jafingerhut** [comment]
I have never tried following the steps you have on a system before, so my advice is quite limited.

Did you start from a freshly installed Ubuntu 20.04 system, i.e. one that had just been installed, with no extra packages installed except perhaps for a few things like git, curl, etc.?  If there was already a bunch of packages or other software installed on the system, any of them might conflict with assumptions made by these scripts.  When developing these install scripts, no attempt has been made to try to make them work for arbitrary sets of packages that might have been installed on top of a freshly installed Ubuntu 20.04 system.

**Comment by sschaud2** [comment]
It is not freshly installed system and there is good possibility that it had some conflicting packages. If I start with freshly installed Ubuntu 20.4, what steps would you recommend?

**Comment by jafingerhut** [comment]
If you have a freshly installed Ubuntu 20.04 system, I would recommend one of the scripts described on this page: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md. I test those every month and update them if they need changes to keep working.

I would guess that the scripts in this repository can also be made to work -- I just have not tested exactly which sequence of commands work myself.

**Comment by sschaud2** [comment]
Thanks! I will try this. I was using VM with its default memory setting and made a few topology changes in the exercise programs. Due to long logs I guess, my VM stopped working and it is not booting up. It throws a "no space left error". Can you help me to understand the way I can make it work? Can I recover it?

**Comment by sschaud2** [comment]
I am trying to follow process you recommended:
1. I cleaned the python2 related packages and protobuf package I installed on my server. 
2. Followed the instructions here  https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md.
3. Since my OS is ubuntu 20.04, I used script "install-p4dev-v5.sh". I got following error:

**sudo apt-get update -qq
E: The repository 'http://ppa.launchpad.net/blue-shell/sddm/ubuntu focal Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/hermlnx/xrdp/ubuntu focal Release' does not have a Release file.**

Adding output added to log file for your reference:
------------------------------------------------------------------------------------------------------------------
Found distributor 'Ubuntu' release '20.04'.  Continuing with installation.
Minimum recommended memory to run this script: 1920 MBytes
Memory on this system from /proc/meminfo:      15761 MBytes -> enough
Minimum free disk space to run this script:    2560 MBytes
Free disk space on this system from df output: 382165 MBytes -> enough
Found directory containing patches: /afs/unity.ncsu.edu/users/s/sschaud2/p4-guide/bin/patches
Passed all sanity checks
+ set +x
This script installs pre-compiled Debian packages of the P4_16 (and
also P4_14) compiler, and the behavioral-model software packet
forwarding program, that can behave as just about any legal P4
program.

It is regularly tested on freshly installed Ubuntu 20.04 systems,
with all Ubuntu software updates as of the date of
testing.  See this directory for log files recording the last
date this script was tested on its supported operating systems:

    https://github.com/jafingerhut/p4-guide/tree/master/bin/output

As of 2021-Nov-14, the files installed by this script consume about 2
GB of disk space.  Running the script downloads about 250 MBytes of
data from the Internet.

On a 2015 MacBook Pro with a decent speed Internet connection
and an SSD drive, running Ubuntu Linux in a VirtualBox VM, it
took about 3 minutes.

------------------------------------------------------------
Time and disk space used before installation begins:
+ date
Thu 28 Apr 2022 11:43:44 PM EDT
+ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  468G   71G  374G  16% /
+ df -BM .
Filesystem     1M-blocks   Used Available Use% Mounted on
/dev/nvme0n1p2   479191M 72617M   382165M  16% /
+ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
+ python -V
./p4-guide/bin/install-p4dev-v5.sh: line 170: python: command not found
+ echo 'No such command in PATH: python'
No such command in PATH: python
+ python2 -V
./p4-guide/bin/install-p4dev-v5.sh: line 171: python2: command not found
+ echo 'No such command in PATH: python2'
No such command in PATH: python2
+ python3 -V
Python 3.8.10
+ pip -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
+ pip2 -V
./p4-guide/bin/install-p4dev-v5.sh: line 174: pip2: command not found
+ echo 'No such command in PATH: pip2'
No such command in PATH: pip2
+ pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
+ sudo apt-get install -qq -y --no-install-recommends --fix-missing curl git wget
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 741967 files and directories currently installed.)
Preparing to unpack .../curl_7.68.0-1ubuntu2.10_amd64.deb ...
Unpacking curl (7.68.0-1ubuntu2.10) over (7.68.0-1ubuntu2.7) ...
Preparing to unpack .../libcurl4_7.68.0-1ubuntu2.10_amd64.deb ...
Unpacking libcurl4:amd64 (7.68.0-1ubuntu2.10) over (7.68.0-1ubuntu2.7) ...
Setting up libcurl4:amd64 (7.68.0-1ubuntu2.10) ...
Setting up curl (7.68.0-1ubuntu2.10) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ echo 'deb http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/ /'
+ sudo tee /etc/apt/sources.list.d/home:p4lang.list
deb http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/ /
+ wget -qO - http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/Release.key
+ sudo apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
+ sudo apt-get update -qq
E: The repository 'http://ppa.launchpad.net/blue-shell/sddm/ubuntu focal Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/hermlnx/xrdp/ubuntu focal Release' does not have a Release file.

**Comment by jfingerh** [comment]
@sschaud2 I saw an email notification on this issue where it appears that you sent some details about an experiment you tried of removing a few packages, then running some of the scripts, and an error message you got.

My best guess is that whatever you did to remove some packages got your system closer to the state of a freshly installed Ubuntu 20.04 system, but not close enough for the scripts in this repo to work.

I test these scripts only on freshly installed Ubuntu Linux system with the stated version.  There is no way anyone can test all possible variations of packages or configuration changes that might be made to a system after it is freshly installed.  There are too many such variations to test.  I am sorry, but I have no interest in taking the (perhaps large) time required to debug exactly what might be different between your system and a freshly installed system.

If you can actually try these scripts on a freshly installed system, I recommend trying that.  Otherwise, these scripts are provided as is.

**Comment by sschaud2** [comment]
Hi, I am sorry for the confusion. 
I got some errors in sudo apt-get update. But I resolved it. I removed "-qq" option in the command to see the logs. I identified the problem. It was a local issue and was not related to the P4 environment. Since it was not related to this repo, I deleted it from this page. 
With that experience, I understand that it is not possible to test all possible variations and it depends on the local packages.
**Update**: After resolving my local issue, I got my script running without errors. But I am still working on it as I could not run the example program from the exercise folder.

**Comment by sschaud2** [comment]
Hi,

I used script install-p4dev-v6.sh and followed instructions from README-install-troubleshooting.md to install P4 related packages and P4 tutorial repository on **freshly installed Ubuntu 20.04**. It worked smoothly without any error and I can run the P4 tutorial programs on my system without VM.

Thanks, @jafingerhut for your support.
