### ISSUE TITLE
trying with tutorials

### ISSUE THREAD

**Issue by ham-xa** [p4lang/tutorials#469]
Is there any complete guide that doesn't link to other links?
I've made a Ubuntu 20.04 Vm in my server not using the vagrant as I use virtual instances. So, after I've cloned the tutorials repo and I installed the P4c and some more dependencies I faced an error that I'm unable to resolve. 
File "../../utils/run_exercise.py", line 29, in <module>
from mininet.cli import CLI
ModuleNotFoundError: No module name 'mininet.cli'
make: *** [../../utils/Makefile:35: run] Error 1

@jafingerhut Can you please help me here?
Thanks.

**Comment by rst0git** [comment]
> I've made a Ubuntu 20.04 Vm in my server not using the vagrant as I use virtual instances.
> ModuleNotFoundError: No module name 'mininet.cli'

@ham-xa This error indicates that mininet has not been installed. Andy recently updated the installation steps for mininet (https://github.com/p4lang/tutorials/pull/464) to fix similar problem. You can find the steps executed by vagrant to install mininet in [user-common-bootstrap.sh](https://github.com/p4lang/tutorials/blob/7e2ae40cbde87a23faf5abb24cd9bad11c77b613/vm-ubuntu-20.04/user-common-bootstrap.sh#L6L16).
