### ISSUE TITLE
Try to print the flowID in the log

### ISSUE THREAD

**Issue by 529669517** [p4lang/tutorials#471]
Hi,

I am trying to print the flow ID (source and dst ip address, port, protocal).

I create a table with the five keys.
![image](https://user-images.githubusercontent.com/45109782/170862454-e9e7a027-ad24-44a5-95ac-a6f2489631f0.png)

However, in the log, it didn't show the original format like 192.168.3.0. 
I guess it is hexadecimal format.
![1653818232(1)](https://user-images.githubusercontent.com/45109782/170862383-7c8f19ea-720f-4c7f-934b-ac001f227e22.png)

Is there any way to print the ip address like 192.168.3.0. 

Thanks

**Comment by jnfoster** [comment]
One of the "P"s in "P4" stands for protocol-independent. The language doesn't know anything about IP addresses, though it gives you the features to implement RFC-compliant IPv4 processing. Anyway, the Bmv2 software switch doesn't do anything special for 32-bit values that happen to be in a header whose name is "ipv4." It just prints them as hex.

I'd suggest writing a script to post-process the logs if this is important for your situation...
