### ISSUE TITLE
Make sure the switch is running and that you have the right port

### ISSUE THREAD

**Issue by onlyone-i** [p4lang/tutorials#477]
In the basic experiment, using `simple_switch_CLI --thrift-port 9090` does not allow access to the switch management interface，and the tips returned are as follows:
```
p4@p4-virtual-machine:~/P4/tutorials/exercises/basic$ simple_switch_CLI --thrift-port 9090
Could not connect to any of [('127.0.0.1', 9090)]
Could not connect to thrift client on port 9090
Make sure the switch is running and that you have the right port
```

`make run`  executed successfully, and accessed to the mininet control interface:

```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 h3 h4 
h2 -> h1 h3 h4 
h3 -> h1 h2 h4 
h4 -> h1 h2 h3 
*** Results: 0% dropped (12/12 received)
mininet> 
```

**Comment by jafingerhut** [comment]
I just downloaded both of the VM images built from the scripts in this repo on 2022-Sep-01 from this web page: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

I installed the VM images using VirtualBox, logged into the user account `p4`, ran these commands:
```
cd tutorials/exercises/basic
cp solution/basic.p4 .
make run
```
then I created a separate terminal window and ran the command:
```
simple_switch_CLI --thrift-port 9090
```
and it connected successfully.

Those VMs were created by running these commands using the latest versions of the files in these repos as of 2022-Sep-01:
```
cd vm-ubuntu-20.04
vagrant up
```
What steps did you follow to create the system where you saw the results in your comment?

**Comment by onlyone-i** [comment]
> I just downloaded both of the VM images built from the scripts in this repo on 2022-Sep-01 from this web page: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
> 
> I installed the VM images using VirtualBox, logged into the user account `p4`, ran these commands:
> 
> ```
> cd tutorials/exercises/basic
> cp solution/basic.p4 .
> make run
> ```
> 
> then I created a separate terminal window and ran the command:
> 
> ```
> simple_switch_CLI --thrift-port 9090
> ```
> 
> and it connected successfully.
> 
> Those VMs were created by running these commands using the latest versions of the files in these repos as of 2022-Sep-01:
> 
> ```
> cd vm-ubuntu-20.04
> vagrant up
> ```
> 
> What steps did you follow to create the system where you saw the results in your comment?

I have used steps from elsewhere and may have missed something, I am going to check against the steps you mentioned and see if I can find the problem.Also, I see the following hint in the logs and wonder if it has anything to do with the issue.
`[21:22:53.335] [bmv2] [W] [thread 30300] You used the '--thrift-port' command-line option, but this target was compiled without Thrift support. You can enable Thrift support (not recommended) by providing '--with-thrift' to configure.`

**Comment by jfingerh** [comment]
That message in the log is a sign that `simple_switch_grpc` was built in a way that did not enable the Thrift server.  The current build scripts do enable it, as you can see here (the `--with-thrift` option to `configure`): https://github.com/p4lang/tutorials/blob/master/vm-ubuntu-20.04/user-dev-bootstrap.sh#L176

**Comment by onlyone-i** [comment]
> That message in the log is a sign that `simple_switch_grpc` was built in a way that did not enable the Thrift server.  The current build scripts do enable it, as you can see here (the `--with-thrift` option to `configure`): https://github.com/p4lang/tutorials/blob/master/vm-ubuntu-20.04/user-dev-bootstrap.sh#L176

Then I should have found the problem, which I have solved so far.
I missed the parameter `--with-thrift` option to `configure`.
