### ISSUE TITLE
Broadcast, Queue Size and Global Data

### ISSUE THREAD

**Issue by NofelYaseen** [p4lang/tutorials#48]
As I understand, the features like broadcast, obtaining buffer queue size and registers for storing global data are architecture specific. 
Right now I am still learning how to make p4 work with mininet and bmv2 simple switch as given in the tutorials.

Do we have any way to do broadcast, obtain buffer queue size (individual for each port or combined, whatever way is the implementation) and store global variables (do not change with packet) in the simple switch?

It might be out of scope here because it is related to mininet, let me know if its possible to run separate p4 file in each mininet switch. The way it is set right now /tutorials/P4D2_2017/utils/mininet/* is to pass P4switch object to mininet.

**Comment by jnfoster** [comment]
Yes, please consult the architecture used in these exercises, which is
v1model.p4. It has features to support all of these things.

-N

**Comment by NofelYaseen** [comment]
Thank you for the reply, I was able to figure these out. Another thing I would like to know if its possible to retrieve the counter value inside the program.

https://github.com/p4lang/tutorials/tree/master/examples/counter

This example uses CLI to read the counter value. I would like to put the counter value in a packet header.

**Comment by jafingerhut** [comment]
@NofelYaseen By design, P4 counters can only be read from the control plane -- the current value of the counters are not visible from the P4 program.

If you want a counter that you can see the value of from within the P4 program, you may implement it using a Register.

**Comment by NofelYaseen** [comment]
@jafingerhut Thanks for the suggestion. Is there any function to reset the entire register to 0?
I am using v1model for now:
https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4

**Comment by jafingerhut** [comment]
I am not aware of such a function.  Using the control plane API for writing each element of the register to 0, and iterating over all indices, should achieve that goal.
