### ISSUE TITLE
Can P4 support parallel execution of match action tables?

### ISSUE THREAD

**Issue by 529669517** [p4lang/tutorials#484]
Hi,

When I review the classical P4 paper of 2014.
The paper said P4 can support the parallel execution of match action tables, like the following,

![11f35511d0ddee718bd6bb3ca3f0ed5](https://user-images.githubusercontent.com/45109782/195232565-329cefe9-106f-4762-8868-dcb16f133ac9.png)
![1d11689bbb7c0b68dd94e69362d8f4d](https://user-images.githubusercontent.com/45109782/195232580-b629b17d-38b6-4adc-ad43-1825ac10df9f.png)
![fcf807aa4cf3cd3bd1680e141d32eb3](https://user-images.githubusercontent.com/45109782/195232587-d944826b-9e84-40e0-9f4d-339d7d8af039.png)

However, I cannot find any discussion about the parallel execution in the latest P4-spec version.
I am curious about if P4 still supports the parallel execution of match action tables.
Also, the parallel execution of primitives within an action function?

Thanks,

**Comment by jnfoster** [comment]
This kind of question is probably better asked on the [P4 Forum](https://forum.p4.org). 

But while we are here: P4 now mandates sequential semantics for actions (and most other constructs). See Section 12.3 of the specification.

Note that this does not preclude a compiler from generating code that executes in parallel on a given machine. Indeed, almost all high-speed P4 targets rely on parallelism to get good performance. But the semantics of an action -- whether or not it is executed in parallel or not -- will be consistent with a sequential execution of the statements in its body.
