### ISSUE TITLE
run_exercise.py error: argument --behavioral-exe 

### ISSUE THREAD

**Issue by lululouisa** [p4lang/tutorials#485]
when i tried to use simple_switch_mininet.py, there is always error about argument --behavioral_exe is required. 
What should i do ?

**Comment by jnfoster** [comment]
Perhaps try using the `Makefiles` supplied with each exercise? Those provide all of the necessary arguments to other scripts like `simple_switch_mininet.py`. And you can generalize from there...

**Comment by jnfoster** [comment]
To answer the specific question: you need to provide the path to the Bmv2 switch, which is usually the binary `simple_switch`.

**Comment by lululouisa** [comment]
![image](https://user-images.githubusercontent.com/116613808/197671459-7119dc99-cd22-4ec9-a952-f6d486efab24.png)
yes, i add the argument about the BMv2 on the top of Makefile, but leider it doesnt work.
![image](https://user-images.githubusercontent.com/116613808/197671630-54983a9d-0b7d-44c8-b9f7-2b176637fa08.png)

**Comment by lululouisa** [comment]
Sorry, i am not sure how to provide the path to the BMv2 switch.
Yes, in original run_exercise.py for multiple switch, there is a default='simple_switch' in args part. However, i dont know how to add them into simple_switch_mininet.py

**Comment by jafingerhut** [comment]
Are you running an unmodified exercise that is currently checked into the latest version of this p4lang/tutorials repo?  The directory name shown in your screen shot does not look like the directory name of anything in the repo.

**Comment by lululouisa** [comment]
i rename them by myself. I clone the untils and vm to my local and tried a basic forwarding exercise now.

**Comment by jnfoster** [comment]
I think what Andy is asking: can you try running `make run` on an *unmodified* tutorial exercise, like `basic`?

(Also, I remembered that the switch binary is probably `simple_switch_grpc`.)

**Comment by lululouisa** [comment]
When i make run with original topology.json and original run_exericese.py (3hosts with 3 switches) on basic.p4, it works and ping sucessful.

**Comment by lululouisa** [comment]
emmm, i tried both of simple_switch and simple_switch_grpc, however didnt work~~

**Comment by jnfoster** [comment]
Good!

Obviously something has changed in going from the tutorial code to your custom program and the tutorial code... likely in the Makefile. if you can figure out what that is, you should be able to diagnose the issue.

**Comment by lululouisa** [comment]
whether the p4runtime_lib necessary for basic forwarding？

**Comment by jnfoster** [comment]
Yes.
