### ISSUE TITLE
Unwanted packets during the p4 in mininet

### ISSUE THREAD

**Issue by lululouisa** [p4lang/tutorials#488]
Hello everone,

There are always some unwanted packets like the below picutre, that created by unknown source when i tried to test my p4 code in the miniet. 
![1669733527203](https://user-images.githubusercontent.com/116613808/204561738-1c945ea9-c907-40fa-b88c-57ef7abd3626.png)
However, when i used the tcpdump to monitor the interface of p4switch" s1-eth1" and "s1-eth2", there are no packets like them.
Could you help me to avoid these packets?

Thank you~

Louisa

**Comment by jafingerhut** [comment]
I would recommend posting your question here instead https://forum.p4.org/ because there are likely more people participating there than there are on tutorials Github issues.
