### ISSUE TITLE
There's a possibility to execute the heavy_hitter project on simple_router

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#49]
Hi,
I try to perform manually the project heavy_hitter and exactly ''counter_example''
https://github.com/p4lang/tutorials/tree/master/SIGCOMM_2016/heavy_hitter/counter_example
on simple router.

1.       I compile heavy_hitter.P4 to have json file : **OK**
2.       When I type the following commande:
sudo python 1sw_demo.py --behavioral-exe ../targets/simple_router/simple_router --json ../targets/simple_router/heavy_hitter.json

It gives me an error '' p4 switch s1 did not started correctly "

Please What is the problem exactly

**Comment by antoninbas** [comment]
That's easy. heavy_hitter.p4 was written for simple_switch, not simple_router. They are 2 different architectures and support different sets of P4 programs.

**Comment by Safaamahrach** [comment]
I m working on Ubuntu server so I havn't the possibility to download the project from github. 
Thus I try to run manually heavy_hitter project on standard behavioral model environment used for simple_router
https://github.com/p4lang/behavioral-model

Please there's possibility to get heavy_hitter project directory from github in line commande (ubuntu server)
