### ISSUE TITLE
iperf has no result

### ISSUE THREAD

**Issue by onlyone-i** [p4lang/tutorials#491]
no result after executing iperf, just like the screenshot. But, the `ping` is normal.
<img width="330" alt="Snipaste_2023-02-15_22-08-38" src="https://user-images.githubusercontent.com/58205279/219050398-4ec20908-7b8a-4dcb-9d75-e8be616263c0.png">

**Comment by jafingerhut** [comment]
I would recommend posting questions on using the tutorials repo to https://forum.p4.org, where more people read the questions there and are more likely to answer, versus questions posted here.
