### ISSUE TITLE
JSON error while make run

### ISSUE THREAD

**Issue by vertcard** [p4lang/tutorials#492]
![image](https://user-images.githubusercontent.com/125567241/219465490-4b57032b-21ac-4ea5-aee2-d29215ab2a7b.png)

cannot make run the file in this directory.

**Comment by jafingerhut** [comment]
I have tried `make run` on one of the pre-built VMs recently published, which was created by following the instructions in the top level README of this repo here: https://github.com/p4lang/tutorials#obtaining-required-software

I would recommend picking one of the methods in that section to build or download the software recommended there, and try `make run` in that directory again.  If you get a problem at that time, please state _exactly which method you used to install the P4 development tools_ in your follow-up question.  There are an unlimited variety of ways to attempt to install the P4 development tools, most of which lead to non-working systems that, in my opinion, is a waste of time to diagnose.
