### ISSUE TITLE
ModuleNotFoundError: No module named 'p4.tmp'

### ISSUE THREAD

**Issue by mwigakki** [p4lang/tutorials#493]
I have installed P4 today and want to test if my p4 works well. So, I download this tutorial and execute the easiest exercise `basic`. I run `basic` in the terminal with simply `sudo make` and I get the error reported as follow:
``` bash
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
sudo python3 ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 28, in <module>
    import p4runtime_lib.simple_controller
  File "/home/ubt/tutorials/utils/p4runtime_lib/simple_controller.py", line 24, in <module>
    from . import bmv2, helper
  File "/home/ubt/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from p4.tmp import p4config_pb2
ModuleNotFoundError: No module named 'p4.tmp'
../../utils/Makefile:35: recipe for target 'run' failed
```

I have noticed [the same issue](https://github.com/p4lang/tutorials/issues/463) So I am trying to follow his step to fix it. 
Then I find that my python repository do not have the complete p4 module! This is all my p4 module:
``` bash
ubt@ubt-vm:/usr/local/lib/python3.6/dist-packages/p4$ ls -al
total 20
drwxr-sr-x  5 root staff 4096 2月  18 15:30 .
drwxrwsr-x 67 root staff 4096 2月  18 15:31 ..
drwxr-sr-x  4 root staff 4096 2月  18 15:30 config
-rw-r--r--  1 root staff    0 2月  18 15:23 __init__.py
drwxr-sr-x  2 root staff 4096 2月  18 15:30 __pycache__
drwxr-sr-x  3 root staff 4096 2月  18 15:30 v1

```
I don't know if this is the key problem that leads to my error.
Any help is very valuable to me.
My OS is `Ubuntu18.04` and python version is 3.6.

**Comment by jafingerhut** [comment]
The recommended install instructions here suggest installing Vagrant on a base operating system, e.g. Windows, macOS, or Linux, and then running `vagrant up` to create a VM that has Ubuntu 20.04 installed on it, plus the open source P4 development tools, as described here (ignore the last paragraph, which contains obsolete instructions that should be deleted): https://github.com/p4lang/tutorials#obtaining-required-software

If you did not follow those steps, then there are many, many other things you might have done that I have no clue to guess what they might have been.  There are many things that could have gone wrong in whatever you did, if they were not exactly those steps.

Alternately, you can download a pre-built VM that follows those steps from this page, if you wish, and run them using VirtualBox.  Note that those VMs were created on a Windows system by following the recommended install steps mentioned above -- I did not do something secret to create them that you cannot find described above: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by mwigakki** [comment]
OK! I'll try it.
Thanks for your help!

**Comment by jafingerhut** [comment]
Closing this issue, as the follow-up issue for updating the README has been resolved, hence this one like is, too.  Re-open if desired, or create a new issue if a separate question arises.
