### ISSUE TITLE
How to close all logs?

### ISSUE THREAD

**Issue by whyLongWay** [p4lang/tutorials#499]
Hi, sometimes I found that log files ( including pcap and switch log ) were so big even to tens of MBs/file.  So, I want to close ALL of the logs of Mininet  and BMV2 (pcaps, switch logs and so on). How to close them all before running, and after close them,  I hope the code will not only stop  writting into log file, but also stop generating log-related variables.  Thanks.

**Comment by jafingerhut** [comment]
Are you asking for a capability where while the simple_switch_grpc process is running, you can turn logging on or off at any point in time?

As far as I know, the simple_switch_grpc process from this repo https://github.com/p4lang/behavioral-model would need to be enhanced to make that possible, unless it already has such a feature.  I would recommend asking if it already has such a feature in an issue on that repo, since experts on simple_switch_grpc capabilities might not be looking at issues on this tutorials repo.

**Comment by whyLongWay** [comment]
Maybe my question is not clear. Actually I only want to close logs of mininet and BMV2 (like  pcaps and s1.log) BEFORE running. After closing them,  I hope the code will not only write nothing into log file, but also generate no  log-related variables.

**Comment by jafingerhut** [comment]
So from the beginning of your run of a tutorial, you NEVER want to generate BMv2 logs at any time during the run?

If so, then search through all of the source files in this repo that mention command line options to BMv2 like these:

+ `--log-file <filename>`
+ `--log-flush`
+ `--log-console`

and delete those command line options.

For logs generated by Mininet, I do not know what you would need to change.

**Comment by jafingerhut** [comment]
For pcap files created by BMv2, search for command line options like `--pcap <filename>`.  The code in this repo might call that `--cap-dump <filename>` instead -- not sure why, but probably the same behavior regardless of which name you use.

**Comment by whyLongWay** [comment]
Really Thank you, I will try later.  I see in tutorials/utils/p4runtime_switch.py , there are some "log"-related variables, if I set these log variables to None, or comment these codes like below, the pcap filename and switch log filename will become None, will this close all the log ? I want to close the log also because of avoiding file IO.

And I also want to know, who (which code file)  will use these log filename after starting, if I set these filename to None, maybe there will be some errors when some code files want to use log filename? If I know who use them, I can make further code change to avoid possible error.

Line 76 (https://github.com/p4lang/tutorials/blob/master/utils/p4runtime_switch.py)
`
# self.output = open(logfile, 'w')
 #self.pcap_dump = pcap_dump
self.enable_debugger = enable_debugger
 #self.log_console = log_console

if log_file is not None:
           # self.log_file = log_file
           pass
        else:
           # self.log_file = "/tmp/p4s.{}.log".format(self.name)
          pass

`

**Comment by whyLongWay** [comment]
Really Thank you, I will try later.  I see in tutorials/utils/p4runtime_switch.py , there are some "log"-related variables, if I set these log variables to None, or comment these codes like below, the pcap filename and switch log filename will become None, will this close all the log ? I want to close the log also because of avoiding file IO.

And I also want to know, who (which code file)  will use these log filename after starting, if I set these filename to None, maybe there will be some errors when some code files want to use log filename? If I know who use them, I can make further code change to avoid possible error.

Line 76 (https://github.com/p4lang/tutorials/blob/master/utils/p4runtime_switch.py)
`
# self.output = open(logfile, 'w')
 #self.pcap_dump = pcap_dump
self.enable_debugger = enable_debugger
 #self.log_console = log_console

if log_file is not None:
           # self.log_file = log_file
           pass
        else:
           # self.log_file = "/tmp/p4s.{}.log".format(self.name)
          pass

`

**Comment by whyLongWay** [comment]
> Really Thank you, I will try later. I see in tutorials/utils/p4runtime_switch.py , there are some "log"-related variables, if I set these log variables to None, or comment these codes like below, the pcap filename and switch log filename will become None, will this close all the log ? I want to close the log also because of avoiding file IO.
> 
> And I also want to know, who (which code file in BMV2 or Mininet) will use these log filename after starting, if I set these filename to None, maybe there will be some errors when some code files want to use log filename? If I know who use them, I can make further code change to avoid possible error.
> 
> Line 76 (https://github.com/p4lang/tutorials/blob/master/utils/p4runtime_switch.py) ` #self.output = open(logfile, 'w') #self.pcap_dump = pcap_dump self.enable_debugger = enable_debugger #self.log_console = log_console
> 
> if log_file is not None: # self.log_file = log_file pass else: # self.log_file = "/tmp/p4s.{}.log".format(self.name) pass
> 
> `

Now by this way, though I cannot see switch log file and pcap files in folders, but when I start to run for 7 minutes, the memory usage is up to 88% (8.8G/10G RAM). This seems that some codes accumulate lots of varabiles waiting to write into files( maybe), but as I have commented some file address as above, what should have been written to the file keeps accumulating. By the way,  I have use" ./configure 'CXXFLAGS=-g -O3' 'CFLAGS=-g -O3' --disable-logging-macros --disable-elogger " commands to re-make install BMV2. 

So, I think I should find who generates these log variables and comment them. I found in BMV2's source code, a function named BMLOG_DEBUG_PKT generates switch's log, and I will try it later.

**Comment by jafingerhut** [comment]
@whyLongWay As far as I know, there is no software that reads these log files.  They are intended for a person to use later, if they wish, to know precisely what happened while packets were being processed.

**Comment by whyLongWay** [comment]
@jafingerhut Thanks and best regards. And, I have another seemingly unrelated question: In BMV2, there is a module called "nanomsg", what is "nanomsg" used for in BMV2? Can I turn it off by commenting some codes?

**Comment by jafingerhut** [comment]
nanomsg is the name of an open source library that BMv2 can use.  I have never used it myself, so I do not know what it is best used for.  `--nanolog` is a command line option to the `simple_switch` and `simple_switch_grpc` commands that can be used to enable nanomsg to be used for logging some kinds of events.  The output of `simple_switch_grpc --help` says that by default no nanomsg logging is enabled, if you omit the `--nanolog` command line option.

When you say that after several minutes you see something using 8.8/10 GB of memory, is that the user process `simple_switch_grpc` using that much resident memory?  Or the operating system as a whole using that much memory?  And how did you determine this?

**Comment by whyLongWay** [comment]
8.8G/10G RAM is actually used by the whole ubuntu OS, but before I start mininet and bmv2, the utilization is 1.9G/10G RAM of the whole OS. I have commented log-related codes in BMV2. I use ten hosts and ten switches in my topo. I have commented log-related codes in BMV2 and re-make it and I found that forwarding performance of switch seems to be a little faster. When I type "ecit" command in mininet shell, 8.8G/10G will reduce to 1.9G/10G which shown in ubuntu's system monitor "resource" item, but in the "process" item, no process shows such amount of RAM utilization. I think maybe scapy created so many packets, I am trying to determine which part used so many RAM.

**Comment by jafingerhut** [comment]
What command are you using, and what part of its output are you looking at, that shows 8/8/10G RAM used by the whole OS?  Are you going by the 4th line from the top of the screen while running the command `top`, for example, which looks like the example below on an Ubuntu 20.04 Linux system?

```
MiB Mem :   3923.6 total,    116.1 free,   1276.1 used,   2531.4 buff/cache
```
Or some other command's output value?

Note that if you are going by the output of the `top` command that I mentioned, that memory usage includes in-kernel caches of disk blocks for recently read and written files (see the "buff/cache" number above), and tends to grow to fill available RAM for performance reasons, and all of that file cache is deallocated automatically if a user space process needs it.  If that is the only number growing, I wouldn't worry about it.

**Comment by jafingerhut** [comment]
If the Python programs you see gradually growing in memory usage are part of this repository, then it would not surprise me at all if they have been written in a way that keeps around things in memory for a long time that is not strictly needed for correct operation, but it just happened to be written that way.  Unless someone does very long runs as you are doing, and figures out why, and comes up with proposed changes that also work correctly, but grow less in memory usage over time, such things tend not to be improved upon.  People who only do relatively short runs never notice such behavior -- i.e. for their purposes, everything is working fine.

**Comment by whyLongWay** [comment]
Thank you very much for your reply, I think it 's the time to close this issue.
