### ISSUE TITLE
problem in installing thrift and nanomsg to install BMv2

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#50]
Hi,
I followed the officiel tutorial '' https://github.com/p4lang/behavioral-model '' for installing P4/BMv2 on Ubuntu 14.04.5 LTS (desktop )
1, I installed the dependecies needed using the  install_deps.sh script.
2, I try to install the thrift and nanomsg from the /travis source 
./install-nanomsg.sh
./install-thrift.sh
./install-nnpy.sh
Then I get this message
![permission denied](https://user-images.githubusercontent.com/31244674/30222334-c2fd1412-94be-11e7-9003-8f63f35f7dc4.png)

When I try with sudo it give me " commande not found "

PLease your help

**Comment by Maikey93** [comment]
sudo bash ./install-nanomsg.sh worked for me

**Comment by Safaamahrach** [comment]
Yes it is worked for me too
thanks lot
