### ISSUE TITLE
VM Image link issue

### ISSUE THREAD

**Issue by tomsteiner1** [p4lang/tutorials#502]
Using sigcomm19 P4 tutorial in my networking class and students are reporting that the link to download VM image (option 1) is not working.

https://github.com/p4lang/tutorials/tree/sigcomm19

Can this be corrected?

Thanks.

**Comment by jafingerhut** [comment]
Someone _might_ have that particular VM image still around in order to make the link work again, but I do not.  We will see if someone else responds that has that particular version.

There is a potential issue that a few things have changed in the P4 language examples since the ones given in SIGCOMM 2019, but if you are willing to work through those differences, and maybe even consider updating any README or other instructional material for those differences, there are pre-built VM images from the latest P4 development tools source code available here, as linked in the current README of this repository: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by tomsteiner1** [comment]
Thanks for the response! 

Given the additional potential issues with changes that you mentioned is there any newer P4 tutorial/exercise I could assign (obviously I don't have a lot of time to research to find one :) )

**Comment by jafingerhut** [comment]
I have not gone through all of the steps of the latest version of the code's exercises/basic, exercises/firewall, and exercises/link_monitor directories myself with the latest P4 development tools, but I would not be terribly surprised if they just worked.  I also would not be terribly surprised if small issues arose, for which you could ask questions in issues here and others may be able to help.

The link you gave in your original issue also has instructions for creating a VM, which if I recall correctly will attempt to create a VM running Ubuntu 16.04 Linux.  I don't know if those instructions still work, but you could try creating a new VM following those steps and see what happens.

**Comment by tomsteiner1** [comment]
Thanks Andy but the problem is the VM image in option 1 - the link is not
working so the students don't have the image to work withstep

**Comment by tomsteiner1** [comment]
so .... option 1 link is not working ..... option 2 VM link working but vagrant up not working ...... no USB for option 3 :(

**Comment by jafingerhut** [comment]
If you or a TA/grad student/active-talented-student-in-your-class can use a recently built VM from 2023, and the latest version of the p4lang/tutorials repo (not the version on the sigcomm19 branch), I would recommend trying that out.  Most things should just work, I expect.  If you have trouble, please ask in an issue or comment here.

**Comment by jafingerhut** [comment]
FYI, at least for the basic forwarding exercise, I test that every month with the latest version of the VM, and I know it can ping with the solution to the exercise.

**Comment by tomsteiner1** [comment]
Thanks Andy --- is there a link to create a copy of the VM you use? Is it
then just follow the same instructions for basic forwarding exercise?

**Comment by jafingerhut** [comment]
There is a link to this page from the top level p4lang/tutorials README in the section on setting up the software, but for your convenience here is a direct link to a page I maintain that has a table with pre-built VMs running that can be loaded into VirtualBox on Windows or macOS host systems (I presume also on VirtualBox running on a Linux system, although I have not tested that myself).  They were created by running the instructions `vagrant up` or `vagrant up dev` in the p4lang/tutorials README, so contain the same software you would get following those instructions.

https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

And here is a direct link to one of the pre-built VMs, the ~2 GBytes release VM created on 2023-Mar-03: https://drive.google.com/file/d/11aFyxC9Bau2y1P60M_NtD4MDxRqsLeV2/view?usp=share_link
