### ISSUE TITLE
Run the p4c tests

### ISSUE THREAD

**Issue by OctMoonz** [p4lang/tutorials#504]
Hello，I built the virtual machine use the way below:
- Install [[Vagrant](https://vagrantup.com/)](https://vagrantup.com) and [[VirtualBox](https://virtualbox.org/)](https://virtualbox.org)
- Clone the repository
- Before proceeding, ensure that your system has at least 12 Gbytes of free disk space, otherwise the installation can fail in unpredictable ways.
- `cd vm-ubuntu-20.04`
- `vagrant up` - The time for this step to complete depends upon your computer and Internet access speeds, but for example with a 2015 MacBook pro and 50 Mbps download speed, it took a little less than 20 minutes.  It requires a reliable Internet connection throughout the entire process.

And then I want to test my P4 enviroment, so,  I log in as user vagrant (password vagrant)， and in a new terminal, execute these commands:
- git clone --recursive https://github.com/p4lang/p4c
- git clone https://github.com/jafingerhut/p4-guide
- cd p4c
- ~/p4-guide/bin/build-p4c.sh
- cd build
- make -j2 check |& tee make-check-out.txt

BUT  when I execute the commands:~/p4-guide/bin/build-p4c.sh, it shows:
![001582c5d0ff08dfcb22512bb918905](https://user-images.githubusercontent.com/108675568/226337253-c7843f2a-471e-46be-ac22-0cf036b0910e.png)

And then when I execute the commands:make -j2 check |& tee make-check-out.txt, it shows: make: *** No rule to make target 'check'. Stop.

![5b513d67954fbbd442ceee568edec02](https://user-images.githubusercontent.com/108675568/226337093-bbaf7534-3df3-4445-be78-c6d472e88eb7.png)

What's wrong? Please help me. Thank you very much.

**Comment by jafingerhut** [comment]
You should be able to do the exercises in the p4lang/tutorials repo in either the "release VM" (created with `vagrant up` command) or the "development VM" (created with `vagrant up dev` command).  Doing the exercises in the tutorials repo does not require you to run p4c's included tests.
