### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by xiaobai0102** [p4lang/tutorials#510]
I have a question to inquire about, which is whether using install-p4devv6.sh to successfully install on Ubuntu can achieve the transmission of data packets to the controller

**Comment by jafingerhut** [comment]
Yes, several PTF tests in this repository use this capability: https://github.com/jafingerhut/p4-guide

including these:
+ https://github.com/jafingerhut/p4-guide/tree/master/ptf-tests/packetinout
+ https://github.com/jafingerhut/p4-guide/tree/master/ptf-tests/registeraccess
