### ISSUE TITLE
[build error]When I want to compile the ECN project,error interrupt after I input 'make' command

### ISSUE THREAD

**Issue by ruirui-wang-study** [p4lang/tutorials#512]
Configuring switch s1 using P4Runtime with file s1-runtime.json
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 396, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 210, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 317, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 282, in program_switch_p4runtime
    p4runtime_lib.mycontroller.program_switch(
AttributeError: module 'p4runtime_lib' has no attribute 'mycontroller'
make: *** [../../utils/Makefile:35: run] Error 1

**Comment by jafingerhut** [comment]
With the latest version of the code in this p4lang/tutorials repository, and a recent version of the open source P4 development tools installed on an Ubuntu 20.04 system, I am not able to reproduce this error.

What OS are you running on?

Have you modified the code in your local copy of the tutorials repository?  Or are you trying to run the code in the tutorials/exercises/ecn directory with no changes?

How did you install the open source P4 development tools?  e.g. one of these?

+ cloned this tutorials repo and ran `vagrant up`
+ downloaded a VM image that had the tools already installed (if so, which one?)
+ some other steps?  What were they?

This page lists a couple of ways that you can get an Ubuntu 20.04 or 22.04 system into a state that has all of the P4 open source development tools installed that should be able to run _unmodified_ exercises in this repo without such errors: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by jafingerhut** [comment]
No responses for several months, so closing issue.
