### ISSUE TITLE
Output format  problem of flow table item in mycontroller.py in P4 runtime

### ISSUE THREAD

**Issue by PengYiHua2000** [p4lang/tutorials#522]
Dear friends:
        When executing mycontroller.py in solution, the number output by the terminal is not in an easy to read format. How can we ensure that the code correctly outputs the character format we need?
        Unexpected output like this:
MyIngress.myTunnel_exact:  hdr.myTunnel.dst_id '\x00d' -> MyIngress.myTunnel_egress dstAddr '\x08\x00\x00\x00\x02"' port '\x00\x01'

Thank you very much!
pengyihua

**Comment by jafingerhut** [comment]
I would recommend asking this question on this web forum, where you may find more people reading and answering than here: https://forum.p4.org

**Comment by PengYiHua2000** [comment]
Thank you very much for your kind reply. I will search this question in the forum.
