### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by LaironSk** [p4lang/tutorials#525]
Following the MRI Tutorial, this happens when I follow the instructions of README:

root@p4:/home/p4/tutorials/exercises/mri#  sudo iperf -c 10.0.2.22 -t 15 connect failed: Connection refused

This has happened many times using different instances of the tutorial VM.

**Comment by jafingerhut** [comment]
I believe there are not many people looking at Github issues on this repository prepared to answer such questions.  I would recommend asking your question on this web forum instead, where there are likely to be more people reading questions there and participating in answering similar questions: https://forum.p4.org
