### ISSUE TITLE
How to obtain higher-precision processing delay

### ISSUE THREAD

**Issue by againwq** [p4lang/tutorials#526]
Hello everyone
    I want to obtain the processing delay of my P4 program for each packet, but from the logs, I can only get millisecond-level records. How can I obtain higher-precision processing delay?

Thank you very much!

**Comment by jafingerhut** [comment]
Can you show an example of a line from a log file that shows you millisecond-level records, and which log file you found it in?  I am not recalling seeing such lines before.

**Comment by againwq** [comment]
I can see the time when a packet enters and leaves the switch port by querying the switch's log files, such as s1.log, as shown in the first line and the second-to-last line in the diagram below, from 'Processing packet....' to 'Transmitting packet......'. I approximate the difference between these two moments as the time it takes for my switch to process a data packet. However, the logs only record timestamps at the millisecond level.

![捕获](https://github.com/p4lang/tutorials/assets/108559952/5472bee2-9054-4ab9-aa64-2a5d34d1ead0)

**Comment by jafingerhut** [comment]
If you apply the following one-line change to the source code of the `behavioral-model` repository, and recompile and install it, it will report times to the nanosecond level of precision:
```
diff --git a/src/bm_sim/logger.cpp b/src/bm_sim/logger.cpp
index 6fa0984..713ad1a 100644
--- a/src/bm_sim/logger.cpp
+++ b/src/bm_sim/logger.cpp
@@ -62,7 +62,7 @@ Logger::set_logger_ostream(std::ostream &os) {
 
 void
 Logger::set_pattern() {
-  logger->set_pattern("[%H:%M:%S.%e] [%n] [%L] [thread %t] %v");
+  logger->set_pattern("[%H:%M:%S.%F] [%n] [%L] [thread %t] %v");
 }
 
 void
```

**Comment by againwq** [comment]
Thanks for your reply, it was very helpful to me !
