### ISSUE TITLE
Get queues length

### ISSUE THREAD

**Issue by MohamadAlAdraa** [p4lang/tutorials#527]
Hello,

I am a Master student and I am working to finish my research work to graduate. I have an important question and I would be thankfull for any one who can help.
when a packet comes into the switch I need to get the queue length for each egress port. And choose the link that has the shortest egress queue length.
So the main problem how can I get access to the egress ports queue length at ingress so I can based on the shortest one decide the egress port.

I am using BMV2 with v1model architecture.

I really need your help and I would highly appreciate your answer.

**Comment by jafingerhut** [comment]
I would recommend asking your question on https://forum.p4.org where more people read, and more people answer, such questions.
