### ISSUE TITLE
 make run mkdir -p build pcaps logs sudo python3 ../../utils/run_exercise.py -t topology.json -j build/ python3: can't open file '/home/chinni12/tutorials/utils/../../utils/run_exercise.py': [Errno 2] No such file or directory make: *** [Makefile:35: run] Error 2

### ISSUE THREAD

**Issue by LavanyaMalakalapalli** [p4lang/tutorials#529]

**Comment by jafingerhut** [comment]
How did you install the P4 development software, such that it led to this error?

**Comment by jafingerhut** [comment]
I should also add that if you are looking for a way to install the open source P4 development tools in such a way that I have personally successfully run the examples in the tutorials repository, you can find instructions for doing so here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
