### ISSUE TITLE
n error occurred during make run Traceback (most recent call last):    File "../../utils/run_exercise.py", line 28, in <module>      import p4runtime_lib.simple_controller    File "/home/inspur/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>      from p4.config.v1 import p4info_pb2 ModuleNotFoundError: No module named 'p4.config'

### ISSUE THREAD

**Issue by asfdd3** [p4lang/tutorials#532]
File "../../utils/run_exercise.py", line 28, in <module>
    import p4runtime_lib.simple_controller
  File "/home/inspur/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    from p4.config.v1 import p4info_pb2
ModuleNotFoundError: No module named 'p4.config'
make: *** [../../utils/Makefile:35: run] Error 1

**Comment by jafingerhut** [comment]
There are many different ways that you might have tried to install this software, leading up to the error that you saw.  Please explain which method you used to install the software, or consider using a VM image that has already had all of the P4 development tools built for you and installed on it.  Many versions of such a VM are available for download here, for example: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by asfdd3** [comment]
I used git clone to install it. Also, does the installation script you mentioned have to install the VM? You can also perform steps on a physical machine

**Comment by jafingerhut** [comment]
Merely performing `git clone` on this repository does not install the P4 development tools, such as the P4 compiler and the behavioral-model (aka BMv2) software switch, which are required for running the tutorial examples.

Did you do any additional steps to install those tools after doing `git clone`?  If not, you need to do more, e.g. following the instructions in the README of this repository to install the required software.

**Comment by asfdd3** [comment]
I installed the p4 interpreter and bmv2. In addition I can perform the described below a script to build on a physical machine p4 environment https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by jafingerhut** [comment]
I have only tested the instructions at https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md as documented there -- on a freshly installed Ubuntu system with one of the supported versions mentioned there, with no other software already installed on it.

If you have a system where you have already installed software packages like protobuf, grpc, BMv2, or p4c, and _then_ you try to follow the instructions at that link, I have very little idea what might happen.  I do not expect good results, though.

**Comment by jafingerhut** [comment]
No follow-up questions for over a month, so closingthis issue.
