### ISSUE TITLE
Way to disable the functionality to write the switch logging into a file?

### ISSUE THREAD

**Issue by fengkeyleaf** [p4lang/tutorials#533]
Good day,

I am testing my program with the Bmv2 model but the switch outputs the logging to a local log file, like s1.log, which will grow very large, like 8 ~ 9 GB, which would make the VM crash. So I wonder there is a way to turn off the logging? Or any recommended suggestions?

Also, there are two logging files as far as I know, one located at /tmp/p4s.s1.log, another located at <my_project>/logs/s1.log. I could let the switch not output the logging into the second file by editing [run_exercise.py ](https://github.com/p4lang/tutorials/blob/master/utils/run_exercise.py#L94), but I don't know how to deal with the first one.

Thanks,

**Comment by jafingerhut** [comment]
See a possible answer to your question here: https://forum.p4.org/t/running-p4lang-tutorials-with-no-logs-and-no-pcaps-generated/1022
