### ISSUE TITLE
Permission to submit p4_16-mode.el to MELPA 

### ISSUE THREAD

**Issue by SohamG** [p4lang/tutorials#535]
Hello,

I am writing to request consent for me to submit [the p4_16 mode for emacs](https://github.com/p4lang/tutorials/blob/master/vm/p4_16-mode.el) from this repo to MELPA for wider availability and easier access. 

I will definitely credit the original authors and preserve references to them in the file's header, and add references to this repo as the original source. I will also use the same license as the repo.

**Comment by jnfoster** [comment]
Thanks! Having a P4_16 mode in MELPA would be great. If you are looking for approval from the original author @vgurevich is the person to contact. But, I think you are clear to go -- I am not a lawyer, but with the Apache2 License, I don't believe there are any obstacles to you distributing it another way .

**Comment by jnfoster** [comment]
I'll close this issue since I think it is basically resolved. Feel free to contact Vladimir out of band.

**Comment by SohamG** [comment]
Update: I have managed to get the mode added to [NonGNU Elpa](https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?id=b299b0d074a4762e99474ba443d37263f87ace1d). Went with (nongnu)ELPA as it ships with emacs by default as compared to MELPA.
