### ISSUE TITLE
VM login and password 

### ISSUE THREAD

**Issue by eliaspiette** [p4lang/tutorials#537]
Hello, are the login and password on the vm p4 and p4? If so, i still do not get a valid identification.

Have a good day !
Elias

**Comment by zhihuacc** [comment]
> Yes. See here:
> 
> https://github.com/p4lang/tutorials/blob/master/vm/root-bootstrap.sh#L70

I typed p4 and p4, but got error and refused to login.

**Comment by jafingerhut** [comment]
@zhihuacc Did you create a VM using the `vagrant up` or `vagrant up dev` commands run within the `vm-ubuntu-20.04` directory?

If not, how did you create the system you are trying to log into?

If yes, did you see anything that looked like error messages in the output?

**Comment by zhihuacc** [comment]
> @zhihuacc Did you create a VM using the `vagrant up` or `vagrant up dev` commands run within the `vm-ubuntu-20.04` directory?
> 
> If not, how did you create the system you are trying to log into?
> 
> If yes, did you see anything that looked like error messages in the output?

Hi, sorry for late reply. I created vm using `vagrant up`. I the error just says "login incorrect" for p4:p4. But finally I login successully with vagrant:vagrant.

**Comment by RithvikChuppala** [comment]
@jafingerhut @zhihuacc any updates? I'm seeing the same issue. It might be because the script hasn't finished installing yet (as per: https://github.com/p4lang/tutorials/issues/120) - could this be the issue and if so, how would we know that its finished installing? I'm doing this a Ubuntu 18.04 machine running VirtualBox Ubuntu 20.04

**Comment by jafingerhut** [comment]
You could also try downloading an already-built and lightly tested VM from here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

I follow the instructions in the `vm-ubuntu-20.04/README.md` file every month to create those images and publish them there.  Occasionally something goes wrong, but usually the installation completes as expected, resulting in a VM where I can log in with p4/p4, or with vagrant/vagrant.

**Comment by zhihuacc** [comment]
> @jafingerhut @zhihuacc any updates? I'm seeing the same issue. It might be because the script hasn't finished installing yet (as per: #120) - could this be the issue and if so, how would we know that its finished installing? I'm doing this a Ubuntu 18.04 machine running VirtualBox Ubuntu 20.04

I can login with account vagrant:vagrant, instead of p4:p4 as stated.

**Comment by RithvikChuppala** [comment]
thanks @jafingerhut, using the prebuilt VM worked!
