### ISSUE TITLE
cpu_port support

### ISSUE THREAD

**Issue by subrnath** [p4lang/tutorials#539]
In https://github.com/p4lang/tutorials/tree/master/exercises/mri, I would like integrate https://github.com/nsg-ethz/p4-learning/blob/master/examples/copy_to_cpu and trying to ad cpu_port. As mentioned in https://github.com/nsg-ethz/p4-learning/blob/master/examples/copy_to_cpu/p4app.json, I am adding the cpu_port in https://github.com/p4lang/tutorials/blob/master/exercises/mri/topology.json

    "switches": {
        "s1": { "runtime_json" : "s1-runtime.json", "cpu_port": true },
        "s2": { "runtime_json" : "s2-runtime.json", "cpu_port": true },
        "s3": { "runtime_json" : "s3-runtime.json", "cpu_port": true }
    },

but don't find ant interface in S1 . https://github.com/nsg-ethz/p4-learning/blob/master/examples/copy_to_cpu/receive.py in s1, throws the error that s1-cpu-eth1 interface is not present. 

Can someone help me what i am missing here. Or, how to add the support for cpu_port in this mininet topology?

**Comment by jafingerhut** [comment]
I would recommend asking your question here instead, where more people are likely to read and respond: https://forum.p4.org
