### ISSUE TITLE
Is it possible to match multiple tables at the same time in P4？

### ISSUE THREAD

**Issue by againwq** [p4lang/tutorials#540]
The pipelines defined in P4 are executed sequentially. Is it possible to match multiple tables at the same time in Ingress Match-Action？Or is it possible to define multiple pipelines sharing one parser and deparser?

**Comment by jafingerhut** [comment]
I would recommend asking questions like these, not specifically related to the tutorials repository, here: https://forum.p4.org

One advantage is that such questions and answers will have a slightly wider audience, and they will be searchable in future for others who are looking for answers.

**Comment by againwq** [comment]
OK,Thanks
