### ISSUE TITLE
gRPC Error: failed to connect to all addresses (UNAVAILABLE)

### ISSUE THREAD

**Issue by sunruifeng0602** [p4lang/tutorials#541]
In the p4runtime exercise, running ./mycontroller.py got the following error:

`gRPC Error: failed to connect to all addresses (UNAVAILABLE)`

And after using the netstat -lpnt command, we get the following results：
![image](https://github.com/p4lang/tutorials/assets/102899087/750edae0-39c0-4e01-a309-890f7851d239)
How can i solve this problem
Thanks

**Comment by jafingerhut** [comment]
I would recommend posting your question here instead https://forum.p4.org because there are likely more people participating there than there are on tutorials Github issues.
