### ISSUE TITLE
[Discuss] The sequence of "Implementing Multicast" to list of exercises

### ISSUE THREAD

**Issue by AdarshRawat1** [p4lang/tutorials#550]
Under which [module](https://github.com/p4lang/tutorials#introduction) should "[Implementing multicast](https://github.com/p4lang/tutorials/tree/master/exercises/multicast)" be placed

**Comment by jafingerhut** [comment]
I think the "Advanced" section seems reasonable.  I would recommend adding it to the end of that list, since it is the newest one, and not part of the original list of tutorials.

**Comment by jafingerhut** [comment]
Sorry, but merging PR #545 seems to have undone this change.  Would you mind creating another PR to add multicast again, and this time also add a brief description like for the other exercises?

**Comment by AdarshRawat1** [comment]
>  Would you mind creating another PR to add multicast again, and this time also add a brief description like for the other exercises?

Sure, I'll create  a new PR by EOD .
