### ISSUE TITLE
Update the basic Exercise with prerequisite section 

### ISSUE THREAD

**Issue by AdarshRawat1** [p4lang/tutorials#561]
## Issue 
A new user usually starts with the first module `basic` exercise and might skip the installation guidelines, resulting in errors like "Module not found" . 

## Possible solution 

_We can explicitly mention following points in the README of `basic` Exercise under a new_ **PREREQUISITE**  _section._ 
- [ Required]The [Obtaining required software](https://github.com/p4lang/tutorials#obtaining-required-software) guidelines link 
- [Optional] Installation options available https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
along with recommend way i.e. preinstalled VM  

## Discuss 
If this section seems reasonable, should we include this only is first exercise or other exercises as well ?

**Comment by jafingerhut** [comment]
IF we add a prerequisite for every exercise (and I'm not sure we should), it should be very brief, e.g. a link to a single location where the prerequisites are described clearly.  I hope that the "Obtaining required software" section is good enough, but past experience suggests to me that no matter what we change, there will still be people that do something differently and then ask questions when things do not work for them.

**Comment by AdarshRawat1** [comment]
> IF we add a prerequisite for every exercise (and I'm not sure we should), it should be very brief, e.g. a link to a single location where the prerequisites are described clearly.

 Sounds reasonable 

>  I hope that the "Obtaining required software" section is good enough.
We can include this section as a single line before every tutorial. 

Something like - 


Make sure you have followed the steps in 
"Obtaining required software" section .

> but past experience suggests to me that no matter what we change, there will still be people that do something differently and then ask questions when things do not work for them.

Totally agreed 👍
