### ISSUE TITLE
Parsing Infiniband Packet with P4

### ISSUE THREAD

**Issue by LiuMicheal** [p4lang/tutorials#569]
Can we use the P4 program to turn a switch equipped with Tofino 2 into an Infiniband switch?

**Comment by jafingerhut** [comment]
I would recommend asking this question at https://forum.p4.org, where there is a bigger audience of people reading and responding, than there is on this Github repo.

**Comment by LiuMicheal** [comment]
Thank you for your reply. I have posted on the P4 forum.
