### ISSUE TITLE
Count TCP_SYN packets for each host : Issue

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/tutorials#58]
Hi everybody,
Please I want count number of SYN request sending by each host on network for this end I create a counter as bellow:

counter ip_src_counter {
    type: packets;
    static: count_table;
    instance_count: 1024;
}
//with action 
action count_action(idx) {
    count(ip_src_counter, idx);
}
// Here I specify (IPsrc and IPdst, srcPort, TCP_SYNfalgs
//Please I want to know if it s the correct way to specify TCP_SYN_flag field (as bellow tcp.tcpFlags1 : exact;)on p4 and how can I also specify TCP_ACK_flag field sending by source if I want to do
table count_table {
    reads {
        ipv4.srcAddr : ternary;
        ipv4.dstAddr : exact;
	tcp.srcPort : ternary;
	tcp.tcpFlags1 : exact;
    }
    actions {
        count_action;
        _drop;
    }
    size : 1024;
}
I generate traffic between hosts then I try to read counter for each host It gives 0 packets 
![display counter](https://user-images.githubusercontent.com/31244674/31490235-243d6844-af3b-11e7-82a4-7f87c882200e.png)

please find attached p4 program
[Counter_SYN_paquet.txt](https://github.com/p4lang/tutorials/files/1378860/Counter_SYN_paquet.txt)

**Comment by antoninbas** [comment]
A few things:
- a direct counter seems more appropriate here, as you seem to want one counter entry for each flow (i.e. for each entry in the table). If you use a direct counter, you will not need to worry about having to manage counter indices yourself.
- I personally would not include `tcp.tcpFlags1` in the match key. Instead, I would wrap the apply statement for the table in a if condition: `if (tcp.tcpFlags1 == <whatever indicates it's a SYN>`) { apply(count_table); }`.
- you do not seem to be adding any entries in your table. If you have no entries, then the table will always miss and you are not going to count anything... You need to add a match-action entry for each flow you want to count, which you can do using the bmv2 simple_switch CLI.

**Comment by Safaamahrach** [comment]
Hi,
Thank you so much for help 
-- For counter if I want to make only direct one What I can make in action of count_table SO  I keep indirect counter and I add direct one as you can see in file  attached
-- I eliminate tcp.tcpFlags1 in match key And I add a condition in control ingress
if (tcp.tcpFlags1 == 02) { apply(count_table); }
-- For entries I attach the file commande.txt that I use

**Comment by Safaamahrach** [comment]
Hi,
Thank you so much for help 
-- For counter if I want to make only direct one What I can make in action of count_table SO  I keep indirect counter and I add direct one as you can see in file  attached (p4 program)
-- I eliminate tcp.tcpFlags1 in match key And I add a condition in control ingress
if (tcp.tcpFlags1 == 02) { apply(count_table); }
-- For entries I attach the file commande.txt that I use
In result I have the same thing I can not display generated packets as before
I want to attach the files but it doesn't work !!!!!
Please your help

**Comment by Safaamahrach** [comment]
I can display  packets with counter when I specify only  ''src-ip'' but When I add a condition on control flow with ''tcpflags'' as bellow  I get 0 packets when displaying counter
control ingress {
if (tcp.tcpFlags1 == 1) // which value I have to define for tcpFlags1
{ apply(count_table); }
Thank you for help

**Comment by jnfoster** [comment]
Closing as this isn't a tutorial issue. Suggest asking for help on p4-dev.
