### ISSUE TITLE
Which file contains the control plane logic?

### ISSUE THREAD

**Issue by drobinkent** [p4lang/tutorials#59]

**Comment by jnfoster** [comment]
For the recent tutorials (D2 and SIGCOMM '17) see the files s*-commands.txt

**Comment by drobinkent** [comment]
My question was not too clear. I am sorry for that. 

I wanted to know, which file contains the code that connects to the switch and runs the commands. I am trying to understand the codes that actually contains the code for a control plane program. not only the commands to manipulate the table.

**Comment by jnfoster** [comment]
For example:
https://github.com/p4lang/tutorials/blob/master/SIGCOMM_2017/utils/mininet/single_switch_mininet.py#L117

-N
