### ISSUE TITLE
P4 switch s1 did not start correctly

### ISSUE THREAD

**Issue by ywhgod** [p4lang/tutorials#605]
when i tried to run basic tutorial, i saw this error ：      
ubuntu@ns7:~/Workspace/P4/tutorials/exercises/basic$ make
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
basic.p4(81): [--Wwarn=unused] warning: 'dstAddr' is unused
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): [--Wwarn=unused] warning: 'port' is unused
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
[--Wwarn=deprecated] warning: .txt format is being deprecated; use .txtpb instead
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter dstAddr
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter port
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
sudo python3 ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
P4 switch s1 did not start correctly.
make: *** [../../utils/Makefile:35: run] Error 1

What is the reason for this, please

**Comment by jafingerhut** [comment]
I would recommend asking such questions on https://forum.p4.org as there are more readers there than on Github issues on this repository.

If you do, you might also want to add details such as:

+ Have you made any local changes to the files, and if so, what are they?
+ How did you install the P4 development tools on your system?
