### ISSUE TITLE
Packet aggregation

### ISSUE THREAD

**Issue by amir-raoofy** [p4lang/tutorials#626]
Hi p4 community, 

I am looking for an example p4 program that is kind of similar to `calc` tutorial, but instead of getting the operands from a single packets, I intend to get the operands from multiple packets. It is kind of an example to do aggregation of payloads of multiple packets which probably requires packet buffering. 

Can this be done via P4? Do you have examples that might resemble this? 

These are the closest pointer I found: https://github.com/LittleD3092/reliable-in-network-aggregation/tree/master and https://www.sciencedirect.com/science/article/pii/S1084804519301687

I appreciate your input. Thanks!

**Comment by jafingerhut** [comment]
The first example that comes to my mind is this one, which is intended to do vector integer addition of data across different packet payloads, as a way to assist some kinds of collective operations like AllReduce being done by the hosts, but with the switches accelerating the operation.

https://github.com/p4lang/p4app-switchML

**Comment by amir-raoofy** [comment]
Dear Andy,

Many thanks for sharing this pointer. That is exactly what I am looking for. I will have a deeper look into it.

Regards,
Amir

**Comment by jafingerhut** [comment]
Closing this issue, as there have been no follow-ups for a while.  Feel free to reopen if desired, or simply create a new issue.
