### ISSUE TITLE
ONF Account Registration could not be registered, so I unable to log in to https://forum.p4.org

### ISSUE THREAD

**Issue by hugo0819** [p4lang/tutorials#627]
I'm sorry to ask here because I couldn't sign up for an ONF account. Each registration shows that an error has occurred. I can't solve this problem and I wonder if it has something to do with my use of VPN since I can't access the website directly in China.

I also would like to know if there are any requirements for the registered email address? Or something else？

So far I've only been able to browse the https://forum.p4.org but not `log in` or `sign up` to ask questions and answers, I'm very sad.

**Comment by hugo0819** [comment]
![download](https://github.com/user-attachments/assets/4121c193-3aa5-4f3c-89d6-48d8da1f1dc7)

**Comment by jafingerhut** [comment]
Unfortunately, I believe this has been a problem for about a month on the account registration part of the https://forum.p4.org web site.  People who are already logged in can remain logged in for a long time, but if you are not logged in, you cannot get logged in.

I will remind some of the people who help administer that site about this issue, to ensure they are aware of it, and hopefully they may be able to correct the problem.

**Comment by jafingerhut** [comment]
This problem was finally fixed some time in October, 2024 (I believe), so closing this issue.  If you have problems logging on to https://forum.p4.org or other P4 communication channels in the future, I would recommend using P4 Zulip to report them, but other channels are fine, too.
