### ISSUE TITLE
add custom headers

### ISSUE THREAD

**Issue by kobe-S9** [p4lang/tutorials#636]
Hello, I am trying to implement the function of adding some custom header to the packet, this function is specifically when a specific condition is met, the packet will resubmit once, and then it will dynamically add the custom header through the condition judgment, my header code is as follows, where HIGH, LOW, LOW is the possible to add header, `
header data_h {
    value_t d00;
    value_t d01;
    value_t d02;
    value_t d03;
    value_t d04;
}
struct headers {
    ethernet_t   ethernet;
    ipv4_t       ipv4;
    udp_t        udp;
    Multi_h      Multi;
    data_h       data;
    data_h       high;
    data_h       low;
    data_h       LOW;
}
`
the judgment condition is as follows, ` if(meta.isResubmit == 1){
                values0.read(hdr.data.d00,meta.valueIndex);
                values1.read(hdr.data.d01,meta.valueIndex);
                values2.read(hdr.data.d02,meta.valueIndex);
                values3.read(hdr.data.d03,meta.valueIndex);
                values4.read(hdr.data.d04,meta.valueIndex);

                if(meta.high != 0){
                    hdr.high.setValid();
                    values0.read(hdr.high.d00,meta.valueIndex+1);
                    values1.read(hdr.high.d01,meta.valueIndex+1);
                    values2.read(hdr.high.d02,meta.valueIndex+1);
                    values3.read(hdr.high.d03,meta.valueIndex+1);
                    values4.read(hdr.high.d04,meta.valueIndex+1);
                }

                if(meta.low != 0){
                    hdr.low.setValid();
                    values0.read(hdr.low.d00,meta.valueIndex+2);
                    values1.read(hdr.low.d01,meta.valueIndex+2);
                    values2.read(hdr.low.d02,meta.valueIndex+2);
                    values3.read(hdr.low.d03,meta.valueIndex+2);
                    values4.read(hdr.low.d04,meta.valueIndex+2);
                }

                if(meta.LOW != 0){
                    hdr.LOW.setValid();
                    values0.read(hdr.LOW.d00,meta.valueIndex+3);
                    values1.read(hdr.LOW.d01,meta.valueIndex+3);
                    values2.read(hdr.LOW.d02,meta.valueIndex+3);
                    values3.read(hdr.LOW.d03,meta.valueIndex+3);
                    values4.read(hdr.LOW.d04,meta.valueIndex+3);
                }               
            }

control MyDeparser(packet_out packet, in headers hdr) {
    apply {

        //parsed headers have to be added again into the packet.
        packet.emit(hdr.ethernet);
        packet.emit(hdr.ipv4);
        packet.emit(hdr.udp);
        packet.emit(hdr.Multi);
        packet.emit(hdr.data);

        packet.emit(hdr.high);
        packet.emit(hdr.low);
        packet.emit(hdr.LOW);

        

    }
}
`
the deparser also emit,  but why my receiver can't display the correct packet, it's not very likely that the python script is wrong.
the s1.log as follows：
`[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparser 'deparser': start
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Updating checksum 'cksum'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'ethernet'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'ipv4'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'udp'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'Multi'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'data'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'low'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparsing header 'LOW'
[01:06:57.021] [bmv2] [D] [thread 135858] [63.1] [cxt 0] Deparser 'deparser': end
[01:06:57.021] [bmv2] [D] [thread 135859] [63.1] [cxt 0] Transmitting packet of size 67 out of port 3`
the reciever.py result:
![Snipaste_2024-10-11_16-39-13](https://github.com/user-attachments/assets/d7960d75-2408-4424-9e61-bc934549f408)

**Comment by jafingerhut** [comment]
Do you have customizations to the Scapy library that know how to parse your custom headers high, low, and LOW?  And you have tested them in other scenarios to verify that they work?

If so, note that in the trace log you show, there is no header 'high' emitted, only 'data' followed immediately by 'low'.  I do not know your Scapy custom header parsing code at all, but if requires a 'high' header to be present to work, then that could be the problem.

If not, then note that Scapy stops decoding headers when it has no more headers it recognizes, and prints the rest of the packet as padding or payload.

In general, I would recommend looking at the raw bytes of the packet contents, and see if they contain the exact sequence of bytes you expect.  Yes, it can be very tedious to do so, but hopefully you only need to do it once or a few times to figure out whether the packet has the correct contents, and something else is wrong, or the packet has unexpected contents, and then you know you need to figure out why it has unexpected contents.

**Comment by kobe-S9** [comment]
> Do you have customizations to the Scapy library that know how to parse your custom headers high, low, and LOW? And you have tested them in other scenarios to verify that they work?
> 
> If so, note that in the trace log you show, there is no header 'high' emitted, only 'data' followed immediately by 'low'. I do not know your Scapy custom header parsing code at all, but if requires a 'high' header to be present to work, then that could be the problem.
> 
> If not, then note that Scapy stops decoding headers when it has no more headers it recognizes, and prints the rest of the packet as padding or payload.
> 
> In general, I would recommend looking at the raw bytes of the packet contents, and see if they contain the exact sequence of bytes you expect. Yes, it can be very tedious to do so, but hopefully you only need to do it once or a few times to figure out whether the packet has the correct contents, and something else is wrong, or the packet has unexpected contents, and then you know you need to figure out why it has unexpected contents.

Thank you sincerely for your reply and advice, I'm not very good at scapy yet I'm not sure if it's a code issue on the scapy side, I checked the raw bytes of the packet content and I found that the LOW layer of the data isn't included while the padding is for the low layer of the content. In the final functionality I hope to achieve, the three layers high, low, and LOW are randomly and dynamically appearing, and may or may not be present.In this example, the low and LOW layers will appear, but since the LOW layer result is not included in the packet, and the padding layer result is the content of the low layer, so I changed the scapy code to receive the low layer in a fixed way, i.e., data>low, but it still can't display the packet content correctly. Here is my receiver code script
`from scapy.all import *
from scapy.packet import Packet
from scapy.fields import BitField, IntField
import sys
import threading


class Multi(Packet):
    name = "Multi"
    fields_desc = [
        IntField("bitmap", 0),
        BitField("fanIndegree", 0, 8),
        BitField("overflow", 0, 1),
        BitField("isResend", 0, 1),
        BitField("ECN", 0, 1),
        BitField("types", 0, 4),
        BitField("isACK", 0, 1),
        IntField("index", 0)
    ]


class data(Packet):
    name = "data"
    fields_desc = [
        BitField("d00", 0, 8),
        BitField("d01", 0, 8),
        BitField("d02", 0, 8),
        BitField("d03", 0, 8),
        BitField("d04", 0, 8)
    ]


class high(Packet):
    name = "high"
    fields_desc = [
        BitField("d00", 0, 8),
        BitField("d01", 0, 8),
        BitField("d02", 0, 8),
        BitField("d03", 0, 8),
        BitField("d04", 0, 8)
    ]


class low(Packet):
    name = "low"
    fields_desc = [
        BitField("d00", 0, 8),
        BitField("d01", 0, 8),
        BitField("d02", 0, 8),
        BitField("d03", 0, 8),
        BitField("d04", 0, 8)
    ]


class LOW(Packet):
    name = "LOW"
    fields_desc = [
        BitField("d00", 0, 8),
        BitField("d01", 0, 8),
        BitField("d02", 0, 8),
        BitField("d03", 0, 8),
        BitField("d04", 0, 8)
    ]


# 绑定层次关系，支持 data 直接连接 Low 或经过 high 层
bind_layers(UDP, Multi)
bind_layers(Multi, data)
#bind_layers(data, high)  # data > high
#bind_layers(high, low)   # high > low
#bind_layers(low, LOW)  # low > LOW
bind_layers(data, low)
#bind_layers(data,LOW )      # 允许 data 直接连接 LOW层
#bind_layers(high, LOW) 

class receiver(object):
    def __init__(self, interface="eth0"):
        self.interface = interface
        self.stop_event = threading.Event()  # 用于停止监听

    def packet_callback(self, packet):
        # 如果数据包包含 Multi 层，开始解析
        if packet.haslayer(Multi):

            print("Received Multi packet:")
            packet.show()



    def run(self):
        while True:
            self.stop_event.clear()  # 清除停止事件
            print("Listening...")
            sniff(iface=self.interface, filter="udp", prn=self.packet_callback,
                  stop_filter=lambda p: self.stop_event.is_set())
            print("Listening stopped, restarting...")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Using default interface\n")
        receiver1 = receiver()
    else:
        receiver1 = receiver(interface=sys.argv[1])
    receiver1.run()
`

**Comment by kobe-S9** [comment]
> Do you have customizations to the Scapy library that know how to parse your custom headers high, low, and LOW? And you have tested them in other scenarios to verify that they work?
> 
> If so, note that in the trace log you show, there is no header 'high' emitted, only 'data' followed immediately by 'low'. I do not know your Scapy custom header parsing code at all, but if requires a 'high' header to be present to work, then that could be the problem.
> 
> If not, then note that Scapy stops decoding headers when it has no more headers it recognizes, and prints the rest of the packet as padding or payload.
> 
> In general, I would recommend looking at the raw bytes of the packet contents, and see if they contain the exact sequence of bytes you expect. Yes, it can be very tedious to do so, but hopefully you only need to do it once or a few times to figure out whether the packet has the correct contents, and something else is wrong, or the packet has unexpected contents, and then you know you need to figure out why it has unexpected contents.
Thank you very much for your help, I found out what was causing the error because I was dynamically adding the headers causing the message length to change, so I should have dynamically changed the fields for ip and udp to indicate the length which is something I hadn't done previously

**Comment by jafingerhut** [comment]
No follow-ups to this issue for a while, and the last comment appears to indicate that the issue creator has found and fixed their problems.  Reopen if desired, or create a new issue if new problems arise.
