### ISSUE TITLE
Small problems

### ISSUE THREAD

**Issue by NevermeChu** [p4lang/tutorials#646]
Could someone tell me how to enlarge the border of this window? It's makes me uncomfortable.By the way, almost all icons on the system are missing,and i don`t know what is going on.

![image](https://github.com/user-attachments/assets/fdf7159c-caa0-40d1-982c-dbc000d46651)

**Comment by jafingerhut** [comment]
If you have just used the instructions in the file vm-ubuntu-24.04/README.md to build a VM running Ubuntu 24.04, I have just restored some instructions to that file that I moved elsewhere a few weeks ago, in a section titled "GUI settings that you will likely wish to change".  Please see there for some steps that include ones for changing the icon settings on the GUI desktop.

+ https://github.com/p4lang/tutorials/tree/master/vm-ubuntu-24.04

**Comment by NevermeChu** [comment]
Oh thank you for your patience! I am new to P4, and your suggetsions helps a lot. But i am still confused to all of these new things. There are things i can`t solve, could you please help me with it?
1.Border of windows is too small. Your suggestions about icons missing work well, but not work for this problem. And i spent hours to enlarge the border but unsuccessfully. I even modified relevant confuguration files of openbox, although which might not be a correct solution.This failed too.
2.What should be in the system if it is correctly downloaded and installed. I just ran the command 'vagrant up dev' and waited for it finishing.But there are no extra application icons such as Wireshark. Shoud Wireshark be here when the system is correctly iinstalled? Is my system unnormal for its wrong downloading or installing?

**Comment by jafingerhut** [comment]
2. There should be a Wireshark icon on the desktop for the user named "p4", but there is no such icon created by the install scripts for the user account named "vagrant".  The Wireshark icon doesn't _look_ like the Wireshark icon, unfortunately, but it should look like some kind of icon labeled "Wireshark".

1. I have not looked for settings regarding the border width of windows.  It is probably possible to install a different GUI desktop environment, e.g. Ubuntu Desktop Linux's default Gnome GUI, using a command like `sudo apt-get install ubuntu-desktop-minimal`, and then rebooting after it finishes installing.  I am trying that for the first time right now to see what happens.

**Comment by jafingerhut** [comment]
Doing `sudo apt-get install ubuntu-desktop-minimal` and then rebooting the system does change the desktop to the default Gnome desktop used by Ubuntu Desktop Linux, for which the settings for changing how things appear might be more familiar to more Linux users, and there is probably more easily searchable on-line documentation for how to change those settings.

**Comment by NevermeChu** [comment]
Thank you for your patience!I will try later.Due to the problem of missing Wireshark(not only the icon on desktop but the application itself which i can`t find at anywhere), i suspect that something wrong happened when the system downloading and installing.I will redo the installing later.Thank you again for your patience.You are so kind.

**Comment by jafingerhut** [comment]
I have updated the install README again today, giving instructions for changing the GUI desktop to the default one that Ubuntu Linux uses, called GNOME, in case that is more famliiar to you: https://github.com/p4lang/tutorials/tree/master/vm-ubuntu-24.04/README.md

**Comment by NevermeChu** [comment]
Thank you, indeed i am more familiar with GNOME. I will try it later.Nice if you for your patience and assistance.

**Comment by jafingerhut** [comment]
Closing this issue, as it seems resolved now.
