### ISSUE TITLE
Bug in apptopo.py in P4D2_2017_Spring

### ISSUE THREAD

**Issue by alex1230608** [p4lang/tutorials#66]
Hi,

I think there is a small copy-paste bug at line 57 in `P4D2_2017_Spring/utils/mininet/apptopo.py`

`delay_key = ''.join(sorted([host_name, sw]))`

should be 

`delay_key = ''.join(sorted([sw1, sw2]))`

Hope it helps!

**Comment by Abhinavcode13** [comment]
This bug is fixed and can be closed now. @jafingerhut

**Comment by jafingerhut** [comment]
@Abhinavcode13 Thanks for investigating!  Closing this issue.
