### ISSUE TITLE
could not find declaration for update_checksum

### ISSUE THREAD

**Issue by Yukinarii** [p4lang/tutorials#68]
Hello, is there anyone have the problem as the follow?

Could not find declaration for update_checksum
update_checksum(
^^^^^^^^^^^^
Compile failed

**Comment by antoninbas** [comment]
I think you just need to update your p4lang/p4c version to something more recent. The checksum API in v1model was modified recently and the P4 programs in the tutorials repo were updated to use the new API. As a result you need the latest compiler version with the latest v1model definition.

**Comment by Yukinarii** [comment]
Thank you!
