### ISSUE TITLE
Issues About SIGCOMM_2015 Source Routing   

### ISSUE THREAD

**Issue by JingYuan0818** [p4lang/tutorials#9]
I have set up the necessary software and environment for Exercise 1 : Source Routing, but I face some problems when I want to run it:

The shell reports:
 **Command '['/home/jy/tutorials/./bmv2/tools/runtime_CLI.py', '--json', 'source_routing.json', '--thrift-port', '22222']' returned non-zero exit status 1
Could not connect to thrift client on port 22222
Make sure the switch is running and that you have the right port**

And when one host sends a packet, the other cannot receive.

**Comment by antoninbas** [comment]
In all likelihood this means that the switch did not start properly. I would recommend that you try starting the switch separately (look for the command in the shell script) and see if you get an error message.

**Comment by antoninbas** [comment]
closing this since no update
