### ISSUE TITLE
Modify examples to use P4Runtime instead of CLI.

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#99]

**Comment by jafingerhut** [comment]
The command `simple_switch_CLI` is mentioned in a few of the latest Python programs in this repo, but `simple_switch_CLI` is never mentioned in any of the documentation as of 2024-Mar-07.

It would be great if someone could check whether those mentions of `simple_switch_CLI` in the Python programs are actually _used_ when running the exercises, or whether they are vestigial left-over old code that is now dead.

**Comment by stano45** [comment]
@jafingerhut Since there is now an example usage of `simple_switch_CLI`, do you think this issue can be closed?

**Comment by jafingerhut** [comment]
Yes, I will close it now.
